function generateRange(start, end) {
    return Array.from({ length: (end - start + 1) }, (_, i) => i + start);
}



const pokedexData = {
    gen1: {
    1: { name: "bulbasaur", type: "Grass/Poison", image:"images/RBY Dex/bulbasaur.png" },
    2: { name: "ivysaur", type: "Grass/Poison", image:"images/RBY Dex/ivysaur.png" },
    3: { name: "venusaur", type: "Grass/Poison", image:"images/RBY Dex/venusaur.png" },
    4: { name: "charmander", type: "Fire", image:"images/RBY Dex/charmander.png" },
    5: { name: "charmeleon", type: "Fire", image:"images/RBY Dex/charmeleon.png" },
    6: { name: "charizard", type: "Fire/Flying", image:"images/RBY Dex/charizard.png" },
    7: { name: "squirtle", type: "Water", image:"images/RBY Dex/squirtle.png" },
    8: { name: "wartortle", type: "Water", image:"images/RBY Dex/wartortle.png" },
    9: { name: "blastoise", type: "Water", image:"images/RBY Dex/blastoise.png" },
    10: { name: "caterpie", type: "Bug", image:"images/RBY Dex/caterpie.png" },
    11: { name: "metapod", type: "Bug", image:"images/RBY Dex/metapod.png" },
    12: { name: "butterfree", type: "Bug/Flying", image:"images/RBY Dex/butterfree.png" },
    13: { name: "weedle", type: "Bug/Poison", image:"images/RBY Dex/weedle.png" },
    14: { name: "kakuna", type: "Bug/Poison", image:"images/RBY Dex/kakuna.png" },
    15: { name: "beedrill", type: "Bug/Poison", image:"images/RBY Dex/beedrill.png" },
    16: { name: "pidgey", type: "Normal/Flying", image:"images/RBY Dex/pidgey.png" },
    17: { name: "pidgeotto", type: "Normal/Flying", image:"images/RBY Dex/pidgeotto.png" },
    18: { name: "pidgeot", type: "Normal/Flying", image:"images/RBY Dex/pidgeot.png" },
    19: { name: "rattata", type: "Normal", image:"images/RBY Dex/rattata.png" },
    20: { name: "raticate", type: "Normal", image:"images/RBY Dex/raticate.png" },
    21: { name: "spearow", type: "Normal/Flying", image:"images/RBY Dex/spearow.png" },
    22: { name: "fearow", type: "Normal/Flying", image:"images/RBY Dex/fearow.png" },
    23: { name: "ekans", type: "Poison", image:"images/RBY Dex/ekans.png" },
    24: { name: "arbok", type: "Poison", image:"images/RBY Dex/arbok.png" },
    25: { name: "pikachu", type: "Electric", image:"images/RBY Dex/pikachu.png" },
    26: { name: "raichu", type: "Electric", image:"images/RBY Dex/raichu.png" },
    27: { name: "sandshrew", type: "Ground", image:"images/RBY Dex/sandshrew.png" },
    28: { name: "sandslash", type: "Ground", image:"images/RBY Dex/sandslash.png" },
    29: { name: "nidoran-♀", type: "Poison", image:"images/RBY Dex/nidoran-♀.png" },
    30: { name: "nidorina", type: "Poison", image:"images/RBY Dex/nidorina.png" },
    31: { name: "nidoqueen", type: "Poison/Ground", image:"images/RBY Dex/nidoqueen.png" },
    32: { name: "nidoran-♂", type: "Poison", image:"images/RBY Dex/nidoran-♂.png" },
    33: { name: "nidorino", type: "Poison", image:"images/RBY Dex/nidorino.png" },
    34: { name: "nidoking", type: "Poison/Ground", image:"images/RBY Dex/nidoking.png" },
    35: { name: "clefairy", type: "Fairy", image:"images/RBY Dex/clefairy.png" },
    36: { name: "clefable", type: "Fairy", image:"images/RBY Dex/clefable.png" },
    37: { name: "vulpix", type: "Fire", image:"images/RBY Dex/vulpix.png" },
    38: { name: "ninetales", type: "Fire", image:"images/RBY Dex/ninetales.png" },
    39: { name: "jigglypuff", type: "Normal/Fairy", image:"images/RBY Dex/jigglypuff.png" },
    40: { name: "wigglytuff", type: "Normal/Fairy", image:"images/RBY Dex/wigglytuff.png" },
    41: { name: "zubat", type: "Poison/Flying", image:"images/RBY Dex/zubat.png" },
    42: { name: "golbat", type: "Poison/Flying", image:"images/RBY Dex/golbat.png" },
    43: { name: "oddish", type: "Grass/Poison", image:"images/RBY Dex/oddish.png" },
    44: { name: "gloom", type: "Grass/Poison", image:"images/RBY Dex/gloom.png" },
    45: { name: "vileplume", type: "Grass/Poison", image:"images/RBY Dex/vileplume.png" },
    46: { name: "paras", type: "Bug/Grass", image:"images/RBY Dex/paras.png" },
    47: { name: "parasect", type: "Bug/Grass", image:"images/RBY Dex/parasect.png" },
    48: { name: "venonat", type: "Bug/Poison", image:"images/RBY Dex/venonat.png" },
    49: { name: "venomoth", type: "Bug/Poison", image:"images/RBY Dex/venomoth.png" },
    50: { name: "diglett", type: "Ground", image:"images/RBY Dex/diglett.png" },
    51: { name: "dugtrio", type: "Ground", image:"images/RBY Dex/dugtrio.png" },
    52: { name: "meowth", type: "Normal", image:"images/RBY Dex/meowth.png" },
    53: { name: "persian", type: "Normal", image:"images/RBY Dex/persian.png" },
    54: { name: "psyduck", type: "Water", image:"images/RBY Dex/psyduck.png" },
    55: { name: "golduck", type: "Water", image:"images/RBY Dex/golduck.png" },
    56: { name: "mankey", type: "Fighting", image:"images/RBY Dex/mankey.png" },
    57: { name: "primeape", type: "Fighting", image:"images/RBY Dex/primeape.png" },
    58: { name: "growlithe", type: "Fire", image:"images/RBY Dex/growlithe.png" },
    59: { name: "arcanine", type: "Fire", image:"images/RBY Dex/arcanine.png" },
    60: { name: "poliwag", type: "Water", image:"images/RBY Dex/poliwag.png" },
    61: { name: "poliwhirl", type: "Water", image:"images/RBY Dex/poliwhirl.png" },
    62: { name: "poliwrath", type: "Water/Fighting", image:"images/RBY Dex/poliwrath.png" },
    63: { name: "abra", type: "Psychic", image:"images/RBY Dex/abra.png" },
    64: { name: "kadabra", type: "Psychic", image:"images/RBY Dex/kadabra.png" },
    65: { name: "alakazam", type: "Psychic", image:"images/RBY Dex/alakazam.png" },
    66: { name: "machop", type: "Fighting", image:"images/RBY Dex/machop.png" },
    67: { name: "machoke", type: "Fighting", image:"images/RBY Dex/machoke.png" },
    68: { name: "machamp", type: "Fighting", image:"images/RBY Dex/machamp.png" },
    69: { name: "bellsprout", type: "Grass/Poison", image:"images/RBY Dex/bellsprout.png" },
    70: { name: "weepinbell", type: "Grass/Poison", image:"images/RBY Dex/weepinbell.png" },
    71: { name: "victreebel", type: "Grass/Poison", image:"images/RBY Dex/victreebel.png" },
    72: { name: "tentacool", type: "Water/Poison", image:"images/RBY Dex/tentacool.png" },
    73: { name: "tentacruel", type: "Water/Poison", image:"images/RBY Dex/tentacruel.png" },
    74: { name: "geodude", type: "Rock/Ground", image:"images/RBY Dex/geodude.png" },
    75: { name: "graveler", type: "Rock/Ground", image:"images/RBY Dex/graveler.png" },
    76: { name: "golem", type: "Rock/Ground", image:"images/RBY Dex/golem.png" },
    77: { name: "ponyta", type: "Fire", image:"images/RBY Dex/ponyta.png" },
    78: { name: "rapidash", type: "Fire", image:"images/RBY Dex/rapidash.png" },
    79: { name: "slowpoke", type: "Water/Psychic", image:"images/RBY Dex/slowpoke.png" },
    80: { name: "slowbro", type: "Water/Psychic", image:"images/RBY Dex/slowbro.png" },
    81: { name: "magnemite", type: "Electric/Steel", image:"images/RBY Dex/magnemite.png" },
    82: { name: "magneton", type: "Electric/Steel", image:"images/RBY Dex/magneton.png" },
    83: { name: "farfetch'd", type: "Normal/Flying", image:"images/RBY Dex/farfetchd.png" },
    84: { name: "doduo", type: "Normal/Flying", image:"images/RBY Dex/doduo.png" },
    85: { name: "dodrio", type: "Normal/Flying", image:"images/RBY Dex/dodrio.png" },
    86: { name: "seel", type: "Water", image:"images/RBY Dex/seel.png" },
    87: { name: "dewgong", type: "Water/Ice", image:"images/RBY Dex/dewgong.png" },
    88: { name: "grimer", type: "Poison", image:"images/RBY Dex/grimer.png" },
    89: { name: "muk", type: "Poison", image:"images/RBY Dex/muk.png" },
    90: { name: "shellder", type: "Water", image:"images/RBY Dex/shellder.png" },
    91: { name: "cloyster", type: "Water/Ice", image:"images/RBY Dex/cloyster.png" },
    92: { name: "gastly", type: "Ghost/Poison", image:"images/RBY Dex/gastly.png" },
    93: { name: "haunter", type: "Ghost/Poison", image:"images/RBY Dex/haunter.png" },
    94: { name: "gengar", type: "Ghost/Poison", image:"images/RBY Dex/gengar.png" },
    95: { name: "onix", type: "Rock/Ground", image:"images/RBY Dex/onix.png" },
    96: { name: "drowzee", type: "Psychic", image:"images/RBY Dex/drowzee.png" },
    97: { name: "hypno", type: "Psychic", image:"images/RBY Dex/hypno.png" },
    98: { name: "krabby", type: "Water", image:"images/RBY Dex/krabby.png" },
    99: { name: "kingler", type: "Water", image:"images/RBY Dex/kingler.png" },
    100: { name: "voltorb", type: "Electric", image:"images/RBY Dex/voltorb.png" },
    101: { name: "electrode", type: "Electric", image:"images/RBY Dex/electrode.png" },
    102: { name: "exeggcute", type: "Grass/Psychic", image:"images/RBY Dex/exeggcute.png" },
    103: { name: "exeggutor", type: "Grass/Psychic", image:"images/RBY Dex/exeggutor.png" },
    104: { name: "cubone", type: "Ground", image:"images/RBY Dex/cubone.png" },
    105: { name: "marowak", type: "Ground", image:"images/RBY Dex/marowak.png" },
    106: { name: "hitmonlee", type: "Fighting", image:"images/RBY Dex/hitmonlee.png" },
    107: { name: "hitmonchan", type: "Fighting", image:"images/RBY Dex/hitmonchan.png" },
    108: { name: "lickitung", type: "Normal", image:"images/RBY Dex/lickitung.png" },
    109: { name: "koffing", type: "Poison", image:"images/RBY Dex/koffing.png" },
    110: { name: "weezing", type: "Poison", image:"images/RBY Dex/weezing.png" },
    111: { name: "rhyhorn", type: "Ground/Rock", image:"images/RBY Dex/rhyhorn.png" },
    112: { name: "rhydon", type: "Ground/Rock", image:"images/RBY Dex/rhydon.png" },
    113: { name: "chansey", type: "Normal", image:"images/RBY Dex/chansey.png" },
    114: { name: "tangela", type: "Grass", image:"images/RBY Dex/tangela.png" },
    115: { name: "kangaskhan", type: "Normal", image:"images/RBY Dex/kangaskhan.png" },
    116: { name: "horsea", type: "Water", image:"images/RBY Dex/horsea.png" },
    117: { name: "seadra", type: "Water", image:"images/RBY Dex/seadra.png" },
    118: { name: "goldeen", type: "Water", image:"images/RBY Dex/goldeen.png" },
    119: { name: "seaking", type: "Water", image:"images/RBY Dex/seaking.png" },
    120: { name: "staryu", type: "Water", image:"images/RBY Dex/staryu.png" },
    121: { name: "starmie", type: "Water/Psychic", image:"images/RBY Dex/starmie.png" },
    122: { name: "mr-mime", type: "Psychic/Fairy", image:"images/RBY Dex/mr-mime.png" },
    123: { name: "scyther", type: "Bug/Flying", image:"images/RBY Dex/scyther.png" },
    124: { name: "jynx", type: "Ice/Psychic", image:"images/RBY Dex/jynx.png" },
    125: { name: "electabuzz", type: "Electric", image:"images/RBY Dex/electabuzz.png" },
    126: { name: "magmar", type: "Fire", image:"images/RBY Dex/magmar.png" },
    127: { name: "pinsir", type: "Bug", image:"images/RBY Dex/pinsir.png" },
    128: { name: "tauros", type: "Normal", image:"images/RBY Dex/tauros.png" },
    129: { name: "magikarp", type: "Water", image:"images/RBY Dex/magikarp.png" },
    130: { name: "gyarados", type: "Water/Flying", image:"images/RBY Dex/gyarados.png" },
    131: { name: "lapras", type: "Water/Ice", image:"images/RBY Dex/lapras.png" },
    132: { name: "ditto", type: "Normal", image:"images/RBY Dex/ditto.png" },
    133: { name: "eevee", type: "Normal", image:"images/RBY Dex/eevee.png" },
    134: { name: "vaporeon", type: "Water", image:"images/RBY Dex/vaporeon.png" },
    135: { name: "jolteon", type: "Electric", image:"images/RBY Dex/jolteon.png" },
    136: { name: "flareon", type: "Fire", image:"images/RBY Dex/flareon.png" },
    137: { name: "porygon", type: "Normal", image:"images/RBY Dex/porygon.png" },
    138: { name: "omanyte", type: "Rock/Water", image:"images/RBY Dex/omanyte.png" },
    139: { name: "omastar", type: "Rock/Water", image:"images/RBY Dex/omastar.png" },
    140: { name: "kabuto", type: "Rock/Water", image:"images/RBY Dex/kabuto.png" },
    141: { name: "kabutops", type: "Rock/Water", image:"images/RBY Dex/kabutops.png" },
    142: { name: "aerodactyl", type: "Rock/Flying", image:"images/RBY Dex/aerodactyl.png" },
    143: { name: "snorlax", type: "Normal", image:"images/RBY Dex/snorlax.png" },
    144: { name: "articuno", type: "Ice/Flying", image:"images/RBY Dex/articuno.png" },
    145: { name: "zapdos", type: "Electric/Flying", image:"images/RBY Dex/zapdos.png" },
    146: { name: "moltres", type: "Fire/Flying", image:"images/RBY Dex/moltres.png" },
    147: { name: "dratini", type: "Dragon", image:"images/RBY Dex/dratini.png" },
    148: { name: "dragonair", type: "Dragon", image:"images/RBY Dex/dragonair.png" },
    149: { name: "dragonite", type: "Dragon/Flying", image:"images/RBY Dex/dragonite.png" },
    150: { name: "mewtwo", type: "Psychic", image:"images/RBY Dex/mewtwo.png" },
    151: { name: "mew", type: "Psychic", image:"images/RBY Dex/mew.png" }
    },
    gen2: {
    152: {name: "Chikorita", type: "Grass", image:"images/GSC Dex/chikorita.png" },
    153: {name: "Bayleef", type: "Grass", image:"images/GSC Dex/bayleef.png" },
    154: {name: "Meganium", type: "Grass", image:"images/GSC Dex/meganium.png" },
    155: {name: "Cyndaquil", type: "Fire", image:"images/GSC Dex/cyndaquil.png" },
    156: {name: "Quilava", type: "Fire", image:"images/GSC Dex/quilava.png" },
    157: {name: "Typhlosion", type: "Fire", image:"images/GSC Dex/typhlosion.png" },
    158: {name: "Totodile", type: "Water", image:"images/GSC Dex/totodile.png" },
    159: {name: "Croconaw", type: "Water", image:"images/GSC Dex/croconaw.png" },
    160: {name: "Feraligatr", type: "Water", image:"images/GSC Dex/feraligatr.png" },
    161: {name: "Sentret", type: "Normal", image:"images/GSC Dex/sentret.png" },
    162: {name: "Furret", type: "Normal", image:"images/GSC Dex/furret.png" },
    163: {name: "Hoothoot", type: "Normal/Flying", image:"images/GSC Dex/hoothoot.png" },
    164: {name: "Noctowl", type: "Normal/Flying", image:"images/GSC Dex/noctowl.png" },
    165: {name: "Ledyba", type: "Bug/Flying", image:"images/GSC Dex/ledyba.png" },
    166: {name: "Ledian", type: "Bug/Flying", image:"images/GSC Dex/ledian.png" },
    167: {name: "Spinarak", type: "Bug/Poison", image:"images/GSC Dex/spinarak.png" },
    168: {name: "Ariados", type: "Bug/Poison", image:"images/GSC Dex/ariados.png" },
    169: {name: "Crobat", type: "Poison/Flying", image:"images/GSC Dex/crobat.png" },
    170: {name: "Chinchou", type: "Water/Electric", image:"images/GSC Dex/chinchou.png" },
    171: {name: "Lanturn", type: "Water/Electric", image:"images/GSC Dex/lanturn.png" },
    172: {name: "Pichu", type: "Electric", image:"images/GSC Dex/pichu.png" },
    173: {name: "Cleffa", type: "Fairy", image:"images/GSC Dex/cleffa.png" },
    174: {name: "Igglybuff", type: "Normal/Fairy", image:"images/GSC Dex/igglybuff.png" },
    175: {name: "Togepi", type: "Fairy", image:"images/GSC Dex/togepi.png" },
    176: {name: "Togetic", type: "Fairy/Flying", image:"images/GSC Dex/togetic.png" },
    177: {name: "Natu", type: "Psychic/Flying", image:"images/GSC Dex/natu.png" },
    178: {name: "Xatu", type: "Psychic/Flying", image:"images/GSC Dex/xatu.png" },
    179: {name: "Mareep", type: "Electric", image:"images/GSC Dex/mareep.png" },
    180: {name: "Flaaffy", type: "Electric", image:"images/GSC Dex/flaaffy.png" },
    181: {name: "Ampharos", type: "Electric", image:"images/GSC Dex/ampharos.png" },
    182: {name: "Bellossom", type: "Grass", image:"images/GSC Dex/bellossom.png" },
    183: {name: "Marill", type: "Water/Fairy", image:"images/GSC Dex/marill.png" },
    184: {name: "Azumarill", type: "Water/Fairy", image:"images/GSC Dex/azumarill.png" },
    185: {name: "Sudowoodo", type: "Rock", image:"images/GSC Dex/sudowoodo.png" },
    186: {name: "Politoed", type: "Water", image:"images/GSC Dex/politoed.png" },
    187: {name: "Hoppip", type: "Grass/Flying", image:"images/GSC Dex/hoppip.png" },
    188: {name: "Skiploom", type: "Grass/Flying", image:"images/GSC Dex/skiploom.png" },
    189: {name: "Jumpluff", type: "Grass/Flying", image:"images/GSC Dex/jumpluff.png" },
    190: {name: "Aipom", type: "Normal", image:"images/GSC Dex/aipom.png" },
    191: {name: "Sunkern", type: "Grass", image:"images/GSC Dex/sunkern.png" },
    192: {name: "Sunflora", type: "Grass", image:"images/GSC Dex/sunflora.png" },
    193: {name: "Yanma", type: "Bug/Flying", image:"images/GSC Dex/yanma.png" },
    194: {name: "Wooper", type: "Water/Ground", image:"images/GSC Dex/wooper.png" },
    195: {name: "Quagsire", type: "Water/Ground", image:"images/GSC Dex/quagsire.png" },
    196: {name: "Espeon", type: "Psychic", image:"images/GSC Dex/espeon.png" },
    197: {name: "Umbreon", type: "Dark", image:"images/GSC Dex/umbreon.png" },
    198: {name: "Murkrow", type: "Dark/Flying", image:"images/GSC Dex/murkrow.png" },
    199: {name: "Slowking", type: "Water/Psychic", image:"images/GSC Dex/slowking.png" },
    200: {name: "Misdreavus", type: "Ghost", image:"images/GSC Dex/misdreavus.png" },
    201: {name: "Unown", type: "Psychic", image:"images/GSC Dex/unown.png" },
    202: {name: "Wobbuffet", type: "Psychic", image:"images/GSC Dex/wobbuffet.png" },
    203: {name: "Girafarig", type: "Normal/Psychic", image:"images/GSC Dex/girafarig.png" },
    204: {name: "Pineco", type: "Bug", image:"images/GSC Dex/pineco.png" },
    205: {name: "Forretress", type: "Bug/Steel", image:"images/GSC Dex/forretress.png" },
    206: {name: "Dunsparce", type: "Normal", image:"images/GSC Dex/dunsparce.png" },
    207: {name: "Gligar", type: "Ground/Flying", image:"images/GSC Dex/gligar.png" },
    208: {name: "Steelix", type: "Steel/Ground", image:"images/GSC Dex/steelix.png" },
    209: {name: "Snubbull", type: "Fairy", image:"images/GSC Dex/snubbull.png" },
    210: {name: "Granbull", type: "Fairy", image:"images/GSC Dex/granbull.png" },
    211: {name: "Qwilfish", type: "Water/Poison", image:"images/GSC Dex/qwilfish.png" },
    212: {name: "Scizor", type: "Bug/Steel", image:"images/GSC Dex/scizor.png" },
    213: {name: "Shuckle", type: "Bug/Rock", image:"images/GSC Dex/shuckle.png" },
    214: {name: "Heracross", type: "Bug/Fighting", image:"images/GSC Dex/heracross.png" },
    215: {name: "Sneasel", type: "Dark/Ice", image:"images/GSC Dex/sneasel.png" },
    216: {name: "Teddiursa", type: "Normal", image:"images/GSC Dex/teddiursa.png" },
    217: {name: "Ursaring", type: "Normal", image:"images/GSC Dex/ursaring.png" },
    218: {name: "Slugma", type: "Fire", image:"images/GSC Dex/slugma.png" },
    219: {name: "Magcargo", type: "Fire/Rock", image:"images/GSC Dex/magcargo.png" },
    220: {name: "Swinub", type: "Ice/Ground", image:"images/GSC Dex/swinub.png" },
    221: {name: "Piloswine", type: "Ice/Ground", image:"images/GSC Dex/piloswine.png" },
    222: {name: "Corsola", type: "Water/Rock", image:"images/GSC Dex/corsola.png" },
    223: {name: "Remoraid", type: "Water", image:"images/GSC Dex/remoraid.png" },
    224: {name: "Octillery", type: "Water", image:"images/GSC Dex/octillery.png" },
    225: {name: "Delibird", type: "Ice/Flying", image:"images/GSC Dex/delibird.png" },
    226: {name: "Mantine", type: "Water/Flying", image:"images/GSC Dex/mantine.png" },
    227: {name: "Skarmory", type: "Steel/Flying", image:"images/GSC Dex/skarmory.png" },
    228: {name: "Houndour", type: "Dark/Fire", image:"images/GSC Dex/houndour.png" },
    229: {name: "Houndoom", type: "Dark/Fire", image:"images/GSC Dex/houndoom.png" },
    230: {name: "Kingdra", type: "Water/Dragon", image:"images/GSC Dex/kingdra.png" },
    231: {name: "Phanpy", type: "Ground", image:"images/GSC Dex/phanpy.png" },
    232: {name: "Donphan", type: "Ground", image:"images/GSC Dex/donphan.png" },
    233: {name: "Porygon2", type: "Normal", image:"images/GSC Dex/porygon2.png" },
    234: {name: "Stantler", type: "Normal", image:"images/GSC Dex/stantler.png" },
    235: {name: "Smeargle", type: "Normal", image:"images/GSC Dex/smeargle.png" },
    236: {name: "Tyrogue", type: "Fighting", image:"images/GSC Dex/tyrogue.png" },
    237: {name: "Hitmontop", type: "Fighting", image:"images/GSC Dex/hitmontop.png" },
    238: {name: "Smoochum", type: "Ice/Psychic", image:"images/GSC Dex/smoochum.png" },
    239: {name: "Elekid", type: "Electric", image:"images/GSC Dex/elekid.png" },
    240: {name: "Magby", type: "Fire", image:"images/GSC Dex/magby.png" },
    241: {name: "Miltank", type: "Normal", image:"images/GSC Dex/miltank.png" },
    242: {name: "Blissey", type: "Normal", image:"images/GSC Dex/blissey.png" },
    243: {name: "Raikou", type: "Electric", image:"images/GSC Dex/raikou.png" },
    244: {name: "Entei", type: "Fire", image:"images/GSC Dex/entei.png" },
    245: {name: "Suicune", type: "Water", image:"images/GSC Dex/suicune.png" },
    246: {name: "Larvitar", type: "Rock/Ground", image:"images/GSC Dex/larvitar.png" },
    247: {name: "Pupitar", type: "Rock/Ground", image:"images/GSC Dex/pupitar.png" },
    248: {name: "Tyranitar", type: "Rock/Dark", image:"images/GSC Dex/tyranitar.png" },
    249: {name: "Lugia", type: "Psychic/Flying", image:"images/GSC Dex/lugia.png" },
    250: {name: "Ho-Oh", type: "Fire/Flying", image:"images/GSC Dex/Ho-Oh.png" },
    251: {name: "Celebi", type: "Psychic/Grass", image:"images/GSC Dex/celebi.png" }
},
    gen3: {
    252: {name: "Treecko", type: "Grass", image:"images/RSE Dex/treecko.png" },
    253: {name: "Grovyle", type: "Grass", image:"images/RSE Dex/grovyle.png" },
    254: {name: "Sceptile",type: "Grass",image:"images/RSE Dex/sceptile.png"},
    255: {name: "Torchic",type: "Fire",image:"images/RSE Dex/torchic.png"},
    256: {name: "Combusken",type: "Fire · Fighting",image:"images/RSE Dex/combusken.png"},
    257: {name: "Blaziken",type: "Fire · Fighting",image:"images/RSE Dex/blaziken.png"},
    258: {name: "Mudkip",type: "Water", image:"images/RSE Dex/mudkip.png"},
    259: {name: "Marshtomp",type: "Water · Ground",image:"images/RSE Dex/marshtomp.png"},
    260: {name: "Swampert",type: "Water · Ground",image:"images/RSE Dex/swampert.png"},
    261: {name: "Poochyena",type: "Dark",image:"images/RSE Dex/poochyena.png"},
    262: {name: "Mightyena",type: "Dark",image:"images/RSE Dex/mightyena.png"},
    263: {name: "Zigzagoon", type: "Normal", image:"images/RSE Dex/zigzagoon.png" },
    264: {name: "Linoone", type: "Normal", image:"images/RSE Dex/linoone.png" },
    265: {name: "Wurmple", type: "Bug", image:"images/RSE Dex/wurmple.png" },
    266: {name: "Silcoon", type: "Bug", image:"images/RSE Dex/silcoon.png" },
    267: {name: "Beautifly", type: "Bug · Flying", image:"images/RSE Dex/beautifly.png" },
    268: {name: "Cascoon", type: "Bug", image:"images/RSE Dex/cascoon.png" },
    269: {name: "Dustox", type: "Bug · Poison", image:"images/RSE Dex/dustox.png" },
    270: {name: "Lotad", type: "Water · Grass", image:"images/RSE Dex/lotad.png" },
    271: {name: "Lombre", type: "Water · Grass", image:"images/RSE Dex/lombre.png" },
    272: {name: "Ludicolo", type: "Water · Grass", image:"images/RSE Dex/ludicolo.png" },
    273: {name: "Seedot", type: "Grass", image:"images/RSE Dex/seedot.png" },
    274: {name: "Nuzleaf", type: "Grass · Dark", image:"images/RSE Dex/nuzleaf.png" },
    275: {name: "Shiftry", type: "Grass · Dark", image:"images/RSE Dex/shiftry.png" },
    276: {name: "Taillow", type: "Normal · Flying", image:"images/RSE Dex/taillow.png" },
    277: {name: "Swellow", type: "Normal · Flying", image:"images/RSE Dex/swellow.png" },
    278: {name: "Wingull", type: "Water · Flying", image:"images/RSE Dex/wingull.png" },
    279: {name: "Pelipper", type: "Water · Flying", image:"images/RSE Dex/pelipper.png" },
    280: {name: "Ralts", type: "Psychic · Fairy", image:"images/RSE Dex/ralts.png" },
    281: {name: "Kirlia", type: "Psychic · Fairy", image:"images/RSE Dex/kirlia.png" },
    282: {name: "Gardevoir", type: "Psychic · Fairy", image:"images/RSE Dex/gardevoir.png" },
    283: {name: "Surskit", type: "Bug · Water", image:"images/RSE Dex/surskit.png" },
    284: {name: "Masquerain", type: "Bug · Flying", image:"images/RSE Dex/masquerain.png" },
    285: {name: "Shroomish", type: "Grass", image:"images/RSE Dex/shroomish.png" },
    286: {name: "Breloom", type: "Grass · Fighting", image:"images/RSE Dex/breloom.png" },
    287: {name: "Slakoth", type: "Normal", image:"images/RSE Dex/slakoth.png" },
    288: {name: "Vigoroth", type: "Normal", image:"images/RSE Dex/vigoroth.png" },
    289: {name: "Slaking", type: "Normal", image:"images/RSE Dex/slaking.png" },
    290: {name: "Nincada", type: "Bug · Ground", image:"images/RSE Dex/nincada.png" },
    291: {name: "Ninjask", type: "Bug · Flying", image:"images/RSE Dex/ninjask.png" },
    292: {name: "Shedinja", type: "Bug · Ghost", image:"images/RSE Dex/shedinja.png" },
    293: {name: "Whismur", type: "Normal", image:"images/RSE Dex/whismur.png" },
    294: {name: "Loudred", type: "Normal", image:"images/RSE Dex/loudred.png" },
    295: {name: "Exploud", type: "Normal", image:"images/RSE Dex/exploud.png" },
    296: {name: "Makuhita", type: "Fighting", image:"images/RSE Dex/makuhita.png" },
    297: {name: "Hariyama", type: "Fighting", image:"images/RSE Dex/hariyama.png" },
    298: {name: "Azurill", type: "Normal · Fairy", image:"images/RSE Dex/azurill.png" },
    299: {name: "Nosepass", type: "Rock", image:"images/RSE Dex/nosepass.png" },
    300: {name: "Skitty", type: "Normal", image:"images/RSE Dex/skitty.png" },
    301: {name: "Delcatty", type: "Normal", image:"images/RSE Dex/delcatty.png" },
    302: {name: "Sableye", type: "Dark · Ghost", image:"images/RSE Dex/sableye.png" },
    303: {name: "Mawile",type: "Steel · Fairy",image:"images/RSE Dex/mawile.png"},
    304: {name: "Aron",type: "Steel · Rock",image:"images/RSE Dex/aron.png"},
    305: {name: "Lairon",type: "Steel · Rock", image:"images/RSE Dex/lairon.png"},
    306: {name: "Aggron",type: "Steel · Rock",image:"images/RSE Dex/aggron.png"},
    307: {name: "Meditite",type: "Fighting · Psychic",image:"images/RSE Dex/meditite.png"},
    308: {name: "Medicham",type: "Fighting · Psychic",image:"images/RSE Dex/medicham.png"},
    309: {name: "Electrike",type: "Electric",image:"images/RSE Dex/electrike.png"},
    310: {name: "Manectric",type: "Electric",image:"images/RSE Dex/manectric.png"},
    311: {name: "Plusle",type: "Electric",image:"images/RSE Dex/plusle.png"},
    312: {name: "Minun",type: "Electric",image:"images/RSE Dex/minun.png"},
    313: {name: "Volbeat",type: "Bug",image:"images/RSE Dex/volbeat.png"},
    314: {name: "Illumise",type: "Bug",image:"images/RSE Dex/illumise.png"},
    315: {name: "Roselia",type: "Grass · Poison",image:"images/RSE Dex/roselia.png"},
    316: {name: "Gulpin",type: "Poison",image:"images/RSE Dex/gulpin.png"},
    317: {name: "Swalot",type: "Poison",image:"images/RSE Dex/swalot.png"},
    318: {name: "Carvanha",type: "Water · Dark",image:"images/RSE Dex/carvanha.png"},
    319: {name: "Sharpedo",type: "Water · Dark",image:"images/RSE Dex/sharpedo.png"},
    320: {name: "Wailmer",type: "Water",image:"images/RSE Dex/wailmer.png"},
    321: {name: "Wailord",type: "Water",image:"images/RSE Dex/wailord.png"},
    322: {name: "Numel",type: "Fire · Ground",image:"images/RSE Dex/numel.png"},
    323: {name: "Camerupt",type: "Fire · Ground",image:"images/RSE Dex/camerupt.png"},
    324: {name: "Torkoal",type: "Fire",image:"images/RSE Dex/torkoal.png"},
    325: {name: "Spoink",type: "Psychic",image:"images/RSE Dex/spoink.png"},
    326: {name: "Grumpig",type: "Psychic",image:"images/RSE Dex/grumpig.png"},
    327: {name: "Spinda",type: "Normal",image:"images/RSE Dex/spinda.png"},
    328: {name: "Trapinch",type: "Ground",image:"images/RSE Dex/trapinch.png"},
    329: {name: "Vibrava",type: "Ground · Dragon",image:"images/RSE Dex/vibrava.png"},
    330: {name: "Flygon",type: "Ground · Dragon",image:"images/RSE Dex/flygon.png"},
    331: {name: "Cacnea",type: "Grass",image:"images/RSE Dex/cacnea.png"},
    332: {name: "Cacturne",type: "Grass · Dark",image:"images/RSE Dex/cacturne.png"},
    333: {name: "Swablu",type: "Normal · Flying",image:"images/RSE Dex/swablu.png"},
    334: {name: "Altaria",type: "Dragon · Flying",image:"images/RSE Dex/altaria.png"},
    335: {name: "Zangoose",type: "Normal",image:"images/RSE Dex/zangoose.png"},
    336: {name: "Seviper",type: "Poison",image:"images/RSE Dex/seviper.png"},
    337: {name: "Lunatone",type: "Rock · Psychic",image:"images/RSE Dex/lunatone.png"},
    338: {name: "Solrock",type: "Rock · Psychic",image:"images/RSE Dex/solrock.png"},
    339: {name: "Barboach",type: "Water · Ground",image:"images/RSE Dex/barboach.png"},
    340: {name: "Whiscash",type: "Water · Ground",image:"images/RSE Dex/whiscash.png"},
    341: {name: "Corphish", type: "Water", image:"images/RSE Dex/corphish.png" },
    342: {name: "Crawdaunt",type: "Water · Dark",image:"images/RSE Dex/crawdaunt.png"},
    343: {name: "Baltoy",type: "Ground · Psychic",image:"images/RSE Dex/baltoy.png"},
    344: {name: "Claydol",type: "Ground · Psychic",image:"images/RSE Dex/claydol.png"},
    345: {name: "Lileep",type: "Rock · Grass",image:"images/RSE Dex/lileep.png"},
    346: {name: "Cradily",type: "Rock · Grass",image:"images/RSE Dex/cradily.png"},
    347: {name: "Anorith",type: "Rock · Bug",image:"images/RSE Dex/anorith.png"},
    348: {name: "Armaldo",type: "Rock · Bug",image:"images/RSE Dex/armaldo.png"},
    349: {name: "Feebas",type: "Water",image:"images/RSE Dex/feebas.png"},
    350: {name: "Milotic",type: "Water",image:"images/RSE Dex/milotic.png"},
    351: {name: "Castform",type: "Normal",image:"images/RSE Dex/castform.png"},
    352: {name: "Kecleon",type: "Normal",image:"images/RSE Dex/kecleon.png"},
    353: {name: "Shuppet",type: "Ghost",image:"images/RSE Dex/shuppet.png"},
    354: {name: "Banette",type: "Ghost",image:"images/RSE Dex/banette.png"},
    355: {name: "Duskull",type: "Ghost",image:"images/RSE Dex/duskull.png"},
    356: {name: "Dusclops",type: "Ghost",image:"images/RSE Dex/dusclops.png"},
    357: {name: "Tropius",type: "Grass · Flying",image:"images/RSE Dex/tropius.png"},
    358: {name: "Chimecho", type: "Psychic", image:"images/RSE Dex/chimecho.png" },
    359: {name: "Absol",type: "Dark",image:"images/RSE Dex/absol.png"},
    360: {name: "Wynaut",type: "Psychic",image:"images/RSE Dex/wynaut.png"},
    361: {name: "Snorunt",type: "Ice",image:"images/RSE Dex/snorunt.png"},
    362: {name: "Glalie",type: "Ice",image:"images/RSE Dex/glalie.png"},
    363: {name: "Spheal",type: "Ice · Water",image:"images/RSE Dex/spheal.png"},
    364: {name: "Sealeo",type: "Ice · Water",image:"images/RSE Dex/sealeo.png"},
    365: {name: "Walrein",type: "Ice · Water",image:"images/RSE Dex/walrein.png"},
    366: {name: "Clamperl",type: "Water",image:"images/RSE Dex/clamperl.png"},
    367: {name: "Huntail",type: "Water",image:"images/RSE Dex/huntail.png"},
    368: {name: "Gorebyss",type: "Water",image:"images/RSE Dex/gorebyss.png"},
    369: {name: "Relicanth",type: "Water · Rock",image:"images/RSE Dex/relicanth.png"},
    370: {name: "Luvdisc",type: "Water",image:"images/RSE Dex/luvdisc.png"},
    371: {name: "Bagon",type: "Dragon",image:"images/RSE Dex/bagon.png"},
    372: {name: "Shelgon",type: "Dragon",image:"images/RSE Dex/shelgon.png"},
    373: {name: "Salamence",type: "Dragon · Flying",image:"images/RSE Dex/salamence.png"},
    374: {name: "Beldum",type: "Steel · Psychic",image:"images/RSE Dex/beldum.png"},
    375: {name: "Metang",type: "Steel · Psychic",image:"images/RSE Dex/metang.png"},
    376: {name: "Metagross",type: "Steel · Psychic",image:"images/RSE Dex/metagross.png"},
    377: {name: "Regirock",type: "Rock",image:"images/RSE Dex/regirock.png"},
    378: {name: "Regice",type: "Ice",image:"images/RSE Dex/regice.png"},
    379: {name: "Registeel",type: "Steel",image:"images/RSE Dex/registeel.png"},
    380: {name: "Latias",type: "Dragon · Psychic",image:"images/RSE Dex/latias.png"},
    381: {name: "Latios",type: "Dragon · Psychic",image:"images/RSE Dex/latios.png"},
    382: {name: "Kyogre",type: "Water",image:"images/RSE Dex/kyogre.png"},
    383: {name: "Groudon",type: "Ground",image:"images/RSE Dex/groudon.png"},
    384: {name: "Rayquaza",type: "Dragon · Flying",image:"images/RSE Dex/rayquaza.png"},
    385: {name: "Jirachi",type: "Steel · Psychic",image:"images/RSE Dex/jirachi.png"},
    386: {name: "Deoxys",type: "Psychic",image:"images/RSE Dex/deoxys.png"}
    },
    gen4:{
    387: { name: "Turtwig", type: "Grass", image:"images/DP Dex/turtwig.png" },
    388: { name: "Grotle", type: "Grass", image:"images/DP Dex/grotle.png" },
    389: { name: "Torterra", type: "Grass · Ground", image:"images/DP Dex/torterra.png" },
    390: { name: "Chimchar", type: "Fire", image:"images/DP Dex/chimchar.png" },
    391: { name: "Monferno", type: "Fire · Fighting", image:"images/DP Dex/monferno.png" },
    392: { name: "Infernape", type: "Fire · Fighting", image:"images/DP Dex/infernape.png" },
    393: { name: "Piplup", type: "Water", image:"images/DP Dex/piplup.png" },
    394: { name: "Prinplup", type: "Water", image:"images/DP Dex/prinplup.png" },
    395: { name: "Empoleon", type: "Water · Steel", image:"images/DP Dex/empoleon.png" },
    396: { name: "Starly", type: "Normal · Flying", image:"images/DP Dex/starly.png" },
    397: { name: "Staravia", type: "Normal · Flying", image:"images/DP Dex/staravia.png" },
    398: { name: "Staraptor", type: "Normal · Flying", image:"images/DP Dex/staraptor.png" },
    399: { name: "Bidoof", type: "Normal", image:"images/DP Dex/bidoof.png" },
    400: { name: "Bibarel", type: "Normal · Water", image:"images/DP Dex/bibarel.png" },
    401: { name: "Kricketot", type: "Bug", image:"images/DP Dex/kricketot.png" },
    402: { name: "Kricketune", type: "Bug", image:"images/DP Dex/kricketune.png" },
    403: { name: "Shinx", type: "Electric", image:"images/DP Dex/shinx.png" },
    404: { name: "Luxio", type: "Electric", image:"images/DP Dex/luxio.png" },
    405: { name: "Luxray", type: "Electric", image:"images/DP Dex/luxray.png" },
    406: { name: "Budew", type: "Grass · Poison", image:"images/DP Dex/budew.png" },
    407: { name: "Roserade", type: "Grass · Poison", image:"images/DP Dex/roserade.png" },
    408: { name: "Cranidos", type: "Rock", image:"images/DP Dex/cranidos.png" },
    409: { name: "Rampardos", type: "Rock", image:"images/DP Dex/rampardos.png" },
    410: { name: "Shieldon", type: "Rock · Steel", image:"images/DP Dex/shieldon.png" },
    411: { name: "Bastiodon", type: "Rock · Steel", image:"images/DP Dex/bastiodon.png" },
    412: { name: "Burmy", type: "Bug", image:"images/DP Dex/burmy.png" },
    413: { name: "Wormadam", type: "Bug · Grass", image:"images/DP Dex/wormadam.png" },
    414: { name: "Mothim", type: "Bug · Flying", image:"images/DP Dex/mothim.png" },
    415: { name: "Combee", type: "Bug · Flying", image:"images/DP Dex/combee.png" },
    416: { name: "Vespiquen", type: "Bug · Flying", image:"images/DP Dex/vespiquen.png" },
    417: { name: "Pachirisu", type: "Electric", image:"images/DP Dex/pachirisu.png" },
    418: { name: "Buizel", type: "Water", image:"images/DP Dex/buizel.png" },
    419: { name: "Floatzel", type: "Water", image:"images/DP Dex/floatzel.png" },
    420: { name: "Cherubi", type: "Grass", image:"images/DP Dex/cherubi.png" },
    421: { name: "Cherrim", type: "Grass", image:"images/DP Dex/cherrim.png" },
    422: { name: "Shellos", type: "Water", image:"images/DP Dex/shellos.png" },
    423: { name: "Gastrodon", type: "Water · Ground", image:"images/DP Dex/gastrodon.png" },
    424: { name: "Ambipom", type: "Normal", image:"images/DP Dex/ambipom.png" },
    425: { name: "Drifloon", type: "Ghost · Flying", image:"images/DP Dex/drifloon.png" },
    426: { name: "Drifblim", type: "Ghost · Flying", image:"images/DP Dex/drifblim.png" },
    427: { name: "Buneary", type: "Normal", image:"images/DP Dex/buneary.png" },
    428: { name: "Lopunny", type: "Normal", image:"images/DP Dex/lopunny.png" },
    429: { name: "Mismagius", type: "Ghost", image:"images/DP Dex/mismagius.png" },
    430: { name: "Honchkrow", type: "Dark · Flying", image:"images/DP Dex/honchkrow.png" },
    431: { name: "Glameow", type: "Normal", image:"images/DP Dex/glameow.png" },
    432: { name: "Purugly", type: "Normal", image:"images/DP Dex/purugly.png" },
    433: { name: "Chingling", type: "Psychic", image:"images/DP Dex/chingling.png" },
    434: { name: "Stunky", type: "Poison · Dark", image:"images/DP Dex/stunky.png" },
    435: { name: "Skuntank", type: "Poison · Dark", image:"images/DP Dex/skuntank.png" },
    436: { name: "Bronzor", type: "Steel · Psychic", image:"images/DP Dex/bronzor.png" },
    437: { name: "Bronzong", type: "Steel · Psychic", image:"images/DP Dex/bronzong.png" },
    438: { name: "Bonsly", type: "Rock", image:"images/DP Dex/bonsly.png" },
    439: { name: "Mime Jr.", type: "Psychic · Fairy", image:"images/DP Dex/mime jr.png" },
    440: { name: "Happiny", type: "Normal", image:"images/DP Dex/happiny.png" },
    441: { name: "Chatot", type: "Normal · Flying", image:"images/DP Dex/chatot.png" },
    442: { name: "Spiritomb", type: "Ghost · Dark", image:"images/DP Dex/spiritomb.png" },
    443: { name: "Gible", type: "Dragon · Ground", image:"images/DP Dex/gible.png" },
    444: { name: "Gabite", type: "Dragon · Ground", image:"images/DP Dex/gabite.png" },
    445: { name: "Garchomp", type: "Dragon · Ground", image:"images/DP Dex/garchomp.png" },
    446: { name: "Munchlax", type: "Normal", image:"images/DP Dex/munchlax.png" },
    447: { name: "Riolu", type: "Fighting", image:"images/DP Dex/riolu.png" },
    448: { name: "Lucario", type: "Fighting · Steel", image:"images/DP Dex/lucario.png" },
    449: { name: "Hippopotas", type: "Ground", image:"images/DP Dex/hippopotas.png" },
    450: { name: "Hippowdon", type: "Ground", image:"images/DP Dex/hippowdon.png" },
    451: { name: "Skorupi", type: "Poison · Bug", image:"images/DP Dex/skorupi.png" },
    452: { name: "Drapion", type: "Poison · Dark", image:"images/DP Dex/drapion.png" },
    453: { name: "Croagunk", type: "Poison · Fighting", image:"images/DP Dex/croagunk.png" },
    454: { name: "Toxicroak", type: "Poison · Fighting", image:"images/DP Dex/toxicroak.png" },
    455: { name: "Carnivine", type: "Grass", image:"images/DP Dex/carnivine.png" },
    456: { name: "Finneon", type: "Water", image:"images/DP Dex/finneon.png" },
    457: { name: "Lumineon", type: "Water", image:"images/DP Dex/lumineon.png" },
    458: { name: "Mantyke", type: "Water · Flying", image:"images/DP Dex/mantyke.png" },
    459: { name: "Snover", type: "Grass · Ice", image:"images/DP Dex/snover.png" },
    460: { name: "Abomasnow", type: "Grass · Ice", image:"images/DP Dex/abomasnow.png" },
    461: { name: "Weavile", type: "Dark · Ice", image:"images/DP Dex/weavile.png" },
    462: { name: "Magnezone", type: "Electric · Steel", image:"images/DP Dex/magnezone.png" },
    463: { name: "Lickilicky", type: "Normal", image:"images/DP Dex/lickilicky.png" },
    464: { name: "Rhyperior", type: "Ground · Rock", image:"images/DP Dex/rhyperior.png" },
    465: { name: "Tangrowth", type: "Grass", image:"images/DP Dex/tangrowth.png" },
    466: { name: "Electivire", type: "Electric", image:"images/DP Dex/electivire.png" },
    467: { name: "Magmortar", type: "Fire", image:"images/DP Dex/magmortar.png" },
    468: { name: "Togekiss", type: "Fairy · Flying", image:"images/DP Dex/togekiss.png" },
    469: { name: "Yanmega", type: "Bug · Flying", image:"images/DP Dex/yanmega.png" },
    470: { name: "Leafeon", type: "Grass", image:"images/DP Dex/leafeon.png" },
    471: { name: "Glaceon", type: "Ice", image:"images/DP Dex/glaceon.png" },
    472: { name: "Gliscor", type: "Ground · Flying", image:"images/DP Dex/gliscor.png" },
    473: { name: "Mamoswine", type: "Ice · Ground", image:"images/DP Dex/mamoswine.png" },
    474: { name: "Porygon-Z", type: "Normal", image:"images/DP Dex/porygon-z.png" },
    475: { name: "Gallade", type: "Psychic · Fighting", image:"images/DP Dex/gallade.png" },
    476: { name: "Probopass", type: "Rock · Steel", image:"images/DP Dex/probopass.png" },
    477: { name: "Dusknoir", type: "Ghost", image:"images/DP Dex/dusknoir.png" },
    478: { name: "Froslass", type: "Ice · Ghost", image:"images/DP Dex/froslass.png" },
    479: { name: "Rotom", type: "Electric · Ghost", image:"images/DP Dex/rotom.png" },
    480: { name: "Uxie", type: "Psychic", image:"images/DP Dex/uxie.png" },
    481: { name: "Mesprit", type: "Psychic", image:"images/DP Dex/mesprit.png" },
    482: { name: "Azelf", type: "Psychic", image:"images/DP Dex/azelf.png" },
    483: { name: "Dialga", type: "Steel · Dragon", image:"images/DP Dex/dialga.png" },
    484: { name: "Palkia", type: "Water · Dragon", image:"images/DP Dex/palkia.png" },
    485: { name: "Heatran", type: "Fire · Steel", image:"images/DP Dex/heatran.png" },
    486: { name: "Regigigas", type: "Normal", image:"images/DP Dex/regigigas.png" },
    487: { name: "Giratina", type: "Ghost · Dragon", image:"images/DP Dex/giratina.png" },
    488: { name: "Cresselia", type: "Psychic", image:"images/DP Dex/cresselia.png" },
    489: { name: "Phione", type: "Water", image:"images/DP Dex/phione.png" },
    490: { name: "Manaphy", type: "Water", image:"images/DP Dex/manaphy.png" },
    491: { name: "Darkrai", type: "Dark", image:"images/DP Dex/darkrai.png" },
    492: { name: "Shaymin", type: "Grass", image:"images/DP Dex/shaymin.png" },
    493: { name: "Arceus", type: "Normal", image:"images/DP Dex/arceus.png" }
    },
    
    gen5: {
    494: { name: "Victini", type: "Psychic/Fire", image:"images/B2W2/victini.png" },
    495: { name: "Snivy", type: "Grass", image:"images/B2W2/snivy.png" },
    496: { name: "Servine", type: "Grass", image:"images/B2W2/servine.png" },
    497: { name: "Serperior", type: "Grass", image:"images/B2W2/serperior.png" },
    498: { name: "Tepig", type: "Fire", image:"images/B2W2/tepig.png" },
    499: { name: "Pignite", type: "Fire/Fighting", image:"images/B2W2/pignite.png" },
    500: { name: "Emboar", type: "Fire/Fighting", image:"images/B2W2/emboar.png" },
    501: { name: "Oshawott", type: "Water", image:"images/B2W2/oshawott.png" },
    502: { name: "Dewott", type: "Water", image:"images/B2W2/dewott.png" },
    503: { name: "Samurott", type: "Water", image:"images/B2W2/samurott.png" },
    504: { name: "Patrat", type: "Normal", image:"images/B2W2/patrat.png" },
    505: { name: "Watchog", type: "Normal", image:"images/B2W2/watchog.png" },
    506: { name: "Lillipup", type: "Normal", image:"images/B2W2/lillipup.png" },
    507: { name: "Herdier", type: "Normal", image:"images/B2W2/herdier.png" },
    508: { name: "Stoutland", type: "Normal", image:"images/B2W2/stoutland.png" },
    509: { name: "Purrloin", type: "Dark", image:"images/B2W2/purrloin.png" },
    510: { name: "Liepard", type: "Dark", image:"images/B2W2/liepard.png" },
    511: { name: "Pansage", type: "Grass", image:"images/B2W2/pansage.png" },
    512: { name: "Simisage", type: "Grass", image:"images/B2W2/simisage.png" },
    513: { name: "Pansear", type: "Fire", image:"images/B2W2/pansear.png" },
    514: { name: "Simisear", type: "Fire", image:"images/B2W2/simisear.png" },
    515: { name: "Panpour", type: "Water", image:"images/B2W2/panpour.png" },
    516: { name: "Simipour", type: "Water", image:"images/B2W2/simipour.png" },
    517: { name: "Munna", type: "Psychic", image:"images/B2W2/munna.png" },
    518: { name: "Musharna", type: "Psychic", image:"images/B2W2/musharna.png" },
    519: { name: "Pidove", type: "Normal/Flying", image:"images/B2W2/pidove.png" },
    520: { name: "Tranquill", type: "Normal/Flying", image:"images/B2W2/tranquill.png" },
    521: { name: "Unfezant", type: "Normal/Flying", image:"images/B2W2/unfezant.png" },
    522: { name: "Blitzle", type: "Electric", image:"images/B2W2/blitzle.png" },
    523: { name: "Zebstrika", type: "Electric", image:"images/B2W2/zebstrika.png" },
    524: { name: "Roggenrola", type: "Rock", image:"images/B2W2/roggenrola.png" },
    525: { name: "Boldore", type: "Rock", image:"images/B2W2/boldore.png" },
    526: { name: "Gigalith", type: "Rock", image:"images/B2W2/gigalith.png" },
    527: { name: "Woobat", type: "Psychic/Flying", image:"images/B2W2/woobat.png" },
    528: { name: "Swoobat", type: "Psychic/Flying", image:"images/B2W2/swoobat.png" },
    529: { name: "Drilbur", type: "Ground", image:"images/B2W2/drilbur.png" },
    530: { name: "Excadrill", type: "Ground/Steel", image:"images/B2W2/excadrill.png" },
    531: { name: "Audino", type: "Normal", image:"images/B2W2/audino.png" },
    532: { name: "Timburr", type: "Fighting", image:"images/B2W2/timburr.png" },
    533: { name: "Gurdurr", type: "Fighting", image:"images/B2W2/gurdurr.png" },
    534: { name: "Conkeldurr", type: "Fighting", image:"images/B2W2/conkeldurr.png" },
    535: { name: "Tympole", type: "Water", image:"images/B2W2/tympole.png" },
    536: { name: "Palpitoad", type: "Water · Ground", image:"images/B2W2/palpitoad.png" },
    537: { name: "Seismitoad", type: "Water · Ground", image:"images/B2W2/seismitoad.png" },
    538: { name: "Throh", type: "Fighting", image:"images/B2W2/throh.png" },
    539: { name: "Sawk", type: "Fighting", image:"images/B2W2/sawk.png" },
    540: { name: "Sewaddle", type: "Bug · Grass", image:"images/B2W2/sewaddle.png" },
    541: { name: "Swadloon", type: "Bug · Grass", image:"images/B2W2/swadloon.png" },
    542: { name: "Leavanny", type: "Bug · Grass", image:"images/B2W2/leavanny.png" },
    543: { name: "Venipede", type: "Bug · Poison", image:"images/B2W2/venipede.png" },
    544: { name: "Whirlipede", type: "Bug · Poison", image:"images/B2W2/whirlipede.png" },
    545: { name: "Scolipede", type: "Bug · Poison", image:"images/B2W2/scolipede.png" },
    546: { name: "Cottonee", type: "Grass · Fairy", image:"images/B2W2/cottonee.png" },
    547: { name: "Whimsicott", type: "Grass · Fairy", image:"images/B2W2/whimsicott.png" },
    548: { name: "Petilil", type: "Grass", image:"images/B2W2/petilil.png" },
    549: { name: "Lilligant", type: "Grass", image:"images/B2W2/lilligant.png" },
    550: { name: "Basculin", type: "Water", image:"images/B2W2/basculin.png" },
    551: { name: "Sandile", type: "Ground · Dark", image:"images/B2W2/sandile.png" },
    552: { name: "Krokorok", type: "Ground · Dark", image:"images/B2W2/krokorok.png" },
    553: { name: "Krookodile", type: "Ground · Dark", image:"images/B2W2/krookodile.png" },
    554: { name: "Darumaka", type: "Fire", image:"images/B2W2/darumaka.png" },
    555: { name: "Darmanitan", type: "Fire", image:"images/B2W2/darmanitan.png" },
    556: { name: "Maractus", type: "Grass", image:"images/B2W2/maractus.png" },
    557: { name: "Dwebble", type: "Bug · Rock", image:"images/B2W2/dwebble.png" },
    558: { name: "Crustle", type: "Bug · Rock", image:"images/B2W2/crustle.png" },
    559: { name: "Scraggy", type: "Dark · Fighting", image:"images/B2W2/scraggy.png" },
    560: { name: "Scrafty", type: "Dark · Fighting", image:"images/B2W2/scrafty.png" },
    561: { name: "Sigilyph", type: "Psychic · Flying", image:"images/B2W2/sigilyph.png" },
    562: { name: "Yamask", type: "Ghost", image:"images/B2W2/yamask.png" },
    563: { name: "Cofagrigus", type: "Ghost", image:"images/B2W2/cofagrigus.png" },
    564: { name: "Tirtouga", type: "Water · Rock", image:"images/B2W2/tirtouga.png" },
    565: { name: "Carracosta", type: "Water · Rock", image:"images/B2W2/carracosta.png" },
    566: { name: "Archen", type: "Rock · Flying", image:"images/B2W2/archen.png" },
    567: { name: "Archeops", type: "Rock · Flying", image:"images/B2W2/archeops.png" },
    568: { name: "Trubbish", type: "Poison", image:"images/B2W2/trubbish.png" },
    569: { name: "Garbodor", type: "Poison", image:"images/B2W2/garbodor.png" },
    570: { name: "Zorua", type: "Dark", image:"images/B2W2/zorua.png" },
    571: { name: "Zoroark", type: "Dark", image:"images/B2W2/zoroark.png" },
    572: { name: "Minccino", type: "Normal", image:"images/B2W2/minccino.png" },
    573: { name: "Cinccino", type: "Normal", image:"images/B2W2/cinccino.png" },
    574: { name: "Gothita", type: "Psychic", image:"images/B2W2/gothita.png" },
    575: { name: "Gothorita", type: "Psychic", image:"images/B2W2/gothorita.png" },
    576: { name: "Gothitelle", type: "Psychic", image:"images/B2W2/gothitelle.png" },
    577: { name: "Solosis", type: "Psychic", image:"images/B2W2/solosis.png" },
    578: { name: "Duosion", type: "Psychic", image:"images/B2W2/duosion.png" },
    579: { name: "Reuniclus", type: "Psychic", image:"images/B2W2/reuniclus.png" },
    580: { name: "Ducklett", type: "Water · Flying", image:"images/B2W2/ducklett.png" },
    581: { name: "Swanna", type: "Water · Flying", image:"images/B2W2/swanna.png" },
    582: { name: "Vanillite", type: "Ice", image:"images/B2W2/vanillite.png" },
    583: { name: "Vanillish", type: "Ice", image:"images/B2W2/vanillish.png" },
    584: { name: "Vanilluxe", type: "Ice", image:"images/B2W2/vanilluxe.png" },
    585: { name: "Deerling", type: "Normal · Grass", image:"images/B2W2/deerling.png" },
    586: { name: "Sawsbuck", type: "Normal · Grass", image:"images/B2W2/sawsbuck.png" },
    587: { name: "Emolga", type: "Electric · Flying", image:"images/B2W2/emolga.png" },
    588: { name: "Karrablast", type: "Bug", image:"images/B2W2/karrablast.png" },
    589: { name: "Escavalier", type: "Bug · Steel", image:"images/B2W2/escavalier.png" },
    590: { name: "Foongus", type: "Grass · Poison", image:"images/B2W2/foongus.png" },
    591: { name: "Amoonguss", type: "Grass · Poison", image:"images/B2W2/amoonguss.png" },
    592: { name: "Frillish", type: "Water · Ghost", image:"images/B2W2/frillish.png" },
    593: { name: "Jellicent", type: "Water · Ghost", image:"images/B2W2/jellicent.png" },
    594: { name: "Alomomola", type: "Water", image:"images/B2W2/alomomola.png" },
    595: { name: "Joltik", type: "Bug · Electric", image:"images/B2W2/joltik.png" },
    596: { name: "Galvantula", type: "Bug · Electric", image:"images/B2W2/galvantula.png" },
    597: { name: "Ferroseed", type: "Grass · Steel", image:"images/B2W2/ferroseed.png" },
    598: { name: "Ferrothorn", type: "Grass · Steel", image:"images/B2W2/ferrothorn.png" },
    599: { name: "Klink", type: "Steel", image:"images/B2W2/klink.png" },
    600: { name: "Klang", type: "Steel", image:"images/B2W2/klang.png" },
    601: { name: "Klinklang", type: "Steel", image:"images/B2W2/klinklang.png" },
    602: { name: "Tynamo", type: "Electric", image:"images/B2W2/tynamo.png" },
    603: { name: "Eelektrik", type: "Electric", image:"images/B2W2/eelektrik.png" },
    604: { name: "Eelektross", type: "Electric", image:"images/B2W2/eelektross.png" },
    605: { name: "Elgyem", type: "Psychic", image:"images/B2W2/elgyem.png" },
    606: { name: "Beheeyem", type: "Psychic", image:"images/B2W2/beheeyem.png" },
    607: { name: "Litwick", type: "Ghost · Fire", image:"images/B2W2/litwick.png" },
    608: { name: "Lampent", type: "Ghost · Fire", image:"images/B2W2/lampent.png" },
    609: { name: "Chandelure", type: "Ghost · Fire", image:"images/B2W2/chandelure.png" },
    610: { name: "Axew", type: "Dragon", image:"images/B2W2/axew.png" },
    611: { name: "Fraxure", type: "Dragon", image:"images/B2W2/fraxure.png" },
    612: { name: "Haxorus", type: "Dragon", image:"images/B2W2/haxorus.png" },
    613: { name: "Cubchoo", type: "Ice", image:"images/B2W2/cubchoo.png" },
    614: { name: "Beartic", type: "Ice", image:"images/B2W2/beartic.png" },
    615: { name: "Cryogonal", type: "Ice", image:"images/B2W2/cryogonal.png" },
    616: { name: "Shelmet", type: "Bug", image:"images/B2W2/shelmet.png" },
    617: { name: "Accelgor", type: "Bug", image:"images/B2W2/accelgor.png" },
    618: { name: "Stunfisk", type: "Ground · Electric", image:"images/B2W2/stunfisk.png" },
    619: { name: "Mienfoo", type: "Fighting", image:"images/B2W2/mienfoo.png" },
    620: { name: "Mienshao", type: "Fighting", image:"images/B2W2/mienshao.png" },
    621: { name: "Druddigon", type: "Dragon", image:"images/B2W2/druddigon.png" },
    622: { name: "Golett", type: "Ground · Ghost", image:"images/B2W2/golett.png" },
    623: { name: "Golurk", type: "Ground · Ghost", image:"images/B2W2/golurk.png" },
    624: { name: "Pawniard", type: "Dark · Steel", image:"images/B2W2/pawniard.png" },
    625: { name: "Bisharp", type: "Dark · Steel", image:"images/B2W2/bisharp.png" },
    626: { name: "Bouffalant", type: "Normal", image:"images/B2W2/bouffalant.png" },
    627: { name: "Rufflet", type: "Normal · Flying", image:"images/B2W2/rufflet.png" },
    628: { name: "Braviary", type: "Normal · Flying", image:"images/B2W2/braviary.png" },
    629: { name: "Vullaby", type: "Dark · Flying", image:"images/B2W2/vullaby.png" },
    630: { name: "Mandibuzz", type: "Dark · Flying", image:"images/B2W2/mandibuzz.png" },
    631: { name: "Heatmor", type: "Fire", image:"images/B2W2/heatmor.png" },
    632: { name: "Durant", type: "Bug · Steel", image:"images/B2W2/durant.png" },
    633: { name: "Deino", type: "Dark · Dragon", image:"images/B2W2/deino.png" },
    634: { name: "Zweilous", type: "Dark · Dragon", image:"images/B2W2/zweilous.png" },
    635: { name: "Hydreigon", type: "Dark · Dragon", image:"images/B2W2/hydreigon.png" },
    636: { name: "Larvesta", type: "Bug · Fire", image:"images/B2W2/larvesta.png" },
    637: { name: "Volcarona", type: "Bug · Fire", image:"images/B2W2/volcarona.png" },
    638: { name: "Cobalion", type: "Steel · Fighting", image:"images/B2W2/cobalion.png" },
    639: { name: "Terrakion", type: "Rock · Fighting", image:"images/B2W2/terrakion.png" },
    640: { name: "Virizion", type: "Grass · Fighting", image:"images/B2W2/virizion.png" },
    641: { name: "Tornadus", type: "Flying", image:"images/B2W2/tornadus.png" },
    642: { name: "Thundurus", type: "Electric · Flying", image:"images/B2W2/thundurus.png" },
    643: { name: "Reshiram", type: "Dragon · Fire", image:"images/B2W2/reshiram.png" },
    644: { name: "Zekrom", type: "Dragon · Electric", image:"images/B2W2/zekrom.png" },
    645: { name: "Landorus", type: "Ground · Flying", image:"images/B2W2/landorus.png" },
    646: { name: "Kyurem", type: "Dragon · Ice", image:"images/B2W2/kyurem.png" },
    647: { name: "Keldeo", type: "Water · Fighting", image:"images/B2W2/keldeo.png" },
    648: { name: "Meloetta", type: "Normal · Psychic", image:"images/B2W2/meloetta.png" },
    649: { name: "Genesect", type: "Bug · Steel", image:"images/B2W2/genesect.png" }

    },

    gen6: {
    650: { name: "Chespin", type: "Grass", image:"images/gen 6/chespin.png" },
    651: { name: "Quilladin", type: "Grass", image:"images/gen 6/quilladin.png" },
    652: { name: "Chesnaught", type: "Grass · Fighting", image:"images/gen 6/chesnaught.png" },
    653: { name: "Fennekin", type: "Fire", image:"images/gen 6/fennekin.png" },
    654: { name: "Braixen", type: "Fire", image:"images/gen 6/braixen.png" },
    655: { name: "Delphox", type: "Fire · Psychic", image:"images/gen 6/delphox.png" },
    656: { name: "Froakie", type: "Water", image:"images/gen 6/froakie.png" },
    657: { name: "Frogadier", type: "Water", image:"images/gen 6/frogadier.png" },
    658: { name: "Greninja", type: "Water · Dark", image:"images/gen 6/greninja.png" },
    659: { name: "Bunnelby", type: "Normal", image:"images/gen 6/bunnelby.png" },
    660: { name: "Diggersby", type: "Normal · Ground", image:"images/gen 6/diggersby.png" },
    661: { name: "Fletchling", type: "Normal · Flying", image:"images/gen 6/fletchling.png" },
    662: { name: "Fletchinder", type: "Fire · Flying", image:"images/gen 6/fletchinder.png" },
    663: { name: "Talonflame", type: "Fire · Flying", image:"images/gen 6/talonflame.png" },
    664: { name: "Scatterbug", type: "Bug", image:"images/gen 6/scatterbug.png" },
    665: { name: "Spewpa", type: "Bug", image:"images/gen 6/spewpa.png" },
    666: { name: "Vivillon", type: "Bug · Flying", image:"images/gen 6/vivillon.png" },
    667: { name: "Litleo", type: "Fire · Normal", image:"images/gen 6/litleo.png" },
    668: { name: "Pyroar", type: "Fire · Normal", image:"images/gen 6/pyroar.png" },
    669: { name: "Flabébé", type: "Fairy", image:"images/gen 6/Flabébé.png" },
    670: { name: "Floette", type: "Fairy", image:"images/gen 6/floette.png" },
    671: { name: "Florges", type: "Fairy", image:"images/gen 6/florges.png" },
    672: { name: "Skiddo", type: "Grass", image:"images/gen 6/skiddo.png" },
    673: { name: "Gogoat", type: "Grass", image:"images/gen 6/gogoat.png" },
    674: { name: "Pancham", type: "Fighting", image:"images/gen 6/pancham.png" },
    675: { name: "Pangoro", type: "Fighting · Dark", image:"images/gen 6/pangoro.png" },
    676: { name: "Furfrou", type: "Normal", image:"images/gen 6/furfrou.png" },
    677: { name: "Espurr", type: "Psychic", image:"images/gen 6/espurr.png" },
    678: { name: "Meowstic", type: "Psychic", image:"images/gen 6/meowstic.png" },
    679: { name: "Honedge", type: "Steel · Ghost", image:"images/gen 6/honedge.png" },
    680: { name: "Doublade", type: "Steel · Ghost", image:"images/gen 6/doublade.png" },
    681: { name: "Aegislash", type: "Steel · Ghost", image:"images/gen 6/aegislash.png" },
    682: { name: "Spritzee", type: "Fairy", image:"images/gen 6/spritzee.png" },
    683: { name: "Aromatisse", type: "Fairy", image:"images/gen 6/aromatisse.png" },
    684: { name: "Swirlix", type: "Fairy", image:"images/gen 6/swirlix.png" },
    685: { name: "Slurpuff", type: "Fairy", image:"images/gen 6/slurpuff.png" },
    686: { name: "Inkay", type: "Dark · Psychic", image:"images/gen 6/inkay.png" },
    687: { name: "Malamar", type: "Dark · Psychic", image:"images/gen 6/malamar.png" },
    688: { name: "Binacle", type: "Rock · Water", image:"images/gen 6/binacle.png" },
    689: { name: "Barbaracle", type: "Rock · Water", image:"images/gen 6/barbaracle.png" },
    690: { name: "Skrelp", type: "Poison · Water", image:"images/gen 6/skrelp.png" },
    691: { name: "Dragalge", type: "Poison · Dragon", image:"images/gen 6/dragalge.png" },
    692: { name: "Clauncher", type: "Water", image:"images/gen 6/clauncher.png" },
    693: { name: "Clawitzer", type: "Water", image:"images/gen 6/clawitzer.png" },
    694: { name: "Helioptile", type: "Electric · Normal", image:"images/gen 6/helioptile.png" },
    695: { name: "Heliolisk", type: "Electric · Normal", image:"images/gen 6/heliolisk.png" },
    696: { name: "Tyrunt", type: "Rock · Dragon", image:"images/gen 6/tyrunt.png" },
    697: { name: "Tyrantrum", type: "Rock · Dragon", image:"images/gen 6/tyrantrum.png" },
    698: { name: "Amaura", type: "Rock · Ice", image:"images/gen 6/amaura.png" },
    699: { name: "Aurorus", type: "Rock · Ice", image:"images/gen 6/aurorus.png" },
    700: { name: "Sylveon", type: "Fairy", image:"images/gen 6/sylveon.png" },
    701: { name: "Hawlucha", type: "Fighting · Flying", image:"images/gen 6/hawlucha.png" },
    702: { name: "Dedenne", type: "Electric · Fairy", image:"images/gen 6/dedenne.png" },
    703: { name: "Carbink", type: "Rock · Fairy", image:"images/gen 6/carbink.png" },
    704: { name: "Goomy", type: "Dragon", image:"images/gen 6/goomy.png" },
    705: { name: "Sliggoo", type: "Dragon", image:"images/gen 6/sliggoo.png" },
    706: { name: "Goodra", type: "Dragon", image:"images/gen 6/goodra.png" },
    707: { name: "Klefki", type: "Steel · Fairy", image:"images/gen 6/klefki.png" },
    708: { name: "Phantump", type: "Ghost · Grass", image:"images/gen 6/phantump.png" },
    709: { name: "Trevenant", type: "Ghost · Grass", image:"images/gen 6/trevenant.png" },
    710: { name: "Pumpkaboo", type: "Ghost · Grass", image:"images/gen 6/pumpkaboo.png" },
    711: { name: "Gourgeist", type: "Ghost · Grass", image:"images/gen 6/gourgeist.png" },
    712: { name: "Bergmite", type: "Ice", image:"images/gen 6/bergmite.png" },
    713: { name: "Avalugg", type: "Ice", image:"images/gen 6/avalugg.png" },
    714: { name: "Noibat", type: "Flying · Dragon", image:"images/gen 6/noibat.png" },
    715: { name: "Noivern", type: "Flying · Dragon", image:"images/gen 6/noivern.png" },
    716: { name: "Xerneas", type: "Fairy", image:"images/gen 6/xerneas.png" },
    717: { name: "Yveltal", type: "Dark · Flying", image:"images/gen 6/yveltal.png" },
    718: { name: "Zygarde", type: "Dragon · Ground", image:"images/gen 6/zygarde.png" },
    719: { name: "Diancie", type: "Rock · Fairy", image:"images/gen 6/diancie.png" },
    720: { name: "Hoopa", type: "Psychic · Ghost", image:"images/gen 6/hoopa.png" },
    721: { name: "Volcanion", type: "Fire · Water", image:"images/gen 6/volcanion.png" }
    },
    
    gen7: {
    722: { name: "Rowlet", type: "Grass · Flying", image:"images/gen 7/rowlet.png" },
    723: { name: "Dartrix", type: "Grass · Flying", image:"images/gen 7/dartrix.png" },
    724: { name: "Decidueye", type: "Grass · Ghost", image:"images/gen 7/decidueye.png" },
    725: { name: "Litten", type: "Fire", image:"images/gen 7/litten.png" },
    726: { name: "Torracat", type: "Fire", image:"images/gen 7/torracat.png" },
    727: { name: "Incineroar", type: "Fire · Dark", image:"images/gen 7/incineroar.png" },
    728: { name: "Popplio", type: "Water", image:"images/gen 7/popplio.png" },
    729: { name: "Brionne", type: "Water", image:"images/gen 7/brionne.png" },
    730: { name: "Primarina", type: "Water · Fairy", image:"images/gen 7/primarina.png" },
    731: { name: "Pikipek", type: "Normal · Flying", image:"images/gen 7/pikipek.png" },
    732: { name: "Trumbeak", type: "Normal · Flying", image:"images/gen 7/trumbeak.png" },
    733: { name: "Toucannon", type: "Normal · Flying", image:"images/gen 7/toucannon.png" },
    734: { name: "Yungoos", type: "Normal", image:"images/gen 7/yungoos.png" },
    735: { name: "Gumshoos", type: "Normal", image:"images/gen 7/gumshoos.png" },
    736: { name: "Grubbin", type: "Bug", image:"images/gen 7/grubbin.png" },
    737: { name: "Charjabug", type: "Bug · Electric", image:"images/gen 7/charjabug.png" },
    738: { name: "Vikavolt", type: "Bug · Electric", image:"images/gen 7/vikavolt.png" },
    739: { name: "Crabrawler", type: "Fighting", image:"images/gen 7/crabrawler.png" },
    740: { name: "Crabominable", type: "Fighting · Ice", image:"images/gen 7/crabominable.png" },
    741: { name: "Oricorio", type: "Fire · Flying", image:"images/gen 7/oricorio.png" },
    742: { name: "Cutiefly", type: "Bug · Fairy", image:"images/gen 7/cutiefly.png" },
    743: { name: "Ribombee", type: "Bug · Fairy", image:"images/gen 7/ribombee.png" },
    744: { name: "Rockruff", type: "Rock", image:"images/gen 7/rockruff.png" },
    745: { name: "Lycanroc", type: "Rock", image:"images/gen 7/lycanroc.png" },
    746: { name: "Wishiwashi", type: "Water", image:"images/gen 7/wishiwashi.png" },
    747: { name: "Mareanie", type: "Poison · Water", image:"images/gen 7/mareanie.png" },
    748: { name: "Toxapex", type: "Poison · Water", image:"images/gen 7/toxapex.png" },
    749: { name: "Mudbray", type: "Ground", image:"images/gen 7/mudbray.png" },
    750: { name: "Mudsdale", type: "Ground", image:"images/gen 7/mudsdale.png" },
    751: { name: "Dewpider", type: "Water · Bug", image:"images/gen 7/dewpider.png" },
    752: { name: "Araquanid", type: "Water · Bug", image:"images/gen 7/araquanid.png" },
    753: { name: "Fomantis", type: "Grass", image:"images/gen 7/fomantis.png" },
    754: { name: "Lurantis", type: "Grass", image:"images/gen 7/lurantis.png" },
    755: { name: "Morelull", type: "Grass · Fairy", image:"images/gen 7/morelull.png" },
    756: { name: "Shiinotic", type: "Grass · Fairy", image:"images/gen 7/shiinotic.png" },
    757: { name: "Salandit", type: "Poison · Fire", image:"images/gen 7/salandit.png" },
    758: { name: "Salazzle", type: "Poison · Fire", image:"images/gen 7/salazzle.png" },
    759: { name: "Stufful", type: "Normal · Fighting", image:"images/gen 7/stufful.png" },
    760: { name: "Bewear", type: "Normal · Fighting", image:"images/gen 7/bewear.png" },
    761: { name: "Bounsweet", type: "Grass", image:"images/gen 7/bounsweet.png" },
    762: { name: "Steenee", type: "Grass", image:"images/gen 7/steenee.png" },
    763: { name: "Tsareena", type: "Grass", image:"images/gen 7/tsareena.png" },
    764: { name: "Comfey", type: "Fairy", image:"images/gen 7/comfey.png" },
    765: { name: "Oranguru", type: "Normal · Psychic", image:"images/gen 7/oranguru.png" },
    766: { name: "Passimian", type: "Fighting", image:"images/gen 7/passimian.png" },
    767: { name: "Wimpod", type: "Bug · Water", image:"images/gen 7/wimpod.png" },
    768: { name: "Golisopod", type: "Bug · Water", image:"images/gen 7/golisopod.png" },
    769: { name: "Sandygast", type: "Ghost · Ground", image:"images/gen 7/sandygast.png" },
    770: { name: "Palossand", type: "Ghost · Ground", image:"images/gen 7/palossand.png" },
    771: { name: "Pyukumuku", type: "Water", image:"images/gen 7/pyukumuku.png" },
    772: { name: "Type: Null", type: "Normal", image:"images/gen 7/typenull.png" },
    773: { name: "Silvally", type: "Normal", image:"images/gen 7/silvally.png" },
    774: { name: "Minior", type: "Rock · Flying", image:"images/gen 7/minior.png" },
    775: { name: "Komala", type: "Normal", image:"images/gen 7/komala.png" },
    776: { name: "Turtonator", type: "Fire · Dragon", image:"images/gen 7/turtonator.png" },
    777: { name: "Togedemaru", type: "Electric · Steel", image:"images/gen 7/togedemaru.png" },
    778: { name: "Mimikyu", type: "Ghost · Fairy", image:"images/gen 7/mimikyu.png" },
    779: { name: "Bruxish", type: "Water · Psychic", image:"images/gen 7/bruxish.png" },
    780: { name: "Drampa", type: "Normal · Dragon", image:"images/gen 7/drampa.png" },
    781: { name: "Dhelmise", type: "Ghost · Grass", image:"images/gen 7/dhelmise.png" },
    782: { name: "Jangmo-o", type: "Dragon", image:"images/gen 7/jangmo-o.png" },
    783: { name: "Hakamo-o", type: "Dragon · Fighting", image:"images/gen 7/hakamo-o.png" },
    784: { name: "Kommo-o", type: "Dragon · Fighting", image:"images/gen 7/kommo-o.png" },
    785: { name: "Tapu Koko", type: "Electric · Fairy", image:"images/gen 7/tapukoko.png" },
    786: { name: "Tapu Lele", type: "Psychic · Fairy", image:"images/gen 7/tapulele.png" },
    787: { name: "Tapu Bulu", type: "Grass · Fairy", image:"images/gen 7/tapubulu.png" },
    788: { name: "Tapu Fini", type: "Water · Fairy", image:"images/gen 7/tapufini.png" },
    789: { name: "Cosmog", type: "Psychic", image:"images/gen 7/cosmog.png" },
    790: { name: "Cosmoem", type: "Psychic", image:"images/gen 7/cosmoem.png" },
    791: { name: "Solgaleo", type: "Psychic · Steel", image:"images/gen 7/solgaleo.png" },
    792: { name: "Lunala", type: "Psychic · Ghost", image:"images/gen 7/lunala.png" },
    793: { name: "Nihilego", type: "Rock · Poison", image:"images/gen 7/nihilego.png" },
    794: { name: "Buzzwole", type: "Bug · Fighting", image:"images/gen 7/buzzwole.png" },
    795: { name: "Pheromosa", type: "Bug · Fighting", image:"images/gen 7/pheromosa.png" },
    796: { name: "Xurkitree", type: "Electric", image:"images/gen 7/xurkitree.png" },
    797: { name: "Celesteela", type: "Steel · Flying", image:"images/gen 7/celesteela.png" },
    798: { name: "Kartana", type: "Grass · Steel", image:"images/gen 7/kartana.png" },
    799: { name: "Guzzlord", type: "Dark · Dragon", image:"images/gen 7/guzzlord.png" },
    800: { name: "Necrozma", type: "Psychic", image:"images/gen 7/necrozma.png" },
    801: { name: "Magearna", type: "Steel · Fairy", image:"images/gen 7/magearna.png" },
    802: { name: "Marshadow", type: "Fighting · Ghost", image:"images/gen 7/marshadow.png" },
    803: { name: "Poipole", type: "Poison", image:"images/gen 7/poipole.png" },
    804: { name: "Naganadel", type: "Poison · Dragon", image:"images/gen 7/naganadel.png" },
    805: { name: "Stakataka", type: "Rock · Steel", image:"images/gen 7/stakataka.png" },
    806: { name: "Blacephalon", type: "Fire · Ghost", image:"images/gen 7/blacephalon.png" },
    807: { name: "Zeraora", type: "Electric", image:"images/gen 7/zeraora.png" },
    808: { name: "Meltan", type: "Steel", image:"images/gen 7/meltan.png" },
    809: { name: "Melmetal", type: "Steel", image:"images/gen 7/melmetal.png" }
},
    gen8: {
    810: { name: "Grookey", type: "Grass", image:"images/Normal/grookey.png" },
    811: { name: "Thwackey", type: "Grass", image:"images/Normal/thwackey.png" },
    812: { name: "Rillaboom", type: "Grass", image:"images/Normal/rillaboom.png" },
    813: { name: "Scorbunny", type: "Fire", image:"images/Normal/scorbunny.png" },
    814: { name: "Raboot", type: "Fire", image:"images/Normal/raboot.png" },
    815: { name: "Cinderace", type: "Fire", image:"images/Normal/cinderace.png" },
    816: { name: "Sobble", type: "Water", image:"images/Normal/sobble.png" },
    817: { name: "Drizzile", type: "Water", image:"images/Normal/drizzile.png" },
    818: { name: "Inteleon", type: "Water", image:"images/Normal/inteleon.png" },
    819: { name: "Skwovet", type: "Normal", image:"images/Normal/skwovet.png" },
    820: { name: "Greedent", type: "Normal", image:"images/Normal/greedent.png" },
    821: { name: "Rookidee", type: "Flying", image:"images/Normal/rookidee.png" },
    822: { name: "Corvisquire", type: "Flying", image:"images/Normal/corvisquire.png" },
    823: { name: "Corviknight", type: "Flying · Steel", image:"images/Normal/corviknight.png" },
    824: { name: "Blipbug", type: "Bug", image:"images/Normal/blipbug.png" },
    825: { name: "Dottler", type: "Bug · Psychic", image:"images/Normal/dottler.png" },
    826: { name: "Orbeetle", type: "Bug · Psychic", image:"images/Normal/orbeetle.png" },
    827: { name: "Nickit", type: "Dark", image:"images/Normal/nickit.png" },
    828: { name: "Thievul", type: "Dark", image:"images/Normal/thievul.png" },
    829: { name: "Gossifleur", type: "Grass", image:"images/Normal/gossifleur.png" },
    830: { name: "Eldegoss", type: "Grass", image:"images/Normal/eldegoss.png" },
    831: { name: "Wooloo", type: "Normal", image:"images/Normal/wooloo.png" },
    832: { name: "Dubwool", type: "Normal", image:"images/Normal/dubwool.png" },
    833: { name: "Chewtle", type: "Water", image:"images/Normal/chewtle.png" },
    834: { name: "Drednaw", type: "Water · Rock", image:"images/Normal/drednaw.png" },
    835: { name: "Yamper", type: "Electric", image:"images/Normal/yamper.png" },
    836: { name: "Boltund", type: "Electric", image:"images/Normal/boltund.png" },
    837: { name: "Rolycoly", type: "Rock", image:"images/Normal/rolycoly.png" },
    838: { name: "Carkol", type: "Rock · Fire", image:"images/Normal/carkol.png" },
    839: { name: "Coalossal", type: "Rock · Fire", image:"images/Normal/coalossal.png" },
    840: { name: "Applin", type: "Grass · Dragon", image:"images/Normal/applin.png" },
    841: { name: "Flapple", type: "Grass · Dragon", image:"images/Normal/flapple.png" },
    842: { name: "Appletun", type: "Grass · Dragon", image:"images/Normal/appletun.png" },
    843: { name: "Silicobra", type: "Ground", image:"images/Normal/silicobra.png" },
    844: { name: "Sandaconda", type: "Ground", image:"images/Normal/sandaconda.png" },
    845: { name: "Cramorant", type: "Flying · Water", image:"images/Normal/cramorant.png" },
    846: { name: "Arrokuda", type: "Water", image:"images/Normal/arrokuda.png" },
    847: { name: "Barraskewda", type: "Water", image:"images/Normal/barraskewda.png" },
    848: { name: "Toxel", type: "Electric · Poison", image:"images/Normal/toxel.png" },
    849: { name: "Toxtricity", type: "Electric · Poison", image:"images/Normal/toxtricity.png" },
    850: { name: "Sizzlipede", type: "Fire · Bug", image:"images/Normal/sizzlipede.png" },
    851: { name: "Centiskorch", type: "Fire · Bug", image:"images/Normal/centiskorch.png" },
    852: { name: "Clobbopus", type: "Fighting", image:"images/Normal/clobbopus.png" },
    853: { name: "Grapploct", type: "Fighting", image:"images/Normal/grapploct.png" },
    854: { name: "Sinistea", type: "Ghost", image:"images/Normal/sinistea.png" },
    855: { name: "Polteageist", type: "Ghost", image:"images/Normal/polteageist.png" },
    856: { name: "Hatenna", type: "Psychic", image:"images/Normal/hatenna.png" },
    857: { name: "Hattrem", type: "Psychic", image:"images/Normal/hattrem.png" },
    858: { name: "Hatterene", type: "Psychic · Fairy", image:"images/Normal/hatterene.png" },
    859: { name: "Impidimp", type: "Dark · Fairy", image:"images/Normal/impidimp.png" },
    860: { name: "Morgrem", type: "Dark · Fairy", image:"images/Normal/morgrem.png" },
    861: { name: "Grimmsnarl", type: "Dark · Fairy", image:"images/Normal/grimmsnarl.png" },
    862: { name: "Obstagoon", type: "Dark · Normal", image:"images/Normal/obstagoon.png" },
    863: { name: "Perrserker", type: "Steel", image:"images/Normal/perrserker.png" },
    864: { name: "Cursola", type: "Ghost", image:"images/Normal/cursola.png" },
    865: { name: "Sirfetch'd", type: "Fighting", image:"images/Normal/sirfetch'd.png" },
    866: { name: "Mr. Rime", type: "Ice · Psychic", image:"images/Normal/mr. rime.png" },
    867: { name: "Runerigus", type: "Ground · Ghost", image:"images/Normal/runerigus.png" },
    868: { name: "Milcery", type: "Fairy", image:"images/Normal/milcery.png" },
    869: { name: "Alcremie", type: "Fairy", image:"images/Normal/alcremie.png" },
    870: { name: "Falinks", type: "Fighting", image:"images/Normal/falinks.png" },
    871: { name: "Pincurchin", type: "Electric", image:"images/Normal/pincurchin.png" },
    872: { name: "Snom", type: "Ice · Bug", image:"images/Normal/snom.png" },
    873: { name: "Frosmoth", type: "Ice · Bug", image:"images/Normal/frosmoth.png" },
    874: { name: "Stonjourner", type: "Rock", image:"images/Normal/stonjourner.png" },
    875: { name: "Eiscue", type: "Ice", image:"images/Normal/eiscue.png" },
    876: { name: "Indeedee", type: "Psychic · Normal", image:"images/Normal/indeedee.png" },
    877: { name: "Morpeko", type: "Electric · Dark", image:"images/Normal/morpeko.png" },
    878: { name: "Cufant", type: "Steel", image:"images/Normal/cufant.png" },
    879: { name: "Copperajah", type: "Steel", image:"images/Normal/copperajah.png" },
    880: { name: "Dracozolt", type: "Electric · Dragon", image:"images/Normal/dracozolt.png" },
    881: { name: "Arctozolt", type: "Electric · Ice", image:"images/Normal/arctozolt.png" },
    882: { name: "Dracovish", type: "Water · Dragon", image:"images/Normal/dracovish.png" },
    883: { name: "Arctovish", type: "Water · Ice", image:"images/Normal/arctovish.png" },
    884: { name: "Duraludon", type: "Steel · Dragon", image:"images/Normal/duraludon.png" },
    885: { name: "Dreepy", type: "Dragon · Ghost", image:"images/Normal/dreepy.png" },
    886: { name: "Drakloak", type: "Dragon · Ghost", image:"images/Normal/drakloak.png" },
    887: { name: "Dragapult", type: "Dragon · Ghost", image:"images/Normal/dragapult.png" },
    888: { name: "Zacian", type: "Fairy", image:"images/Normal/zacian.png" },
    889: { name: "Zamazenta", type: "Fighting", image:"images/Normal/zamazenta.png" },
    890: { name: "Eternatus", type: "Poison · Dragon", image:"images/Normal/eternatus.png" },
    891: { name: "Kubfu", type: "Fighting", image:"images/Normal/kubfu.png" },
    892: { name: "Urshifu", type: "Fighting · Dark", image:"images/Normal/urshifu.png" },
    893: { name: "Zarude", type: "Dark · Grass", image:"images/Normal/zarude.png" },
    894: { name: "Regieleki", type: "Electric", image:"images/Normal/regieleki.png" },
    895: { name: "Regidrago", type: "Dragon", image:"images/Normal/regidrago.png" },
    896: { name: "Glastrier", type: "Ice", image:"images/Normal/glastrier.png" },
    897: { name: "Spectrier", type: "Ghost", image:"images/Normal/spectrier.png" },
    898: { name: "Calyrex", type: "Psychic · Grass", image:"images/Normal/calyrex.png" },
    899: { name: "Wyrdeer", type: "Normal · Psychic", image:"images/Normal/wyrdeer.png" },
    900: { name: "Kleavor", type: "Bug · Rock", image:"images/Normal/kleavor.png" },
    901: { name: "Ursaluna", type: "Ground · Normal", image:"images/Normal/ursaluna.png" },
    902: { name: "Basculegion", type: "Water · Ghost", image:"images/Normal/basculegion.png" },
    903: { name: "Sneasler", type: "Fighting · Poison", image:"images/Normal/sneasler.png" },
    904: { name: "Overqwil", type: "Dark · Poison", image:"images/Normal/overqwil.png" },
    905: { name: "Enamorus", type: "Fairy · Flying", image:"images/Normal/enamorus.png" }
},

    gen9: {
    906: { name: "Sprigatito", type: "Grass", image:"images/Normal/sprigatito.png" },
    907: { name: "Floragato", type: "Grass", image:"images/Normal/floragato.png" },
    908: { name: "Meowscarada", type: "Grass · Dark", image:"images/Normal/meowscarada.png" },
    909: { name: "Fuecoco", type: "Fire", image:"images/Normal/fuecoco.png" },
    910: { name: "Crocalor", type: "Fire", image:"images/Normal/crocalor.png" },
    911: { name: "Skeledirge", type: "Fire · Ghost", image:"images/Normal/skeledirge.png" },
    912: { name: "Quaxly", type: "Water", image:"images/Normal/quaxly.png" },
    913: { name: "Quaxwell", type: "Water", image:"images/Normal/quaxwell.png" },
    914: { name: "Quaquaval", type: "Water · Fighting", image:"images/Normal/quaquaval.png" },
    915: { name: "Lechonk", type: "Normal", image:"images/Normal/lechonk.png" },
    916: { name: "Oinkologne", type: "Normal", image:"images/Normal/oinkologne.png" },
    917: { name: "Tarountula", type: "Bug", image:"images/Normal/tarountula.png" },
    918: { name: "Spidops", type: "Bug", image:"images/Normal/spidops.png" },
    919: { name: "Nymble", type: "Bug", image:"images/Normal/nymble.png" },
    920: { name: "Lokix", type: "Bug · Dark", image:"images/Normal/lokix.png" },
    921: { name: "Pawmi", type: "Electric", image:"images/Normal/pawmi.png" },
    922: { name: "Pawmo", type: "Electric · Fighting", image:"images/Normal/pawmo.png" },
    923: { name: "Pawmot", type: "Electric · Fighting", image:"images/Normal/pawmot.png" },
    924: { name: "Tandemaus", type: "Normal", image:"images/Normal/tandemaus.png" },
    925: { name: "Maushold", type: "Normal", image:"images/Normal/maushold.png" },
    926: { name: "Fidough", type: "Fairy", image:"images/Normal/fidough.png" },
    927: { name: "Dachsbun", type: "Fairy", image:"images/Normal/dachsbun.png" },
    928: { name: "Smoliv", type: "Grass · Normal", image:"images/Normal/smoliv.png" },
    929: { name: "Dolliv", type: "Grass · Normal", image:"images/Normal/dolliv.png" },
    930: { name: "Arboliva", type: "Grass · Normal", image:"images/Normal/arboliva.png" },
    931: { name: "Squawkabilly", type: "Normal · Flying", image:"images/Normal/squawkabilly.png" },
    932: { name: "Nacli", type: "Rock", image:"images/Normal/nacli.png" },
    933: { name: "Naclstack", type: "Rock", image:"images/Normal/naclstack.png" },
    934: { name: "Garganacl", type: "Rock", image:"images/Normal/garganacl.png" },
    935: { name: "Charcadet", type: "Fire", image:"images/Normal/charcadet.png" },
    936: { name: "Armarouge", type: "Fire · Psychic", image:"images/Normal/armarouge.png" },
    937: { name: "Ceruledge", type: "Fire · Ghost", image:"images/Normal/ceruledge.png" },
    938: { name: "Tadbulb", type: "Electric", image:"images/Normal/tadbulb.png" },
    939: { name: "Bellibolt", type: "Electric", image:"images/Normal/bellibolt.png" },
    940: { name: "Wattrel", type: "Electric · Flying", image:"images/Normal/wattrel.png" },
    941: { name: "Kilowattrel", type: "Electric · Flying", image:"images/Normal/kilowattrel.png" },
    942: { name: "Maschiff", type: "Dark", image:"images/Normal/maschiff.png" },
    943: { name: "Mabosstiff", type: "Dark", image:"images/Normal/mabosstiff.png" },
    944: { name: "Shroodle", type: "Poison · Normal", image:"images/Normal/shroodle.png" },
    945: { name: "Grafaiai", type: "Poison · Normal", image:"images/Normal/grafaiai.png" },
    946: { name: "Bramblin", type: "Grass · Ghost", image:"images/Normal/bramblin.png" },
    947: { name: "Brambleghast", type: "Grass · Ghost", image:"images/Normal/brambleghast.png" },
    948: { name: "Toedscool", type: "Ground · Grass", image:"images/Normal/toedscool.png" },
    949: { name: "Toedscruel", type: "Ground · Grass", image:"images/Normal/toedscruel.png" },
    950: { name: "Klawf", type: "Rock", image:"images/Normal/klawf.png" },
    951: { name: "Capsakid", type: "Grass", image:"images/Normal/capsakid.png" },
    952: { name: "Scovillain", type: "Grass · Fire", image:"images/Normal/scovillain.png" },
    953: { name: "Rellor", type: "Bug", image:"images/Normal/rellor.png" },
    954: { name: "Rabsca", type: "Bug · Psychic", image:"images/Normal/rabsca.png" },
    955: { name: "Flittle", type: "Psychic", image:"images/Normal/flittle.png" },
    956: { name: "Espathra", type: "Psychic", image:"images/Normal/espathra.png" },
    957: { name: "Tinkatink", type: "Fairy · Steel", image:"images/Normal/tinkatink.png" },
    958: { name: "Tinkatuff", type: "Fairy · Steel", image:"images/Normal/tinkatuff.png" },
    959: { name: "Tinkaton", type: "Fairy · Steel", image:"images/Normal/tinkaton.png" },
    960: { name: "Wiglett", type: "Water", image:"images/Normal/wiglett.png" },
    961: { name: "Wugtrio", type: "Water", image:"images/Normal/wugtrio.png" },
    962: { name: "Bombirdier", type: "Flying · Dark", image:"images/Normal/bombirdier.png" },
    963: { name: "Finizen", type: "Water", image:"images/Normal/finizen.png" },
    964: { name: "Palafin", type: "Water", image:"images/Normal/palafin.png" },
    965: { name: "Varoom", type: "Steel · Poison", image:"images/Normal/varoom.png" },
    966: { name: "Revavroom", type: "Steel · Poison", image:"images/Normal/revavroom.png" },
    967: { name: "Cyclizar", type: "Dragon · Normal", image:"images/Normal/cyclizar.png" },
    968: { name: "Orthworm", type: "Steel", image:"images/Normal/orthworm.png" },
    969: { name: "Glimmet", type: "Rock · Poison", image:"images/Normal/glimmet.png" },
    970: { name: "Glimmora", type: "Rock · Poison", image:"images/Normal/glimmora.png" },
    971: { name: "Greavard", type: "Ghost", image:"images/Normal/greavard.png" },
    972: { name: "Houndstone", type: "Ghost", image:"images/Normal/houndstone.png" },
    973: { name: "Flamigo", type: "Flying · Fighting", image:"images/Normal/flamigo.png" },
    974: { name: "Cetoddle", type: "Ice", image:"images/Normal/cetoddle.png" },
    975: { name: "Cetitan", type: "Ice", image:"images/Normal/cetitan.png" },
    976: { name: "Veluza", type: "Water · Psychic", image:"images/Normal/veluza.png" },
    977: { name: "Dondozo", type: "Water", image:"images/Normal/dondozo.png" },
    978: { name: "Tatsugiri", type: "Dragon · Water", image:"images/Normal/tatsugiri.png" },
    979: { name: "Annihilape", type: "Fighting · Ghost", image:"images/Normal/annihilape.png" },
    980: { name: "Clodsire", type: "Poison · Ground", image:"images/Normal/clodsire.png" },
    981: { name: "Farigiraf", type: "Normal · Psychic", image:"images/Normal/farigiraf.png" },
    982: { name: "Dudunsparce", type: "Normal", image:"images/Normal/dudunsparce.png" },
    983: { name: "Kingambit", type: "Dark · Steel", image:"images/Normal/kingambit.png" },
    984: { name: "Great Tusk", type: "Ground · Fighting", image:"images/Normal/great tusk.png" },
    985: { name: "Scream Tail", type: "Fairy · Psychic", image:"images/Normal/scream tail.png" },
    986: { name: "Brute Bonnet", type: "Grass · Dark", image:"images/Normal/brute bonnet.png" },
    987: { name: "Flutter Mane", type: "Ghost · Fairy", image:"images/Normal/flutter mane.png" },
    988: { name: "Slither Wing", type: "Bug · Fighting", image:"images/Normal/slither wing.png" },
    989: { name: "Sandy Shocks", type: "Electric · Ground", image:"images/Normal/sandy shocks.png" },
    990: { name: "Iron Treads", type: "Ground · Steel", image:"images/Normal/iron treads.png" },
    991: { name: "Iron Bundle", type: "Ice · Water", image:"images/Normal/iron bundle.png" },
    992: { name: "Iron Hands", type: "Fighting · Electric", image:"images/Normal/iron hands.png" },
    993: { name: "Iron Jugulis", type: "Dark · Flying", image:"images/Normal/iron jugulis.png" },
    994: { name: "Iron Moth", type: "Fire · Poison", image:"images/Normal/iron moth.png" },
    995: { name: "Iron Thorns", type: "Rock · Electric", image:"images/Normal/iron thorns.png" },
    996: { name: "Frigibax", type: "Dragon · Ice", image:"images/Normal/frigibax.png" },
    997: { name: "Arctibax", type: "Dragon · Ice", image:"images/Normal/arctibax.png" },
    998: { name: "Baxcalibur", type: "Dragon · Ice", image:"images/Normal/baxcalibur.png" },
    999: { name: "Gimmighoul", type: "Ghost", image:"images/Normal/gimmighoul.png" },
    1000: { name: "Gholdengo", type: "Steel · Ghost", image:"images/Normal/gholdengo.png" },
    1001: { name: "Wo-Chien", type: "Dark · Grass", image:"images/Normal/wo-chien.png" },
    1002: { name: "Chien-Pao", type: "Dark · Ice", image:"images/Normal/chien-pao.png" },
    1003: { name: "Ting-Lu", type: "Dark · Ground", image:"images/Normal/ting-lu.png" },
    1004: { name: "Chi-Yu", type: "Dark · Fire", image:"images/Normal/chi-yu.png" },
    1005: { name: "Roaring Moon", type: "Dragon · Dark", image:"images/Normal/roaring moon.png" },
    1006: { name: "Iron Valiant", type: "Fairy · Fighting", image:"images/Normal/iron valiant.png" },
    1007: { name: "Koraidon", type: "Dragon · Fighting", image:"images/Normal/koraidon.png" },
    1008: { name: "Miraidon", type: "Dragon · Electric", image:"images/Normal/miraidon.png" },
    1009: { name: "Walking Wake", type: "Dragon · Water", image:"images/Normal/walking_wake.png" },
    1010: { name: "Iron Leaves", type: "Grass · Psychic", image:"images/Normal/iron leaves.png" },
    1011: { name: "Dipplin", type: "Grass · Dragon", image:"images/Normal/dipplin.png" },
    1012: { name: "Poltchageist", type: "Grass · Ghost", image:"images/Normal/poltchageist.png" },
    1013: { name: "Sinistcha", type: "Grass · Ghost", image:"images/Normal/sinistcha.png" },
    1014: { name: "Okidogi", type: "Poison · Fighting", image:"images/Normal/okidogi.png" },
    1015: { name: "Munkidori", type: "Poison · Psychic", image:"images/Normal/munkidori.png" },
    1016: { name: "Fezandipiti", type: "Poison · Fairy", image:"images/Normal/fezandipiti.png" },
    1017: { name: "Ogerpon", type: "Grass", image:"images/Normal/ogerpon.png" },
    1018: { name: "Archaludon", type: "Steel · Dragon", image:"images/Normal/archalundon.png" },
    1019: { name: "Hydrapple", type: "Grass · Dragon", image:"images/Normal/hydrapple.png" },
    1020: { name: "Gouging Fire", type: "Fire · Dragon", image:"images/Normal/gouging fire.png" },
    1021: { name: "Raging Bolt", type: "Electric · Dragon", image:"images/Normal/raging bolt.png" },
    1022: { name: "Iron Boulder", type: "Rock · Psychic", image:"images/Normal/iron boulder.png" },
    1023: { name: "Iron Crown", type: "Steel · Psychic", image:"images/Normal/iron crown.png" },
    1024: { name: "Terapagos", type: "Normal", image:"images/Normal/terapagos.png" },
    1025: { name: "Pecharunt", type: "Poison · Ghost", image:"images/Normal/pecharunt.png" }
    },




    // Add other Generations here
};


const gameData = {
    gen1: [
        { id: 1, name: "PokéCheck", image:"PokéCheck.png",pokemon: generateRange(1, 151) },
    ],

    gen2: [
        { id: 1, name: "PokéCheck", image:"PokéCheck.png",pokemon: generateRange(152, 251) },
    ],

    gen3: [
        { id: 1, name: "PokéCheck", image:"PokéCheck.png",pokemon: generateRange(252, 386) },
    ],

    gen4: [
        { id: 1, name: "PokéCheck", image:"PokéCheck.png", pokemon: generateRange(387, 493) },
    ],

    gen5: [
        { id: 1, name: "PokéCheck", image:"PokéCheck.png",pokemon: generateRange(494, 649) },
    ],

    gen6: [
        { id: 1, name: "PokéCheck", image:"PokéCheck.png",pokemon: generateRange(650, 721) },
    ],

    gen7: [
        { id: 1, name: "PokéCheck", image:"PokéCheck.png",pokemon: generateRange(722, 809) },
    ],

    gen8: [
        { id: 1, name: "PokéCheck", image:"PokéCheck.png",pokemon: generateRange(810, 905) },
    ],

    gen9: [
        { id: 1, name: "PokéCheck", image:"PokéCheck.png",pokemon: generateRange(906, 1025) },
    ],
};


function selectGeneration(Generation) {
    document.getElementById('Generation-selection').classList.add('hidden');
    loadGames(Generation);
}

function loadGames(Generation) {
    const gamesGrid = document.getElementById("games");
    const games = gameData[Generation];

    if (!games) return;

    gamesGrid.innerHTML = ''; // Clear existing games
    document.getElementById('games-section').classList.remove('hidden'); // Show the games section

    // Move this inside the loadGames function
    games.forEach(game => {
        const gameBox = document.createElement("div");
        gameBox.className = "game-box";
        gameBox.innerHTML = `
            <div class="game-name">${game.name}</div>
            <img src="${game.image}" alt="${game.name}" class="game-image"/>
        `;
        gameBox.onclick = () => loadPokedexForGame(Generation, game.pokemon, game.id); // Pass gameId
        gamesGrid.appendChild(gameBox);
    });
}


// Update loadPokedexForGame to accept gameId parameter
function loadPokedexForGame(Generation, pokemonIds, gameId) {
    const pokemonGrid = document.getElementById("pokedex");
    pokemonGrid.innerHTML = '';
    document.getElementById('pokedex-section').classList.remove('hidden');

    pokemonIds.forEach(id => {
        const pokemon = pokedexData[Generation][id];
        const isCaught = localStorage.getItem(`${Generation}-${gameId}-${id}`) === 'true';

        const pokemonBox = document.createElement("div");
        pokemonBox.className = "pokemon-box";
        pokemonBox.innerHTML = `
            <div class="pokemon-number">#${id}</div>
            <div class="pokemon-name">${isCaught ? pokemon.name.charAt(0).toUpperCase() + pokemon.name.slice(1) : '???'}</div>
            <div class="pokemon-status">${isCaught ? 'Caught ✔️' : 'Not Caught ❌'}</div>
            ${isCaught ? `<div class="pokemon-type">Type: ${pokemon.type}</div>` : ''}
            <img src="${isCaught ? pokemon.image : 'Placeholder.png'}" alt="${isCaught ? pokemon.name : ''}">
        `;
        
        pokemonBox.onclick = () => toggleCaughtStatus(Generation, id, gameId);
        pokemonGrid.appendChild(pokemonBox);
    });
}

// Modify toggleCaughtStatus to use gameId
function toggleCaughtStatus(Generation, number, gameId) {
    const isCaught = localStorage.getItem(`${Generation}-${gameId}-${number}`) === 'true';
    localStorage.setItem(`${Generation}-${gameId}-${number}`, !isCaught);
    
    loadPokedexForGame(Generation, Object.keys(pokedexData[Generation]).map(Number), gameId); // Re-load with gameId
}


function goBack() {
    document.getElementById('pokedex-section').classList.add('hidden');
    document.getElementById('games-section').classList.add('hidden');
    document.getElementById('Generation-selection').classList.remove('hidden');
}




