function generateRange(start, end) {
    return Array.from({ length: (end - start + 1) }, (_, i) => i + start);
}


const pokedexData = {
    kanto: {
    1: { name: "bulbasaur", type: "Grass/Poison", image:"images/Normal/Bulbasaur.png" },
    2: { name: "ivysaur", type: "Grass/Poison", image:"images/Normal/Ivysaur.png" },
    3: { name: "venusaur", type: "Grass/Poison", image:"images/Normal/Venusaur.png" },
    4: { name: "charmander", type: "Fire", image:"images/Normal/Charmander.png" },
    5: { name: "charmeleon", type: "Fire", image:"images/Normal/Charmeleon.png" },
    6: { name: "charizard", type: "Fire/Flying", image:"images/Normal/Charizard.png" },
    7: { name: "squirtle", type: "Water", image:"images/Normal/Squirtle.png" },
    8: { name: "wartortle", type: "Water", image:"images/Normal/Wartortle.png" },
    9: { name: "blastoise", type: "Water", image:"images/Normal/Blastoise.png" },
    10: { name: "caterpie", type: "Bug", image:"images/Normal/Caterpie.png" },
    11: { name: "metapod", type: "Bug", image:"images/Normal/Metapod.png" },
    12: { name: "butterfree", type: "Bug/Flying", image:"images/Normal/Butterfree.png" },
    13: { name: "weedle", type: "Bug/Poison", image:"images/Normal/Weedle.png" },
    14: { name: "kakuna", type: "Bug/Poison", image:"images/Normal/Kakuna.png" },
    15: { name: "beedrill", type: "Bug/Poison", image:"images/Normal/Beedrill.png" },
    16: { name: "pidgey", type: "Normal/Flying", image:"images/Normal/Pidgey.png" },
    17: { name: "pidgeotto", type: "Normal/Flying", image:"images/Normal/Pidgeotto.png" },
    18: { name: "pidgeot", type: "Normal/Flying", image:"images/Normal/Pidgeot.png" },
    19: { name: "rattata", type: "Normal", image:"images/Normal/Rattata.png" },
    20: { name: "raticate", type: "Normal", image:"images/Normal/Raticate.png" },
    21: { name: "spearow", type: "Normal/Flying", image:"images/Normal/Spearow.png" },
    22: { name: "fearow", type: "Normal/Flying", image:"images/Normal/Fearow.png" },
    23: { name: "ekans", type: "Poison", image:"images/Normal/Ekans.png" },
    24: { name: "arbok", type: "Poison", image:"images/Normal/Arbok.png" },
    25: { name: "pikachu", type: "Electric", image:"images/Normal/Pikachu.png" },
    26: { name: "raichu", type: "Electric", image:"images/Normal/Raichu.png" },
    27: { name: "sandshrew", type: "Ground", image:"images/Normal/Sandshrew.png" },
    28: { name: "sandslash", type: "Ground", image:"images/Normal/Sandslash.png" },
    29: { name: "nidoran-♀", type: "Poison", image:"images/Normal/Nidoran-♀.png" },
    30: { name: "nidorina", type: "Poison", image:"images/Normal/Nidorina.png" },
    31: { name: "nidoqueen", type: "Poison/Ground", image:"images/Normal/Nidoqueen.png" },
    32: { name: "nidoran-♂", type: "Poison", image:"images/Normal/Nidoran-♂.png" },
    33: { name: "nidorino", type: "Poison", image:"images/Normal/Nidorino.png" },
    34: { name: "nidoking", type: "Poison/Ground", image:"images/Normal/Nidoking.png" },
    35: { name: "clefairy", type: "Fairy", image:"images/Normal/Clefairy.png" },
    36: { name: "clefable", type: "Fairy", image:"images/Normal/Clefable.png" },
    37: { name: "vulpix", type: "Fire", image:"images/Normal/Vulpix.png" },
    38: { name: "ninetales", type: "Fire", image:"images/Normal/Ninetales.png" },
    39: { name: "jigglypuff", type: "Normal/Fairy", image:"images/Normal/Jigglypuff.png" },
    40: { name: "wigglytuff", type: "Normal/Fairy", image:"images/Normal/Wigglytuff.png" },
    41: { name: "zubat", type: "Poison/Flying", image:"images/Normal/Zubat.png" },
    42: { name: "golbat", type: "Poison/Flying", image:"images/Normal/Golbat.png" },
    43: { name: "oddish", type: "Grass/Poison", image:"images/Normal/Oddish.png" },
    44: { name: "gloom", type: "Grass/Poison", image:"images/Normal/Gloom.png" },
    45: { name: "vileplume", type: "Grass/Poison", image:"images/Normal/Vileplume.png" },
    46: { name: "paras", type: "Bug/Grass", image:"images/Normal/Paras.png" },
    47: { name: "parasect", type: "Bug/Grass", image:"images/Normal/Parasect.png" },
    48: { name: "venonat", type: "Bug/Poison", image:"images/Normal/Venonat.png" },
    49: { name: "venomoth", type: "Bug/Poison", image:"images/Normal/Venomoth.png" },
    50: { name: "diglett", type: "Ground", image:"images/Normal/Diglett.png" },
    51: { name: "dugtrio", type: "Ground", image:"images/Normal/Dugtrio.png" },
    52: { name: "meowth", type: "Normal", image:"images/Normal/Meowth.png" },
    53: { name: "persian", type: "Normal", image:"images/Normal/Persian.png" },
    54: { name: "psyduck", type: "Water", image:"images/Normal/Psyduck.png" },
    55: { name: "golduck", type: "Water", image:"images/Normal/Golduck.png" },
    56: { name: "mankey", type: "Fighting", image:"images/Normal/Mankey.png" },
    57: { name: "primeape", type: "Fighting", image:"images/Normal/Primeape.png" },
    58: { name: "growlithe", type: "Fire", image:"images/Normal/Growlithe.png" },
    59: { name: "arcanine", type: "Fire", image:"images/Normal/Arcanine.png" },
    60: { name: "poliwag", type: "Water", image:"images/Normal/Poliwag.png" },
    61: { name: "poliwhirl", type: "Water", image:"images/Normal/Poliwhirl.png" },
    62: { name: "poliwrath", type: "Water/Fighting", image:"images/Normal/Poliwrath.png" },
    63: { name: "abra", type: "Psychic", image:"images/Normal/Abra.png" },
    64: { name: "kadabra", type: "Psychic", image:"images/Normal/Kadabra.png" },
    65: { name: "alakazam", type: "Psychic", image:"images/Normal/Alakazam.png" },
    66: { name: "machop", type: "Fighting", image:"images/Normal/Machop.png" },
    67: { name: "machoke", type: "Fighting", image:"images/Normal/Machoke.png" },
    68: { name: "machamp", type: "Fighting", image:"images/Normal/Machamp.png" },
    69: { name: "bellsprout", type: "Grass/Poison", image:"images/Normal/Bellsprout.png" },
    70: { name: "weepinbell", type: "Grass/Poison", image:"images/Normal/Weepinbell.png" },
    71: { name: "victreebel", type: "Grass/Poison", image:"images/Normal/Victreebel.png" },
    72: { name: "tentacool", type: "Water/Poison", image:"images/Normal/Tentacool.png" },
    73: { name: "tentacruel", type: "Water/Poison", image:"images/Normal/Tentacruel.png" },
    74: { name: "geodude", type: "Rock/Ground", image:"images/Normal/Geodude.png" },
    75: { name: "graveler", type: "Rock/Ground", image:"images/Normal/Graveler.png" },
    76: { name: "golem", type: "Rock/Ground", image:"images/Normal/Golem.png" },
    77: { name: "ponyta", type: "Fire", image:"images/Normal/Ponyta.png" },
    78: { name: "rapidash", type: "Fire", image:"images/Normal/Rapidash.png" },
    79: { name: "slowpoke", type: "Water/Psychic", image:"images/Normal/Slowpoke.png" },
    80: { name: "slowbro", type: "Water/Psychic", image:"images/Normal/Slowbro.png" },
    81: { name: "magnemite", type: "Electric/Steel", image:"images/Normal/Magnemite.png" },
    82: { name: "magneton", type: "Electric/Steel", image:"images/Normal/Magneton.png" },
    83: { name: "farfetch'd", type: "Normal/Flying", image:"images/Normal/Farfetchd.png" },
    84: { name: "doduo", type: "Normal/Flying", image:"images/Normal/Doduo.png" },
    85: { name: "dodrio", type: "Normal/Flying", image:"images/Normal/Dodrio.png" },
    86: { name: "seel", type: "Water", image:"images/Normal/Seel.png" },
    87: { name: "dewgong", type: "Water/Ice", image:"images/Normal/Dewgong.png" },
    88: { name: "grimer", type: "Poison", image:"images/Normal/Grimer.png" },
    89: { name: "muk", type: "Poison", image:"images/Normal/Muk.png" },
    90: { name: "shellder", type: "Water", image:"images/Normal/Shellder.png" },
    91: { name: "cloyster", type: "Water/Ice", image:"images/Normal/Cloyster.png" },
    92: { name: "gastly", type: "Ghost/Poison", image:"images/Normal/Gastly.png" },
    93: { name: "haunter", type: "Ghost/Poison", image:"images/Normal/Haunter.png" },
    94: { name: "gengar", type: "Ghost/Poison", image:"images/Normal/Gengar.png" },
    95: { name: "onix", type: "Rock/Ground", image:"images/Normal/Onix.png" },
    96: { name: "drowzee", type: "Psychic", image:"images/Normal/Drowzee.png" },
    97: { name: "hypno", type: "Psychic", image:"images/Normal/Hypno.png" },
    98: { name: "krabby", type: "Water", image:"images/Normal/Krabby.png" },
    99: { name: "kingler", type: "Water", image:"images/Normal/Kingler.png" },
    100: { name: "voltorb", type: "Electric", image:"images/Normal/Voltorb.png" },
    101: { name: "electrode", type: "Electric", image:"images/Normal/Electrode.png" },
    102: { name: "exeggcute", type: "Grass/Psychic", image:"images/Normal/Exeggcute.png" },
    103: { name: "exeggutor", type: "Grass/Psychic", image:"images/Normal/Exeggutor.png" },
    104: { name: "cubone", type: "Ground", image:"images/Normal/Cubone.png" },
    105: { name: "marowak", type: "Ground", image:"images/Normal/Marowak.png" },
    106: { name: "hitmonlee", type: "Fighting", image:"images/Normal/Hitmonlee.png" },
    107: { name: "hitmonchan", type: "Fighting", image:"images/Normal/Hitmonchan.png" },
    108: { name: "lickitung", type: "Normal", image:"images/Normal/Lickitung.png" },
    109: { name: "koffing", type: "Poison", image:"images/Normal/Koffing.png" },
    110: { name: "weezing", type: "Poison", image:"images/Normal/Weezing.png" },
    111: { name: "rhyhorn", type: "Ground/Rock", image:"images/Normal/Rhyhorn.png" },
    112: { name: "rhydon", type: "Ground/Rock", image:"images/Normal/Rhydon.png" },
    113: { name: "chansey", type: "Normal", image:"images/Normal/Chansey.png" },
    114: { name: "tangela", type: "Grass", image:"images/Normal/Tangela.png" },
    115: { name: "kangaskhan", type: "Normal", image:"images/Normal/Kangaskhan.png" },
    116: { name: "horsea", type: "Water", image:"images/Normal/Horsea.png" },
    117: { name: "seadra", type: "Water", image:"images/Normal/Seadra.png" },
    118: { name: "goldeen", type: "Water", image:"images/Normal/Goldeen.png" },
    119: { name: "seaking", type: "Water", image:"images/Normal/Seaking.png" },
    120: { name: "staryu", type: "Water", image:"images/Normal/Staryu.png" },
    121: { name: "starmie", type: "Water/Psychic", image:"images/Normal/Starmie.png" },
    122: { name: "mr-mime", type: "Psychic/Fairy", image:"images/Normal/Mr-Mime.png" },
    123: { name: "scyther", type: "Bug/Flying", image:"images/Normal/Scyther.png" },
    124: { name: "jynx", type: "Ice/Psychic", image:"images/Normal/Jynx.png" },
    125: { name: "electabuzz", type: "Electric", image:"images/Normal/Electabuzz.png" },
    126: { name: "magmar", type: "Fire", image:"images/Normal/Magmar.png" },
    127: { name: "pinsir", type: "Bug", image:"images/Normal/Pinsir.png" },
    128: { name: "tauros", type: "Normal", image:"images/Normal/Tauros.png" },
    129: { name: "magikarp", type: "Water", image:"images/Normal/Magikarp.png" },
    130: { name: "gyarados", type: "Water/Flying", image:"images/Normal/Gyarados.png" },
    131: { name: "lapras", type: "Water/Ice", image:"images/Normal/Lapras.png" },
    132: { name: "ditto", type: "Normal", image:"images/Normal/Ditto.png" },
    133: { name: "eevee", type: "Normal", image:"images/Normal/Eevee.png" },
    134: { name: "vaporeon", type: "Water", image:"images/Normal/Vaporeon.png" },
    135: { name: "jolteon", type: "Electric", image:"images/Normal/Jolteon.png" },
    136: { name: "flareon", type: "Fire", image:"images/Normal/Flareon.png" },
    137: { name: "porygon", type: "Normal", image:"images/Normal/Porygon.png" },
    138: { name: "omanyte", type: "Rock/Water", image:"images/Normal/Omanyte.png" },
    139: { name: "omastar", type: "Rock/Water", image:"images/Normal/Omastar.png" },
    140: { name: "kabuto", type: "Rock/Water", image:"images/Normal/Kabuto.png" },
    141: { name: "kabutops", type: "Rock/Water", image:"images/Normal/Kabutops.png" },
    142: { name: "aerodactyl", type: "Rock/Flying", image:"images/Normal/Aerodactyl.png" },
    143: { name: "snorlax", type: "Normal", image:"images/Normal/Snorlax.png" },
    144: { name: "articuno", type: "Ice/Flying", image:"images/Normal/Articuno.png" },
    145: { name: "zapdos", type: "Electric/Flying", image:"images/Normal/Zapdos.png" },
    146: { name: "moltres", type: "Fire/Flying", image:"images/Normal/Moltres.png" },
    147: { name: "dratini", type: "Dragon", image:"images/Normal/Dratini.png" },
    148: { name: "dragonair", type: "Dragon", image:"images/Normal/Dragonair.png" },
    149: { name: "dragonite", type: "Dragon/Flying", image:"images/Normal/Dragonite.png" },
    150: { name: "mewtwo", type: "Psychic", image:"images/Normal/Mewtwo.png" },
    151: { name: "mew", type: "Psychic", image:"images/Normal/Mew.png" }
    },
    johto: {
    152: {name: "Chikorita", type: "Grass", image:"images/Normal/Chikorita.png" },
    153: {name: "Bayleef", type: "Grass", image:"images/Normal/Bayleef.png" },
    154: {name: "Meganium", type: "Grass", image:"images/Normal/Meganium.png" },
    155: {name: "Cyndaquil", type: "Fire", image:"images/Normal/Cyndaquil.png" },
    156: {name: "Quilava", type: "Fire", image:"images/Normal/Quilava.png" },
    157: {name: "Typhlosion", type: "Fire", image:"images/Normal/Typhlosion.png" },
    158: {name: "Totodile", type: "Water", image:"images/Normal/Totodile.png" },
    159: {name: "Croconaw", type: "Water", image:"images/Normal/Croconaw.png" },
    160: {name: "Feraligatr", type: "Water", image:"images/Normal/Feraligatr.png" },
    161: {name: "Sentret", type: "Normal", image:"images/Normal/Sentret.png" },
    162: {name: "Furret", type: "Normal", image:"images/Normal/Furret.png" },
    163: {name: "Hoothoot", type: "Normal/Flying", image:"images/Normal/Hoothoot.png" },
    164: {name: "Noctowl", type: "Normal/Flying", image:"images/Normal/Noctowl.png" },
    165: {name: "Ledyba", type: "Bug/Flying", image:"images/Normal/Ledyba.png" },
    166: {name: "Ledian", type: "Bug/Flying", image:"images/Normal/Ledian.png" },
    167: {name: "Spinarak", type: "Bug/Poison", image:"images/Normal/Spinarak.png" },
    168: {name: "Ariados", type: "Bug/Poison", image:"images/Normal/Ariados.png" },
    169: {name: "Crobat", type: "Poison/Flying", image:"images/Normal/Crobat.png" },
    170: {name: "Chinchou", type: "Water/Electric", image:"images/Normal/Chinchou.png" },
    171: {name: "Lanturn", type: "Water/Electric", image:"images/Normal/Lanturn.png" },
    172: {name: "Pichu", type: "Electric", image:"images/Normal/Pichu.png" },
    173: {name: "Cleffa", type: "Fairy", image:"images/Normal/Cleffa.png" },
    174: {name: "Igglybuff", type: "Normal/Fairy", image:"images/Normal/Igglybuff.png" },
    175: {name: "Togepi", type: "Fairy", image:"images/Normal/Togepi.png" },
    176: {name: "Togetic", type: "Fairy/Flying", image:"images/Normal/Togetic.png" },
    177: {name: "Natu", type: "Psychic/Flying", image:"images/Normal/Natu.png" },
    178: {name: "Xatu", type: "Psychic/Flying", image:"images/Normal/Xatu.png" },
    179: {name: "Mareep", type: "Electric", image:"images/Normal/Mareep.png" },
    180: {name: "Flaaffy", type: "Electric", image:"images/Normal/Flaaffy.png" },
    181: {name: "Ampharos", type: "Electric", image:"images/Normal/Ampharos.png" },
    182: {name: "Bellossom", type: "Grass", image:"images/Normal/Bellossom.png" },
    183: {name: "Marill", type: "Water/Fairy", image:"images/Normal/Marill.png" },
    184: {name: "Azumarill", type: "Water/Fairy", image:"images/Normal/Azumarill.png" },
    185: {name: "Sudowoodo", type: "Rock", image:"images/Normal/Sudowoodo.png" },
    186: {name: "Politoed", type: "Water", image:"images/Normal/Politoed.png" },
    187: {name: "Hoppip", type: "Grass/Flying", image:"images/Normal/Hoppip.png" },
    188: {name: "Skiploom", type: "Grass/Flying", image:"images/Normal/Skiploom.png" },
    189: {name: "Jumpluff", type: "Grass/Flying", image:"images/Normal/Jumpluff.png" },
    190: {name: "Aipom", type: "Normal", image:"images/Normal/Aipom.png" },
    191: {name: "Sunkern", type: "Grass", image:"images/Normal/Sunkern.png" },
    192: {name: "Sunflora", type: "Grass", image:"images/Normal/Sunflora.png" },
    193: {name: "Yanma", type: "Bug/Flying", image:"images/Normal/Yanma.png" },
    194: {name: "Wooper", type: "Water/Ground", image:"images/Normal/Wooper.png" },
    195: {name: "Quagsire", type: "Water/Ground", image:"images/Normal/Quagsire.png" },
    196: {name: "Espeon", type: "Psychic", image:"images/Normal/Espeon.png" },
    197: {name: "Umbreon", type: "Dark", image:"images/Normal/Umbreon.png" },
    198: {name: "Murkrow", type: "Dark/Flying", image:"images/Normal/Murkrow.png" },
    199: {name: "Slowking", type: "Water/Psychic", image:"images/Normal/Slowking.png" },
    200: {name: "Misdreavus", type: "Ghost", image:"images/Normal/Misdreavus.png" },
    201: {name: "Unown", type: "Psychic", image:"images/Normal/Unown.png" },
    202: {name: "Wobbuffet", type: "Psychic", image:"images/Normal/Wobbuffet.png" },
    203: {name: "Girafarig", type: "Normal/Psychic", image:"images/Normal/Girafarig.png" },
    204: {name: "Pineco", type: "Bug", image:"images/Normal/Pineco.png" },
    205: {name: "Forretress", type: "Bug/Steel", image:"images/Normal/Forretress.png" },
    206: {name: "Dunsparce", type: "Normal", image:"images/Normal/Dunsparce.png" },
    207: {name: "Gligar", type: "Ground/Flying", image:"images/Normal/Gligar.png" },
    208: {name: "Steelix", type: "Steel/Ground", image:"images/Normal/Steelix.png" },
    209: {name: "Snubbull", type: "Fairy", image:"images/Normal/Snubbull.png" },
    210: {name: "Granbull", type: "Fairy", image:"images/Normal/Granbull.png" },
    211: {name: "Qwilfish", type: "Water/Poison", image:"images/Normal/Qwilfish.png" },
    212: {name: "Scizor", type: "Bug/Steel", image:"images/Normal/Scizor.png" },
    213: {name: "Shuckle", type: "Bug/Rock", image:"images/Normal/Shuckle.png" },
    214: {name: "Heracross", type: "Bug/Fighting", image:"images/Normal/Heracross.png" },
    215: {name: "Sneasel", type: "Dark/Ice", image:"images/Normal/Sneasel.png" },
    216: {name: "Teddiursa", type: "Normal", image:"images/Normal/Teddiursa.png" },
    217: {name: "Ursaring", type: "Normal", image:"images/Normal/Ursaring.png" },
    218: {name: "Slugma", type: "Fire", image:"images/Normal/Slugma.png" },
    219: {name: "Magcargo", type: "Fire/Rock", image:"images/Normal/Magcargo.png" },
    220: {name: "Swinub", type: "Ice/Ground", image:"images/Normal/Swinub.png" },
    221: {name: "Piloswine", type: "Ice/Ground", image:"images/Normal/Piloswine.png" },
    222: {name: "Corsola", type: "Water/Rock", image:"images/Normal/Corsola.png" },
    223: {name: "Remoraid", type: "Water", image:"images/Normal/Remoraid.png" },
    224: {name: "Octillery", type: "Water", image:"images/Normal/Octillery.png" },
    225: {name: "Delibird", type: "Ice/Flying", image:"images/Normal/Delibird.png" },
    226: {name: "Mantine", type: "Water/Flying", image:"images/Normal/Mantine.png" },
    227: {name: "Skarmory", type: "Steel/Flying", image:"images/Normal/Skarmory.png" },
    228: {name: "Houndour", type: "Dark/Fire", image:"images/Normal/Houndour.png" },
    229: {name: "Houndoom", type: "Dark/Fire", image:"images/Normal/Houndoom.png" },
    230: {name: "Kingdra", type: "Water/Dragon", image:"images/Normal/Kingdra.png" },
    231: {name: "Phanpy", type: "Ground", image:"images/Normal/Phanpy.png" },
    232: {name: "Donphan", type: "Ground", image:"images/Normal/Donphan.png" },
    233: {name: "Porygon2", type: "Normal", image:"images/Normal/Porygon2.png" },
    234: {name: "Stantler", type: "Normal", image:"images/Normal/Stantler.png" },
    235: {name: "Smeargle", type: "Normal", image:"images/Normal/Smeargle.png" },
    236: {name: "Tyrogue", type: "Fighting", image:"images/Normal/Tyrogue.png" },
    237: {name: "Hitmontop", type: "Fighting", image:"images/Normal/Hitmontop.png" },
    238: {name: "Smoochum", type: "Ice/Psychic", image:"images/Normal/Smoochum.png" },
    239: {name: "Elekid", type: "Electric", image:"images/Normal/Elekid.png" },
    240: {name: "Magby", type: "Fire", image:"images/Normal/Magby.png" },
    241: {name: "Miltank", type: "Normal", image:"images/Normal/Miltank.png" },
    242: {name: "Blissey", type: "Normal", image:"images/Normal/Blissey.png" },
    243: {name: "Raikou", type: "Electric", image:"images/Normal/Raikou.png" },
    244: {name: "Entei", type: "Fire", image:"images/Normal/Entei.png" },
    245: {name: "Suicune", type: "Water", image:"images/Normal/Suicune.png" },
    246: {name: "Larvitar", type: "Rock/Ground", image:"images/Normal/Larvitar.png" },
    247: {name: "Pupitar", type: "Rock/Ground", image:"images/Normal/Pupitar.png" },
    248: {name: "Tyranitar", type: "Rock/Dark", image:"images/Normal/Tyranitar.png" },
    249: {name: "Lugia", type: "Psychic/Flying", image:"images/Normal/Lugia.png" },
    250: {name: "Ho-Oh", type: "Fire/Flying", image:"images/Normal/Ho-Oh.png" },
    251: {name: "Celebi", type: "Psychic/Grass", image:"images/Normal/Celebi.png" }
},
    hoenn: {
    252: {name: "Treecko", type: "Grass", image:"images/Normal/treecko.png" },
    253: {name: "Grovyle", type: "Grass", image:"images/Normal/grovyle.png" },
    254: {name: "Sceptile",type: "Grass",image:"images/Normal/sceptile.png"},
    255: {name: "Torchic",type: "Fire",image:"images/Normal/torchic.png"},
    256: {name: "Combusken",type: "Fire · Fighting",image:"images/Normal/combusken.png"},
    257: {name: "Blaziken",type: "Fire · Fighting",image:"images/Normal/blaziken.png"},
    258: {name: "Mudkip",type: "Water", image:"E:/Family/Pokedex/sprites/Normal/mudkip.png"},
    259: {name: "Marshtomp",type: "Water · Ground",image:"images/Normal/marshtomp.png"},
    260: {name: "Swampert",type: "Water · Ground",image:"images/Normal/swampert.png"},
    261: {name: "Poochyena",type: "Dark",image:"images/Normal/poochyena.png"},
    262: {name: "Mightyena",type: "Dark",image:"images/Normal/mightyena.png"},
    263: {name: "Zigzagoon", type: "Normal", image:"images/Normal/zigzagoon.png" },
    264: {name: "Linoone", type: "Normal", image:"images/Normal/linoone.png" },
    265: {name: "Wurmple", type: "Bug", image:"images/Normal/wurmple.png" },
    266: {name: "Silcoon", type: "Bug", image:"images/Normal/silcoon.png" },
    267: {name: "Beautifly", type: "Bug · Flying", image:"images/Normal/beautifly.png" },
    268: {name: "Cascoon", type: "Bug", image:"images/Normal/cascoon.png" },
    269: {name: "Dustox", type: "Bug · Poison", image:"images/Normal/dustox.png" },
    270: {name: "Lotad", type: "Water · Grass", image:"images/Normal/lotad.png" },
    271: {name: "Lombre", type: "Water · Grass", image:"images/Normal/lombre.png" },
    272: {name: "Ludicolo", type: "Water · Grass", image:"images/Normal/ludicolo.png" },
    273: {name: "Seedot", type: "Grass", image:"images/Normal/seedot.png" },
    274: {name: "Nuzleaf", type: "Grass · Dark", image:"images/Normal/nuzleaf.png" },
    275: {name: "Shiftry", type: "Grass · Dark", image:"images/Normal/shiftry.png" },
    276: {name: "Taillow", type: "Normal · Flying", image:"images/Normal/taillow.png" },
    277: {name: "Swellow", type: "Normal · Flying", image:"images/Normal/swellow.png" },
    278: {name: "Wingull", type: "Water · Flying", image:"images/Normal/wingull.png" },
    279: {name: "Pelipper", type: "Water · Flying", image:"images/Normal/pelipper.png" },
    280: {name: "Ralts", type: "Psychic · Fairy", image:"images/Normal/ralts.png" },
    281: {name: "Kirlia", type: "Psychic · Fairy", image:"images/Normal/kirlia.png" },
    282: {name: "Gardevoir", type: "Psychic · Fairy", image:"images/Normal/gardevoir.png" },
    283: {name: "Surskit", type: "Bug · Water", image:"images/Normal/surskit.png" },
    284: {name: "Masquerain", type: "Bug · Flying", image:"images/Normal/masquerain.png" },
    285: {name: "Shroomish", type: "Grass", image:"images/Normal/shroomish.png" },
    286: {name: "Breloom", type: "Grass · Fighting", image:"images/Normal/breloom.png" },
    287: {name: "Slakoth", type: "Normal", image:"images/Normal/slakoth.png" },
    288: {name: "Vigoroth", type: "Normal", image:"images/Normal/vigoroth.png" },
    289: {name: "Slaking", type: "Normal", image:"images/Normal/slaking.png" },
    290: {name: "Nincada", type: "Bug · Ground", image:"images/Normal/nincada.png" },
    291: {name: "Ninjask", type: "Bug · Flying", image:"images/Normal/ninjask.png" },
    292: {name: "Shedinja", type: "Bug · Ghost", image:"images/Normal/shedinja.png" },
    293: {name: "Whismur", type: "Normal", image:"images/Normal/whismur.png" },
    294: {name: "Loudred", type: "Normal", image:"images/Normal/loudred.png" },
    295: {name: "Exploud", type: "Normal", image:"images/Normal/exploud.png" },
    296: {name: "Makuhita", type: "Fighting", image:"images/Normal/makuhita.png" },
    297: {name: "Hariyama", type: "Fighting", image:"images/Normal/hariyama.png" },
    298: {name: "Azurill", type: "Normal · Fairy", image:"images/Normal/azurill.png" },
    299: {name: "Nosepass", type: "Rock", image:"images/Normal/nosepass.png" },
    300: {name: "Skitty", type: "Normal", image:"images/Normal/skitty.png" },
    301: {name: "Delcatty", type: "Normal", image:"images/Normal/delcatty.png" },
    302: {name: "Sableye", type: "Dark · Ghost", image:"images/Normal/sableye.png" },
    303: {name: "Mawile",type: "Steel · Fairy",image:"images/Normal/mawile.png"},
    304: {name: "Aron",type: "Steel · Rock",image:"images/Normal/aron.png"},
    305: {name: "Lairon",type: "Steel · Rock", image:"images/Normal/lairon.png"},
    306: {name: "Aggron",type: "Steel · Rock",image:"images/Normal/aggron.png"},
    307: {name: "Meditite",type: "Fighting · Psychic",image:"images/Normal/meditite.png"},
    308: {name: "Medicham",type: "Fighting · Psychic",image:"images/Normal/medicham.png"},
    309: {name: "Electrike",type: "Electric",image:"images/Normal/electrike.png"},
    310: {name: "Manectric",type: "Electric",image:"images/Normal/manectric.png"},
    311: {name: "Plusle",type: "Electric",image:"images/Normal/plusle.png"},
    312: {name: "Minun",type: "Electric",image:"images/Normal/minun.png"},
    313: {name: "Volbeat",type: "Bug",image:"images/Normal/volbeat.png"},
    314: {name: "Illumise",type: "Bug",image:"images/Normal/illumise.png"},
    315: {name: "Roselia",type: "Grass · Poison",image:"images/Normal/roselia.png"},
    316: {name: "Gulpin",type: "Poison",image:"images/Normal/gulpin.png"},
    317: {name: "Swalot",type: "Poison",image:"images/Normal/swalot.png"},
    318: {name: "Carvanha",type: "Water · Dark",image:"images/Normal/carvanha.png"},
    319: {name: "Sharpedo",type: "Water · Dark",image:"images/Normal/sharpedo.png"},
    320: {name: "Wailmer",type: "Water",image:"images/Normal/wailmer.png"},
    321: {name: "Wailord",type: "Water",image:"images/Normal/wailord.png"},
    322: {name: "Numel",type: "Fire · Ground",image:"images/Normal/numel.png"},
    323: {name: "Camerupt",type: "Fire · Ground",image:"images/Normal/camerupt.png"},
    324: {name: "Torkoal",type: "Fire",image:"images/Normal/torkoal.png"},
    325: {name: "Spoink",type: "Psychic",image:"images/Normal/spoink.png"},
    326: {name: "Grumpig",type: "Psychic",image:"images/Normal/grumpig.png"},
    327: {name: "Spinda",type: "Normal",image:"images/Normal/spinda.png"},
    328: {name: "Trapinch",type: "Ground",image:"images/Normal/trapinch.png"},
    329: {name: "Vibrava",type: "Ground · Dragon",image:"images/Normal/vibrava.png"},
    330: {name: "Flygon",type: "Ground · Dragon",image:"images/Normal/flygon.png"},
    331: {name: "Cacnea",type: "Grass",image:"images/Normal/cacnea.png"},
    332: {name: "Cacturne",type: "Grass · Dark",image:"images/Normal/cacturne.png"},
    333: {name: "Swablu",type: "Normal · Flying",image:"images/Normal/swablu.png"},
    334: {name: "Altaria",type: "Dragon · Flying",image:"images/Normal/altaria.png"},
    335: {name: "Zangoose",type: "Normal",image:"images/Normal/zangoose.png"},
    336: {name: "Seviper",type: "Poison",image:"images/Normal/seviper.png"},
    337: {name: "Lunatone",type: "Rock · Psychic",image:"images/Normal/lunatone.png"},
    338: {name: "Solrock",type: "Rock · Psychic",image:"images/Normal/solrock.png"},
    339: {name: "Barboach",type: "Water · Ground",image:"images/Normal/barboach.png"},
    340: {name: "Whiscash",type: "Water · Ground",image:"images/Normal/whiscash.png"},
    341: {name: "Corphish", type: "Water", image:"images/Normal/corphish.png" },
    342: {name: "Crawdaunt",type: "Water · Dark",image:"images/Normal/crawdaunt.png"},
    343: {name: "Baltoy",type: "Ground · Psychic",image:"images/Normal/baltoy.png"},
    344: {name: "Claydol",type: "Ground · Psychic",image:"images/Normal/claydol.png"},
    345: {name: "Lileep",type: "Rock · Grass",image:"images/Normal/lileep.png"},
    346: {name: "Cradily",type: "Rock · Grass",image:"images/Normal/cradily.png"},
    347: {name: "Anorith",type: "Rock · Bug",image:"images/Normal/anorith.png"},
    348: {name: "Armaldo",type: "Rock · Bug",image:"images/Normal/armaldo.png"},
    349: {name: "Feebas",type: "Water",image:"images/Normal/feebas.png"},
    350: {name: "Milotic",type: "Water",image:"images/Normal/milotic.png"},
    351: {name: "Castform",type: "Normal",image:"images/Normal/castform.png"},
    352: {name: "Kecleon",type: "Normal",image:"images/Normal/kecleon.png"},
    353: {name: "Shuppet",type: "Ghost",image:"images/Normal/shuppet.png"},
    354: {name: "Banette",type: "Ghost",image:"images/Normal/banette.png"},
    355: {name: "Duskull",type: "Ghost",image:"images/Normal/duskull.png"},
    356: {name: "Dusclops",type: "Ghost",image:"images/Normal/dusclops.png"},
    357: {name: "Tropius",type: "Grass · Flying",image:"images/Normal/tropius.png"},
    358: {name: "Chimecho", type: "Psychic", image:"images/Normal/chimecho.png" },
    359: {name: "Absol",type: "Dark",image:"images/Normal/absol.png"},
    360: {name: "Wynaut",type: "Psychic",image:"images/Normal/wynaut.png"},
    361: {name: "Snorunt",type: "Ice",image:"images/Normal/snorunt.png"},
    362: {name: "Glalie",type: "Ice",image:"images/Normal/glalie.png"},
    363: {name: "Spheal",type: "Ice · Water",image:"images/Normal/spheal.png"},
    364: {name: "Sealeo",type: "Ice · Water",image:"images/Normal/sealeo.png"},
    365: {name: "Walrein",type: "Ice · Water",image:"images/Normal/walrein.png"},
    366: {name: "Clamperl",type: "Water",image:"images/Normal/clamperl.png"},
    367: {name: "Huntail",type: "Water",image:"images/Normal/huntail.png"},
    368: {name: "Gorebyss",type: "Water",image:"images/Normal/gorebyss.png"},
    369: {name: "Relicanth",type: "Water · Rock",image:"images/Normal/relicanth.png"},
    370: {name: "Luvdisc",type: "Water",image:"images/Normal/luvdisc.png"},
    371: {name: "Bagon",type: "Dragon",image:"images/Normal/bagon.png"},
    372: {name: "Shelgon",type: "Dragon",image:"images/Normal/shelgon.png"},
    373: {name: "Salamence",type: "Dragon · Flying",image:"images/Normal/salamence.png"},
    374: {name: "Beldum",type: "Steel · Psychic",image:"images/Normal/beldum.png"},
    375: {name: "Metang",type: "Steel · Psychic",image:"images/Normal/metang.png"},
    376: {name: "Metagross",type: "Steel · Psychic",image:"images/Normal/metagross.png"},
    377: {name: "Regirock",type: "Rock",image:"images/Normal/regirock.png"},
    378: {name: "Regice",type: "Ice",image:"images/Normal/regice.png"},
    379: {name: "Registeel",type: "Steel",image:"images/Normal/registeel.png"},
    380: {name: "Latias",type: "Dragon · Psychic",image:"images/Normal/latias.png"},
    381: {name: "Latios",type: "Dragon · Psychic",image:"images/Normal/latios.png"},
    382: {name: "Kyogre",type: "Water",image:"images/Normal/kyogre.png"},
    383: {name: "Groudon",type: "Ground",image:"images/Normal/groudon.png"},
    384: {name: "Rayquaza",type: "Dragon · Flying",image:"images/Normal/rayquaza.png"},
    385: {name: "Jirachi",type: "Steel · Psychic",image:"images/Normal/jirachi.png"},
    386: {name: "Deoxys",type: "Psychic",image:"images/Normal/deoxys.png"}
    },
    sinnoh:{
    387: { name: "Turtwig", type: "Grass", image:"images/Normal/Turtwig.png" },
    388: { name: "Grotle", type: "Grass", image:"images/Normal/Grotle.png" },
    389: { name: "Torterra", type: "Grass · Ground", image:"images/Normal/Torterra.png" },
    390: { name: "Chimchar", type: "Fire", image:"images/Normal/Chimchar.png" },
    391: { name: "Monferno", type: "Fire · Fighting", image:"images/Normal/Monferno.png" },
    392: { name: "Infernape", type: "Fire · Fighting", image:"images/Normal/Infernape.png" },
    393: { name: "Piplup", type: "Water", image:"images/Normal/Piplup.png" },
    394: { name: "Prinplup", type: "Water", image:"images/Normal/Prinplup.png" },
    395: { name: "Empoleon", type: "Water · Steel", image:"images/Normal/Empoleon.png" },
    396: { name: "Starly", type: "Normal · Flying", image:"images/Normal/Starly.png" },
    397: { name: "Staravia", type: "Normal · Flying", image:"images/Normal/Staravia.png" },
    398: { name: "Staraptor", type: "Normal · Flying", image:"images/Normal/Staraptor.png" },
    399: { name: "Bidoof", type: "Normal", image:"images/Normal/Bidoof.png" },
    400: { name: "Bibarel", type: "Normal · Water", image:"images/Normal/Bibarel.png" },
    401: { name: "Kricketot", type: "Bug", image:"images/Normal/Kricketot.png" },
    402: { name: "Kricketune", type: "Bug", image:"images/Normal/Kricketune.png" },
    403: { name: "Shinx", type: "Electric", image:"images/Normal/Shinx.png" },
    404: { name: "Luxio", type: "Electric", image:"images/Normal/Luxio.png" },
    405: { name: "Luxray", type: "Electric", image:"images/Normal/Luxray.png" },
    406: { name: "Budew", type: "Grass · Poison", image:"images/Normal/Budew.png" },
    407: { name: "Roserade", type: "Grass · Poison", image:"images/Normal/Roserade.png" },
    408: { name: "Cranidos", type: "Rock", image:"images/Normal/Cranidos.png" },
    409: { name: "Rampardos", type: "Rock", image:"images/Normal/Rampardos.png" },
    410: { name: "Shieldon", type: "Rock · Steel", image:"images/Normal/Shieldon.png" },
    411: { name: "Bastiodon", type: "Rock · Steel", image:"images/Normal/Bastiodon.png" },
    412: { name: "Burmy", type: "Bug", image:"images/Normal/Burmy.png" },
    413: { name: "Wormadam", type: "Bug · Grass", image:"images/Normal/Wormadam.png" },
    414: { name: "Mothim", type: "Bug · Flying", image:"images/Normal/Mothim.png" },
    415: { name: "Combee", type: "Bug · Flying", image:"images/Normal/Combee.png" },
    416: { name: "Vespiquen", type: "Bug · Flying", image:"images/Normal/Vespiquen.png" },
    417: { name: "Pachirisu", type: "Electric", image:"images/Normal/Pachirisu.png" },
    418: { name: "Buizel", type: "Water", image:"images/Normal/Buizel.png" },
    419: { name: "Floatzel", type: "Water", image:"images/Normal/Floatzel.png" },
    420: { name: "Cherubi", type: "Grass", image:"images/Normal/Cherubi.png" },
    421: { name: "Cherrim", type: "Grass", image:"images/Normal/Cherrim.png" },
    422: { name: "Shellos", type: "Water", image:"images/Normal/Shellos.png" },
    423: { name: "Gastrodon", type: "Water · Ground", image:"images/Normal/Gastrodon.png" },
    424: { name: "Ambipom", type: "Normal", image:"images/Normal/Ambipom.png" },
    425: { name: "Drifloon", type: "Ghost · Flying", image:"images/Normal/Drifloon.png" },
    426: { name: "Drifblim", type: "Ghost · Flying", image:"images/Normal/Drifblim.png" },
    427: { name: "Buneary", type: "Normal", image:"images/Normal/Buneary.png" },
    428: { name: "Lopunny", type: "Normal", image:"images/Normal/Lopunny.png" },
    429: { name: "Mismagius", type: "Ghost", image:"images/Normal/Mismagius.png" },
    430: { name: "Honchkrow", type: "Dark · Flying", image:"images/Normal/Honchkrow.png" },
    431: { name: "Glameow", type: "Normal", image:"images/Normal/Glameow.png" },
    432: { name: "Purugly", type: "Normal", image:"images/Normal/Purugly.png" },
    433: { name: "Chingling", type: "Psychic", image:"images/Normal/Chingling.png" },
    434: { name: "Stunky", type: "Poison · Dark", image:"images/Normal/Stunky.png" },
    435: { name: "Skuntank", type: "Poison · Dark", image:"images/Normal/Skuntank.png" },
    436: { name: "Bronzor", type: "Steel · Psychic", image:"images/Normal/Bronzor.png" },
    437: { name: "Bronzong", type: "Steel · Psychic", image:"images/Normal/Bronzong.png" },
    438: { name: "Bonsly", type: "Rock", image:"images/Normal/Bonsly.png" },
    439: { name: "Mime Jr.", type: "Psychic · Fairy", image:"images/Normal/Mime Jr..png" },
    440: { name: "Happiny", type: "Normal", image:"images/Normal/Happiny.png" },
    441: { name: "Chatot", type: "Normal · Flying", image:"images/Normal/Chatot.png" },
    442: { name: "Spiritomb", type: "Ghost · Dark", image:"images/Normal/Spiritomb.png" },
    443: { name: "Gible", type: "Dragon · Ground", image:"images/Normal/Gible.png" },
    444: { name: "Gabite", type: "Dragon · Ground", image:"images/Normal/Gabite.png" },
    445: { name: "Garchomp", type: "Dragon · Ground", image:"images/Normal/Garchomp.png" },
    446: { name: "Munchlax", type: "Normal", image:"images/Normal/Munchlax.png" },
    447: { name: "Riolu", type: "Fighting", image:"images/Normal/Riolu.png" },
    448: { name: "Lucario", type: "Fighting · Steel", image:"images/Normal/Lucario.png" },
    449: { name: "Hippopotas", type: "Ground", image:"images/Normal/Hippopotas.png" },
    450: { name: "Hippowdon", type: "Ground", image:"images/Normal/Hippowdon.png" },
    451: { name: "Skorupi", type: "Poison · Bug", image:"images/Normal/Skorupi.png" },
    452: { name: "Drapion", type: "Poison · Dark", image:"images/Normal/Drapion.png" },
    453: { name: "Croagunk", type: "Poison · Fighting", image:"images/Normal/Croagunk.png" },
    454: { name: "Toxicroak", type: "Poison · Fighting", image:"images/Normal/Toxicroak.png" },
    455: { name: "Carnivine", type: "Grass", image:"images/Normal/Carnivine.png" },
    456: { name: "Finneon", type: "Water", image:"images/Normal/Finneon.png" },
    457: { name: "Lumineon", type: "Water", image:"images/Normal/Lumineon.png" },
    458: { name: "Mantyke", type: "Water · Flying", image:"images/Normal/Mantyke.png" },
    459: { name: "Snover", type: "Grass · Ice", image:"images/Normal/Snover.png" },
    460: { name: "Abomasnow", type: "Grass · Ice", image:"images/Normal/Abomasnow.png" },
    461: { name: "Weavile", type: "Dark · Ice", image:"images/Normal/Weavile.png" },
    462: { name: "Magnezone", type: "Electric · Steel", image:"images/Normal/Magnezone.png" },
    463: { name: "Lickilicky", type: "Normal", image:"images/Normal/Lickilicky.png" },
    464: { name: "Rhyperior", type: "Ground · Rock", image:"images/Normal/Rhyperior.png" },
    465: { name: "Tangrowth", type: "Grass", image:"images/Normal/Tangrowth.png" },
    466: { name: "Electivire", type: "Electric", image:"images/Normal/Electivire.png" },
    467: { name: "Magmortar", type: "Fire", image:"images/Normal/Magmortar.png" },
    468: { name: "Togekiss", type: "Fairy · Flying", image:"images/Normal/Togekiss.png" },
    469: { name: "Yanmega", type: "Bug · Flying", image:"images/Normal/Yanmega.png" },
    470: { name: "Leafeon", type: "Grass", image:"images/Normal/Leafeon.png" },
    471: { name: "Glaceon", type: "Ice", image:"images/Normal/Glaceon.png" },
    472: { name: "Gliscor", type: "Ground · Flying", image:"images/Normal/Gliscor.png" },
    473: { name: "Mamoswine", type: "Ice · Ground", image:"images/Normal/Mamoswine.png" },
    474: { name: "Porygon-Z", type: "Normal", image:"images/Normal/Porygon-Z.png" },
    475: { name: "Gallade", type: "Psychic · Fighting", image:"images/Normal/Gallade.png" },
    476: { name: "Probopass", type: "Rock · Steel", image:"images/Normal/Probopass.png" },
    477: { name: "Dusknoir", type: "Ghost", image:"images/Normal/Dusknoir.png" },
    478: { name: "Froslass", type: "Ice · Ghost", image:"images/Normal/Froslass.png" },
    479: { name: "Rotom", type: "Electric · Ghost", image:"images/Normal/Rotom.png" },
    480: { name: "Uxie", type: "Psychic", image:"images/Normal/Uxie.png" },
    481: { name: "Mesprit", type: "Psychic", image:"images/Normal/Mesprit.png" },
    482: { name: "Azelf", type: "Psychic", image:"images/Normal/Azelf.png" },
    483: { name: "Dialga", type: "Steel · Dragon", image:"images/Normal/Dialga.png" },
    484: { name: "Palkia", type: "Water · Dragon", image:"images/Normal/Palkia.png" },
    485: { name: "Heatran", type: "Fire · Steel", image:"images/Normal/Heatran.png" },
    486: { name: "Regigigas", type: "Normal", image:"images/Normal/Regigigas.png" },
    487: { name: "Giratina", type: "Ghost · Dragon", image:"images/Normal/Giratina.png" },
    488: { name: "Cresselia", type: "Psychic", image:"images/Normal/Cresselia.png" },
    489: { name: "Phione", type: "Water", image:"images/Normal/Phione.png" },
    490: { name: "Manaphy", type: "Water", image:"images/Normal/Manaphy.png" },
    491: { name: "Darkrai", type: "Dark", image:"images/Normal/Darkrai.png" },
    492: { name: "Shaymin", type: "Grass", image:"images/Normal/Shaymin.png" },
    493: { name: "Arceus", type: "Normal", image:"images/Normal/Arceus.png" }
    },
    
    unova: {
    494: { name: "Victini", type: "Psychic/Fire", image:"images/Normal/Victini.png" },
    495: { name: "Snivy", type: "Grass", image:"images/Normal/Sniv.png" },
    496: { name: "Servine", type: "Grass", image:"images/Normal/Servine.png" },
    497: { name: "Serperior", type: "Grass", image:"images/Normal/Serperior.png" },
    498: { name: "Tepig", type: "Fire", image:"images/Normal/Tepig.png" },
    499: { name: "Pignite", type: "Fire/Fighting", image:"images/Normal/Pignite.png" },
    500: { name: "Emboar", type: "Fire/Fighting", image:"images/Normal/Emboar.png" },
    501: { name: "Oshawott", type: "Water", image:"images/Normal/Oshawott.png" },
    502: { name: "Dewott", type: "Water", image:"images/Normal/Dewott.png" },
    503: { name: "Samurott", type: "Water", image:"images/Normal/Samurott.png" },
    504: { name: "Patrat", type: "Normal", image:"images/Normal/Patrat.png" },
    505: { name: "Watchog", type: "Normal", image:"images/Normal/Watchog.png" },
    506: { name: "Lillipup", type: "Normal", image:"images/Normal/Lillipup.png" },
    507: { name: "Herdier", type: "Normal", image:"images/Normal/Herdier.png" },
    508: { name: "Stoutland", type: "Normal", image:"images/Normal/Stoutland.png" },
    509: { name: "Purrloin", type: "Dark", image:"images/Normal/Purrloin.png" },
    510: { name: "Liepard", type: "Dark", image:"images/Normal/Liepard.png" },
    511: { name: "Pansage", type: "Grass", image:"images/Normal/Pansage.png" },
    512: { name: "Simisage", type: "Grass", image:"images/Normal/Simisage.png" },
    513: { name: "Pansear", type: "Fire", image:"images/Normal/Pansear.png" },
    514: { name: "Simisear", type: "Fire", image:"images/Normal/Simisear.png" },
    515: { name: "Panpour", type: "Water", image:"images/Normal/Panpour.png" },
    516: { name: "Simipour", type: "Water", image:"images/Normal/Simipour.png" },
    517: { name: "Munna", type: "Psychic", image:"images/Normal/Munna.png" },
    518: { name: "Musharna", type: "Psychic", image:"images/Normal/Musharna.png" },
    519: { name: "Pidove", type: "Normal/Flying", image:"images/Normal/Pidove.png" },
    520: { name: "Tranquill", type: "Normal/Flying", image:"images/Normal/Tranquill.png" },
    521: { name: "Unfezant", type: "Normal/Flying", image:"images/Normal/Unfezant.png" },
    522: { name: "Blitzle", type: "Electric", image:"images/Normal/Blitzle.png" },
    523: { name: "Zebstrika", type: "Electric", image:"images/Normal/Zebstrika.png" },
    524: { name: "Roggenrola", type: "Rock", image:"images/Normal/Roggenrola.png" },
    525: { name: "Boldore", type: "Rock", image:"images/Normal/Boldore.png" },
    526: { name: "Gigalith", type: "Rock", image:"images/Normal/Gigalith.png" },
    527: { name: "Woobat", type: "Psychic/Flying", image:"images/Normal/Woobat.png" },
    528: { name: "Swoobat", type: "Psychic/Flying", image:"images/Normal/Swoobat.png" },
    529: { name: "Drilbur", type: "Ground", image:"images/Normal/Drilbur.png" },
    530: { name: "Excadrill", type: "Ground/Steel", image:"images/Normal/Excadrill.png" },
    531: { name: "Audino", type: "Normal", image:"images/Normal/Audino.png" },
    532: { name: "Timburr", type: "Fighting", image:"images/Normal/Timburr.png" },
    533: { name: "Gurdurr", type: "Fighting", image:"images/Normal/Gurdurr.png" },
    534: { name: "Conkeldurr", type: "Fighting", image:"images/Normal/Conkeldurr.png" },
    535: { name: "Tympole", type: "Water", image:"images/Normal/Tympole.png" },
    536: { name: "Palpitoad", type: "Water · Ground", image:"images/Normal/Palpitoad.png" },
    537: { name: "Seismitoad", type: "Water · Ground", image:"images/Normal/Seismitoad.png" },
    538: { name: "Throh", type: "Fighting", image:"images/Normal/Throh.png" },
    539: { name: "Sawk", type: "Fighting", image:"images/Normal/Sawk.png" },
    540: { name: "Sewaddle", type: "Bug · Grass", image:"images/Normal/Sewaddle.png" },
    541: { name: "Swadloon", type: "Bug · Grass", image:"images/Normal/Swadloon.png" },
    542: { name: "Leavanny", type: "Bug · Grass", image:"images/Normal/Leavanny.png" },
    543: { name: "Venipede", type: "Bug · Poison", image:"images/Normal/Venipede.png" },
    544: { name: "Whirlipede", type: "Bug · Poison", image:"images/Normal/Whirlipede.png" },
    545: { name: "Scolipede", type: "Bug · Poison", image:"images/Normal/Scolipede.png" },
    546: { name: "Cottonee", type: "Grass · Fairy", image:"images/Normal/Cottonee.png" },
    547: { name: "Whimsicott", type: "Grass · Fairy", image:"images/Normal/Whimsicott.png" },
    548: { name: "Petilil", type: "Grass", image:"images/Normal/Petilil.png" },
    549: { name: "Lilligant", type: "Grass", image:"images/Normal/Lilligant.png" },
    550: { name: "Basculin", type: "Water", image:"images/Normal/Basculin.png" },
    551: { name: "Sandile", type: "Ground · Dark", image:"images/Normal/Sandile.png" },
    552: { name: "Krokorok", type: "Ground · Dark", image:"images/Normal/Krokorok.png" },
    553: { name: "Krookodile", type: "Ground · Dark", image:"images/Normal/Krookodile.png" },
    554: { name: "Darumaka", type: "Fire", image:"images/Normal/Darumaka.png" },
    555: { name: "Darmanitan", type: "Fire", image:"images/Normal/Darmanitan.png" },
    556: { name: "Maractus", type: "Grass", image:"images/Normal/Maractus.png" },
    557: { name: "Dwebble", type: "Bug · Rock", image:"images/Normal/Dwebble.png" },
    558: { name: "Crustle", type: "Bug · Rock", image:"images/Normal/Crustle.png" },
    559: { name: "Scraggy", type: "Dark · Fighting", image:"images/Normal/Scraggy.png" },
    560: { name: "Scrafty", type: "Dark · Fighting", image:"images/Normal/Scrafty.png" },
    561: { name: "Sigilyph", type: "Psychic · Flying", image:"images/Normal/Sigilyph.png" },
    562: { name: "Yamask", type: "Ghost", image:"images/Normal/Yamask.png" },
    563: { name: "Cofagrigus", type: "Ghost", image:"images/Normal/Cofagrigus.png" },
    564: { name: "Tirtouga", type: "Water · Rock", image:"images/Normal/Tirtouga.png" },
    565: { name: "Carracosta", type: "Water · Rock", image:"images/Normal/Carracosta.png" },
    566: { name: "Archen", type: "Rock · Flying", image:"images/Normal/Archen.png" },
    567: { name: "Archeops", type: "Rock · Flying", image:"images/Normal/Archeops.png" },
    568: { name: "Trubbish", type: "Poison", image:"images/Normal/Trubbish.png" },
    569: { name: "Garbodor", type: "Poison", image:"images/Normal/Garbodor.png" },
    570: { name: "Zorua", type: "Dark", image:"images/Normal/Zorua.png" },
    571: { name: "Zoroark", type: "Dark", image:"images/Normal/Zoroark.png" },
    572: { name: "Minccino", type: "Normal", image:"images/Normal/Minccino.png" },
    573: { name: "Cinccino", type: "Normal", image:"images/Normal/Cinccino.png" },
    574: { name: "Gothita", type: "Psychic", image:"images/Normal/Gothita.png" },
    575: { name: "Gothorita", type: "Psychic", image:"images/Normal/Gothorita.png" },
    576: { name: "Gothitelle", type: "Psychic", image:"images/Normal/Gothitelle.png" },
    577: { name: "Solosis", type: "Psychic", image:"images/Normal/Solosis.png" },
    578: { name: "Duosion", type: "Psychic", image:"images/Normal/Duosion.png" },
    579: { name: "Reuniclus", type: "Psychic", image:"images/Normal/Reuniclus.png" },
    580: { name: "Ducklett", type: "Water · Flying", image:"images/Normal/Ducklett.png" },
    581: { name: "Swanna", type: "Water · Flying", image:"images/Normal/Swanna.png" },
    582: { name: "Vanillite", type: "Ice", image:"images/Normal/Vanillite.png" },
    583: { name: "Vanillish", type: "Ice", image:"images/Normal/Vanillish.png" },
    584: { name: "Vanilluxe", type: "Ice", image:"images/Normal/Vanilluxe.png" },
    585: { name: "Deerling", type: "Normal · Grass", image:"images/Normal/Deerling.png" },
    586: { name: "Sawsbuck", type: "Normal · Grass", image:"images/Normal/Sawsbuck.png" },
    587: { name: "Emolga", type: "Electric · Flying", image:"images/Normal/Emolga.png" },
    588: { name: "Karrablast", type: "Bug", image:"images/Normal/Karrablast.png" },
    589: { name: "Escavalier", type: "Bug · Steel", image:"images/Normal/Escavalier.png" },
    590: { name: "Foongus", type: "Grass · Poison", image:"images/Normal/Foongus.png" },
    591: { name: "Amoonguss", type: "Grass · Poison", image:"images/Normal/Amoonguss.png" },
    592: { name: "Frillish", type: "Water · Ghost", image:"images/Normal/Frillish.png" },
    593: { name: "Jellicent", type: "Water · Ghost", image:"images/Normal/Jellicent.png" },
    594: { name: "Alomomola", type: "Water", image:"images/Normal/Alomomola.png" },
    595: { name: "Joltik", type: "Bug · Electric", image:"images/Normal/Joltik.png" },
    596: { name: "Galvantula", type: "Bug · Electric", image:"images/Normal/Galvantula.png" },
    597: { name: "Ferroseed", type: "Grass · Steel", image:"images/Normal/Ferroseed.png" },
    598: { name: "Ferrothorn", type: "Grass · Steel", image:"images/Normal/Ferrothorn.png" },
    599: { name: "Klink", type: "Steel", image:"images/Normal/Klink.png" },
    600: { name: "Klang", type: "Steel", image:"images/Normal/Klang.png" },
    601: { name: "Klinklang", type: "Steel", image:"images/Normal/Klinklang.png" },
    602: { name: "Tynamo", type: "Electric", image:"images/Normal/Tynamo.png" },
    603: { name: "Eelektrik", type: "Electric", image:"images/Normal/Eelektrik.png" },
    604: { name: "Eelektross", type: "Electric", image:"images/Normal/Eelektross.png" },
    605: { name: "Elgyem", type: "Psychic", image:"images/Normal/Elgyem.png" },
    606: { name: "Beheeyem", type: "Psychic", image:"images/Normal/Beheeyem.png" },
    607: { name: "Litwick", type: "Ghost · Fire", image:"images/Normal/Litwick.png" },
    608: { name: "Lampent", type: "Ghost · Fire", image:"images/Normal/Lampent.png" },
    609: { name: "Chandelure", type: "Ghost · Fire", image:"images/Normal/Chandelure.png" },
    610: { name: "Axew", type: "Dragon", image:"images/Normal/Axew.png" },
    611: { name: "Fraxure", type: "Dragon", image:"images/Normal/Fraxure.png" },
    612: { name: "Haxorus", type: "Dragon", image:"images/Normal/Haxorus.png" },
    613: { name: "Cubchoo", type: "Ice", image:"images/Normal/Cubchoo.png" },
    614: { name: "Beartic", type: "Ice", image:"images/Normal/Beartic.png" },
    615: { name: "Cryogonal", type: "Ice", image:"images/Normal/Cryogonal.png" },
    616: { name: "Shelmet", type: "Bug", image:"images/Normal/Shelmet.png" },
    617: { name: "Accelgor", type: "Bug", image:"images/Normal/Accelgor.png" },
    618: { name: "Stunfisk", type: "Ground · Electric", image:"images/Normal/Stunfisk.png" },
    619: { name: "Mienfoo", type: "Fighting", image:"images/Normal/Mienfoo.png" },
    620: { name: "Mienshao", type: "Fighting", image:"images/Normal/Mienshao.png" },
    621: { name: "Druddigon", type: "Dragon", image:"images/Normal/Druddigon.png" },
    622: { name: "Golett", type: "Ground · Ghost", image:"images/Normal/Golett.png" },
    623: { name: "Golurk", type: "Ground · Ghost", image:"images/Normal/Golurk.png" },
    624: { name: "Pawniard", type: "Dark · Steel", image:"images/Normal/Pawniard.png" },
    625: { name: "Bisharp", type: "Dark · Steel", image:"images/Normal/Bisharp.png" },
    626: { name: "Bouffalant", type: "Normal", image:"images/Normal/Bouffalant.png" },
    627: { name: "Rufflet", type: "Normal · Flying", image:"images/Normal/Rufflet.png" },
    628: { name: "Braviary", type: "Normal · Flying", image:"images/Normal/Braviary.png" },
    629: { name: "Vullaby", type: "Dark · Flying", image:"images/Normal/Vullaby.png" },
    630: { name: "Mandibuzz", type: "Dark · Flying", image:"images/Normal/Mandibuzz.png" },
    631: { name: "Heatmor", type: "Fire", image:"images/Normal/Heatmor.png" },
    632: { name: "Durant", type: "Bug · Steel", image:"images/Normal/Durant.png" },
    633: { name: "Deino", type: "Dark · Dragon", image:"images/Normal/Deino.png" },
    634: { name: "Zweilous", type: "Dark · Dragon", image:"images/Normal/Zweilous.png" },
    635: { name: "Hydreigon", type: "Dark · Dragon", image:"images/Normal/Hydreigon.png" },
    636: { name: "Larvesta", type: "Bug · Fire", image:"images/Normal/Larvesta.png" },
    637: { name: "Volcarona", type: "Bug · Fire", image:"images/Normal/Volcarona.png" },
    638: { name: "Cobalion", type: "Steel · Fighting", image:"images/Normal/Cobalion.png" },
    639: { name: "Terrakion", type: "Rock · Fighting", image:"images/Normal/Terrakion.png" },
    640: { name: "Virizion", type: "Grass · Fighting", image:"images/Normal/Virizion.png" },
    641: { name: "Tornadus", type: "Flying", image:"images/Normal/Tornadus.png" },
    642: { name: "Thundurus", type: "Electric · Flying", image:"images/Normal/Thundurus.png" },
    643: { name: "Reshiram", type: "Dragon · Fire", image:"images/Normal/Reshiram.png" },
    644: { name: "Zekrom", type: "Dragon · Electric", image:"images/Normal/Zekrom.png" },
    645: { name: "Landorus", type: "Ground · Flying", image:"images/Normal/Landorus.png" },
    646: { name: "Kyurem", type: "Dragon · Ice", image:"images/Normal/Kyurem.png" },
    647: { name: "Keldeo", type: "Water · Fighting", image:"images/Normal/Keldeo.png" },
    648: { name: "Meloetta", type: "Normal · Psychic", image:"images/Normal/Meloetta.png" },
    649: { name: "Genesect", type: "Bug · Steel", image:"images/Normal/Genesect.png" }

    },

    paldea: {
    906: { name: "Sprigatito", type: "Grass", image:"images/Normal/sprigatito.png" },
    907: { name: "Floragato", type: "Grass", image:"images/Normal/floragato.png" },
    908: { name: "Meowscarada", type: "Grass · Dark", image:"images/Normal/meowscarada.png" },
    909: { name: "Fuecoco", type: "Fire", image:"images/Normal/fuecoco.png" },
    910: { name: "Crocalor", type: "Fire", image:"images/Normal/crocalor.png" },
    911: { name: "Skeledirge", type: "Fire · Ghost", image:"images/Normal/skeledirge.png" },
    912: { name: "Quaxly", type: "Water", image:"images/Normal/quaxly.png" },
    913: { name: "Quaxwell", type: "Water", image:"images/Normal/quaxwell.png" },
    914: { name: "Quaquaval", type: "Water · Fighting", image:"images/Normal/quaquaval.png" },
    915: { name: "Lechonk", type: "Normal", image:"images/Normal/lechonk.png" },
    916: { name: "Oinkologne", type: "Normal", image:"images/Normal/oinkologne.png" },
    917: { name: "Tarountula", type: "Bug", image:"images/Normal/tarountula.png" },
    918: { name: "Spidops", type: "Bug", image:"images/Normal/spidops.png" },
    919: { name: "Nymble", type: "Bug", image:"images/Normal/nymble.png" },
    920: { name: "Lokix", type: "Bug · Dark", image:"images/Normal/lokix.png" },
    921: { name: "Pawmi", type: "Electric", image:"images/Normal/pawmi.png" },
    922: { name: "Pawmo", type: "Electric · Fighting", image:"images/Normal/pawmo.png" },
    923: { name: "Pawmot", type: "Electric · Fighting", image:"images/Normal/pawmot.png" },
    924: { name: "Tandemaus", type: "Normal", image:"images/Normal/tandemaus.png" },
    925: { name: "Maushold", type: "Normal", image:"images/Normal/maushold.png" },
    926: { name: "Fidough", type: "Fairy", image:"images/Normal/fidough.png" },
    927: { name: "Dachsbun", type: "Fairy", image:"images/Normal/dachsbun.png" },
    928: { name: "Smoliv", type: "Grass · Normal", image:"images/Normal/smoliv.png" },
    929: { name: "Dolliv", type: "Grass · Normal", image:"images/Normal/dolliv.png" },
    930: { name: "Arboliva", type: "Grass · Normal", image:"images/Normal/arboliva.png" },
    931: { name: "Squawkabilly", type: "Normal · Flying", image:"images/Normal/squawkabilly.png" },
    932: { name: "Nacli", type: "Rock", image:"images/Normal/nacli.png" },
    933: { name: "Naclstack", type: "Rock", image:"images/Normal/naclstack.png" },
    934: { name: "Garganacl", type: "Rock", image:"images/Normal/garganacl.png" },
    935: { name: "Charcadet", type: "Fire", image:"images/Normal/charcadet.png" },
    936: { name: "Armarouge", type: "Fire · Psychic", image:"images/Normal/armarouge.png" },
    937: { name: "Ceruledge", type: "Fire · Ghost", image:"images/Normal/ceruledge.png" },
    938: { name: "Tadbulb", type: "Electric", image:"images/Normal/tadbulb.png" },
    939: { name: "Bellibolt", type: "Electric", image:"images/Normal/bellibolt.png" },
    940: { name: "Wattrel", type: "Electric · Flying", image:"images/Normal/wattrel.png" },
    941: { name: "Kilowattrel", type: "Electric · Flying", image:"images/Normal/kilowattrel.png" },
    942: { name: "Maschiff", type: "Dark", image:"images/Normal/maschiff.png" },
    943: { name: "Mabosstiff", type: "Dark", image:"images/Normal/mabosstiff.png" },
    944: { name: "Shroodle", type: "Poison · Normal", image:"images/Normal/shroodle.png" },
    945: { name: "Grafaiai", type: "Poison · Normal", image:"images/Normal/grafaiai.png" },
    946: { name: "Bramblin", type: "Grass · Ghost", image:"images/Normal/bramblin.png" },
    947: { name: "Brambleghast", type: "Grass · Ghost", image:"images/Normal/brambleghast.png" },
    948: { name: "Toedscool", type: "Ground · Grass", image:"images/Normal/toedscool.png" },
    949: { name: "Toedscruel", type: "Ground · Grass", image:"images/Normal/toedscruel.png" },
    950: { name: "Klawf", type: "Rock", image:"images/Normal/klawf.png" },
    951: { name: "Capsakid", type: "Grass", image:"images/Normal/capsakid.png" },
    952: { name: "Scovillain", type: "Grass · Fire", image:"images/Normal/scovillain.png" },
    953: { name: "Rellor", type: "Bug", image:"images/Normal/rellor.png" },
    954: { name: "Rabsca", type: "Bug · Psychic", image:"images/Normal/rabsca.png" },
    955: { name: "Flittle", type: "Psychic", image:"images/Normal/flittle.png" },
    956: { name: "Espathra", type: "Psychic", image:"images/Normal/espathra.png" },
    957: { name: "Tinkatink", type: "Fairy · Steel", image:"images/Normal/tinkatink.png" },
    958: { name: "Tinkatuff", type: "Fairy · Steel", image:"images/Normal/tinkatuff.png" },
    959: { name: "Tinkaton", type: "Fairy · Steel", image:"images/Normal/tinkaton.png" },
    960: { name: "Wiglett", type: "Water", image:"images/Normal/wiglett.png" },
    961: { name: "Wugtrio", type: "Water", image:"images/Normal/wugtrio.png" },
    962: { name: "Bombirdier", type: "Flying · Dark", image:"images/Normal/bombirdier.png" },
    963: { name: "Finizen", type: "Water", image:"images/Normal/finizen.png" },
    964: { name: "Palafin", type: "Water", image:"images/Normal/palafin.png" },
    965: { name: "Varoom", type: "Steel · Poison", image:"images/Normal/varoom.png" },
    966: { name: "Revavroom", type: "Steel · Poison", image:"images/Normal/revavroom.png" },
    967: { name: "Cyclizar", type: "Dragon · Normal", image:"images/Normal/cyclizar.png" },
    968: { name: "Orthworm", type: "Steel", image:"images/Normal/orthworm.png" },
    969: { name: "Glimmet", type: "Rock · Poison", image:"images/Normal/glimmet.png" },
    970: { name: "Glimmora", type: "Rock · Poison", image:"images/Normal/glimmora.png" },
    971: { name: "Greavard", type: "Ghost", image:"images/Normal/greavard.png" },
    972: { name: "Houndstone", type: "Ghost", image:"images/Normal/houndstone.png" },
    973: { name: "Flamigo", type: "Flying · Fighting", image:"images/Normal/flamigo.png" },
    974: { name: "Cetoddle", type: "Ice", image:"images/Normal/cetoddle.png" },
    975: { name: "Cetitan", type: "Ice", image:"images/Normal/cetitan.png" },
    976: { name: "Veluza", type: "Water · Psychic", image:"images/Normal/veluza.png" },
    977: { name: "Dondozo", type: "Water", image:"images/Normal/dondozo.png" },
    978: { name: "Tatsugiri", type: "Dragon · Water", image:"images/Normal/tatsugiri.png" },
    979: { name: "Annihilape", type: "Fighting · Ghost", image:"images/Normal/annihilape.png" },
    980: { name: "Clodsire", type: "Poison · Ground", image:"images/Normal/clodsire.png" },
    981: { name: "Farigiraf", type: "Normal · Psychic", image:"images/Normal/farigiraf.png" },
    982: { name: "Dudunsparce", type: "Normal", image:"images/Normal/dudunsparce.png" },
    983: { name: "Kingambit", type: "Dark · Steel", image:"images/Normal/kingambit.png" },
    984: { name: "Great Tusk", type: "Ground · Fighting", image:"images/Normal/great tusk.png" },
    985: { name: "Scream Tail", type: "Fairy · Psychic", image:"images/Normal/scream tail.png" },
    986: { name: "Brute Bonnet", type: "Grass · Dark", image:"images/Normal/brute bonnet.png" },
    987: { name: "Flutter Mane", type: "Ghost · Fairy", image:"images/Normal/flutter mane.png" },
    988: { name: "Slither Wing", type: "Bug · Fighting", image:"images/Normal/slither wing.png" },
    989: { name: "Sandy Shocks", type: "Electric · Ground", image:"images/Normal/sandy shocks.png" },
    990: { name: "Iron Treads", type: "Ground · Steel", image:"images/Normal/iron treads.png" },
    991: { name: "Iron Bundle", type: "Ice · Water", image:"images/Normal/iron bundle.png" },
    992: { name: "Iron Hands", type: "Fighting · Electric", image:"images/Normal/iron hands.png" },
    993: { name: "Iron Jugulis", type: "Dark · Flying", image:"images/Normal/iron jugulis.png" },
    994: { name: "Iron Moth", type: "Fire · Poison", image:"images/Normal/iron moth.png" },
    995: { name: "Iron Thorns", type: "Rock · Electric", image:"images/Normal/iron thorns.png" },
    996: { name: "Frigibax", type: "Dragon · Ice", image:"images/Normal/frigibax.png" },
    997: { name: "Arctibax", type: "Dragon · Ice", image:"images/Normal/arctibax.png" },
    998: { name: "Baxcalibur", type: "Dragon · Ice", image:"images/Normal/baxcalibur.png" },
    999: { name: "Gimmighoul", type: "Ghost", image:"images/Normal/gimmighoul.png" },
    1000: { name: "Gholdengo", type: "Steel · Ghost", image:"images/Normal/gholdengo.png" },
    1001: { name: "Wo-Chien", type: "Dark · Grass", image:"images/Normal/wo-chien.png" },
    1002: { name: "Chien-Pao", type: "Dark · Ice", image:"images/Normal/chien-pao.png" },
    1003: { name: "Ting-Lu", type: "Dark · Ground", image:"images/Normal/ting-lu.png" },
    1004: { name: "Chi-Yu", type: "Dark · Fire", image:"images/Normal/chi-yu.png" },
    1005: { name: "Roaring Moon", type: "Dragon · Dark", image:"images/Normal/roaring moon.png" },
    1006: { name: "Iron Valiant", type: "Fairy · Fighting", image:"images/Normal/iron valiant.png" },
    1007: { name: "Koraidon", type: "Dragon · Fighting", image:"images/Normal/koraidon.png" },
    1008: { name: "Miraidon", type: "Dragon · Electric", image:"images/Normal/miraidon.png" },
    1009: { name: "Walking Wake", type: "Dragon · Water", image:"images/Normal/walking_wake.png" },
    1010: { name: "Iron Leaves", type: "Grass · Psychic", image:"images/Normal/iron leaves.png" },
    1011: { name: "Dipplin", type: "Grass · Dragon", image:"images/Normal/dipplin.png" },
    1012: { name: "Poltchageist", type: "Grass · Ghost", image:"images/Normal/poltchageist.png" },
    1013: { name: "Sinistcha", type: "Grass · Ghost", image:"images/Normal/sinistcha.png" },
    1014: { name: "Okidogi", type: "Poison · Fighting", image:"images/Normal/okidogi.png" },
    1015: { name: "Munkidori", type: "Poison · Psychic", image:"images/Normal/munkidori.png" },
    1016: { name: "Fezandipiti", type: "Poison · Fairy", image:"images/Normal/fezandipiti.png" },
    1017: { name: "Ogerpon", type: "Grass", image:"images/Normal/ogerpon.png" },
    1018: { name: "Archaludon", type: "Steel · Dragon", image:"images/Normal/archalundon.png" },
    1019: { name: "Hydrapple", type: "Grass · Dragon", image:"images/Normal/hydrapple.png" },
    1020: { name: "Gouging Fire", type: "Fire · Dragon", image:"images/Normal/gouging fire.png" },
    1021: { name: "Raging Bolt", type: "Electric · Dragon", image:"images/Normal/raging bolt.png" },
    1022: { name: "Iron Boulder", type: "Rock · Psychic", image:"images/Normal/iron boulder.png" },
    1023: { name: "Iron Crown", type: "Steel · Psychic", image:"images/Normal/iron crown.png" },
    1024: { name: "Terapagos", type: "Normal", image:"images/Normal/terapagos.png" },
    1025: { name: "Pecharunt", type: "Poison · Ghost", image:"images/Normal/pecharunt.png" }
    },




    // Add other multidexs here
};


const gameData = {
    kanto: [
        { id: 1, name: "Pokémon Red", image:"images/games/kanto/Red.png",pokemon: generateRange(1, 151) },
        { id: 2, name: "Pokémon Blue", image:"images/games/kanto/Blue.png", pokemon: generateRange(1, 151) }, // Example with Bulbasaur
        { id: 3, name: "Pokémon Yellow", image:"images/games/kanto/Yellow.png", pokemon: generateRange(1, 151) },
        { id: 4, name: "Pokémon Fire Red", image:"images/games/kanto/FireRed.png",pokemon: generateRange(1, 151) },
        { id: 5, name: "Pokémon Leaf Green", image:"images/games/kanto/LeafGreen.png", pokemon: generateRange(1, 151) }, // Example with Bulbasaur
        { id: 6, name: "Pokémon Lets Go Eevee", image:"images/games/kanto/LetsGoEevee.png", pokemon: generateRange(1, 151) },
        { id: 7, name: "Pokémon Lets Go Pikachu", image:"images/games/kanto/LetsGoPikachu.png",pokemon: generateRange(1, 151) },
    ],
    johto: [
        { id: 1, name: "Pokémon Crystal", image:"images/games/jhoto/crystal.png",pokemon: generateRange(152, 251) },
        { id: 2, name: "Pokémon Gold", image:"images/games/jhoto/Gold.png", pokemon: generateRange(152, 251) },
        { id: 3, name: "Pokémon Heart Gold", image:"images/games/jhoto/HeartGold.png", pokemon: generateRange(152, 251) },
        { id: 4, name: "Pokémon Silver", image:"images/games/jhoto/Silver.png", pokemon: generateRange(152, 251) },
        { id: 5, name: "Pokémon Soul Silver", image:"images/games/jhoto/SoulSilver.png", pokemon: generateRange(152, 251) },
    ],
    hoenn: [
        { id: 1, name: "Pokémon Emerald", image:"images/games/hoenn/Emerald.png",pokemon: generateRange(252, 386) },
        { id: 2, name: "Pokémon Ruby", image:"images/games/hoenn/Ruby.png", pokemon: generateRange(252, 386) },
        { id: 3, name: "Pokémon Sapphire", image:"images/games/hoenn/Sapphire.png", pokemon: generateRange(252, 386) },
        { id: 4, name: "Pokémon Omega Ruby", image:"images/games/hoenn/OmegaRuby.png", pokemon: generateRange(252, 386) },
        { id: 5, name: "Pokémon Alpha Sapphire", image:"images/games/hoenn/AlphaSapphire.png", pokemon: generateRange(252, 386) },
    ],
    sinnoh: [
        { id: 1, name: "Pokémon Arceus", image:"images/games/sinnoh/Arceus.png",pokemon: generateRange(387, 493) },
        { id: 2, name: "Pokémon Brilliant Diamond", image:"images/games/sinnoh/BrilliantDiamond.png", pokemon: generateRange(387, 493) },
        { id: 3, name: "Pokémon Diamond", image:"images/games/sinnoh/Diamond.png", pokemon: generateRange(387, 493) },
        { id: 4, name: "Pokémon Shining Pearl", image:"images/games/sinnoh/ShiningPearl.png", pokemon: generateRange(387, 493) },
        { id: 5, name: "Pokémon Pearl", image:"images/games/sinnoh/Pearl.png", pokemon: generateRange(387, 493) },
        { id: 6, name: "Pokémon Platinum", image:"images/games/sinnoh/Platinum.png", pokemon: generateRange(387, 493) },
    ],
    unova: [
        { id: 1, name: "Pokémon Black", image:"images/games/unova/Black.png",pokemon: generateRange(387, 493) },
        { id: 2, name: "Pokémon Brilliant Diamond", image:"images/games/sinnoh/BrilliantDiamond.png", pokemon: generateRange(387, 493) },
        { id: 3, name: "Pokémon Diamond", image:"images/games/sinnoh/Diamond.png", pokemon: generateRange(387, 493) },
        { id: 4, name: "Pokémon Shining Pearl", image:"images/games/sinnoh/ShiningPearl.png", pokemon: generateRange(387, 493) },
        { id: 5, name: "Pokémon Pearl", image:"images/games/sinnoh/Pearl.png", pokemon: generateRange(387, 493) },
        { id: 6, name: "Pokémon Platinum", image:"images/games/sinnoh/Platinum.png", pokemon: generateRange(387, 493) },
    ]
};


function selectmultidex(multidex) {
    document.getElementById('multidex-selection').classList.add('hidden');
    loadGames(multidex);
}

function loadGames(multidex) {
    const gamesGrid = document.getElementById("games");
    const games = gameData[multidex];

    if (!games) return;

    gamesGrid.innerHTML = ''; // Clear existing games
    document.getElementById('games-section').classList.remove('hidden'); // Show the games section

    // Move this inside the loadGames function
    games.forEach(game => {
        const gameBox = document.createElement("div");
        gameBox.className = "game-box";
        gameBox.innerHTML = `
            <div class="game-name">${game.name}</div>
            <img src="${game.image}" alt="${game.name}" class="game-image"/>
        `;
        gameBox.onclick = () => loadPokedexForGame(multidex, game.pokemon, game.id); // Pass gameId
        gamesGrid.appendChild(gameBox);
    });
}


// Update loadPokedexForGame to accept gameId parameter
function loadPokedexForGame(multidex, pokemonIds, gameId) {
    const pokemonGrid = document.getElementById("pokedex");
    pokemonGrid.innerHTML = '';
    document.getElementById('pokedex-section').classList.remove('hidden');

    pokemonIds.forEach(id => {
        const pokemon = pokedexData[multidex][id];
        const isCaught = localStorage.getItem(`${multidex}-${gameId}-${id}`) === 'true';

        const pokemonBox = document.createElement("div");
        pokemonBox.className = "pokemon-box";
        pokemonBox.innerHTML = `
            <div class="pokemon-number">#${id}</div>
            <div class="pokemon-name">${isCaught ? pokemon.name.charAt(0).toUpperCase() + pokemon.name.slice(1) : '???'}</div>
            <div class="pokemon-status">${isCaught ? 'Caught ✔️' : 'Not Caught ❌'}</div>
            ${isCaught ? `<div class="pokemon-type">Type: ${pokemon.type}</div>` : ''}
            <img src="${isCaught ? pokemon.image : 'path/to/placeholder-image.png'}" alt="${isCaught ? pokemon.name : ''}">
        `;
        
        pokemonBox.onclick = () => toggleCaughtStatus(multidex, id, gameId);
        pokemonGrid.appendChild(pokemonBox);
    });
}

// Modify toggleCaughtStatus to use gameId
function toggleCaughtStatus(multidex, number, gameId) {
    const isCaught = localStorage.getItem(`${multidex}-${gameId}-${number}`) === 'true';
    localStorage.setItem(`${multidex}-${gameId}-${number}`, !isCaught);
    
    loadPokedexForGame(multidex, Object.keys(pokedexData[multidex]).map(Number), gameId); // Re-load with gameId
}


function goBack() {
    document.getElementById('pokedex-section').classList.add('hidden');
    document.getElementById('games-section').classList.add('hidden');
    document.getElementById('multidex-selection').classList.remove('hidden');
}

