const pokedexData = {
    national: {
    1: { name: "bulbasaur", type: "Grass/Poison", image:"images/Normal/bulbasaur.png" },
    2: { name: "ivysaur", type: "Grass/Poison", image:"images/Normal/ivysaur.png" },
    3: { name: "venusaur", type: "Grass/Poison", image:"images/Normal/venusaur.png" },
    4: { name: "charmander", type: "Fire", image:"images/Normal/charmander.png" },
    5: { name: "charmeleon", type: "Fire", image:"images/Normal/charmeleon.png" },
    6: { name: "charizard", type: "Fire/Flying", image:"images/Normal/charizard.png" },
    7: { name: "squirtle", type: "Water", image:"images/Normal/squirtle.png" },
    8: { name: "wartortle", type: "Water", image:"images/Normal/wartortle.png" },
    9: { name: "blastoise", type: "Water", image:"images/Normal/blastoise.png" },
    10: { name: "caterpie", type: "Bug", image:"images/Normal/caterpie.png" },
    11: { name: "metapod", type: "Bug", image:"images/Normal/metapod.png" },
    12: { name: "butterfree", type: "Bug/Flying", image:"images/Normal/butterfree.png" },
    13: { name: "weedle", type: "Bug/Poison", image:"images/Normal/weedle.png" },
    14: { name: "kakuna", type: "Bug/Poison", image:"images/Normal/kakuna.png" },
    15: { name: "beedrill", type: "Bug/Poison", image:"images/Normal/beedrill.png" },
    16: { name: "pidgey", type: "Normal/Flying", image:"images/Normal/pidgey.png" },
    17: { name: "pidgeotto", type: "Normal/Flying", image:"images/Normal/pidgeotto.png" },
    18: { name: "pidgeot", type: "Normal/Flying", image:"images/Normal/pidgeot.png" },
    19: { name: "rattata", type: "Normal", image:"images/Normal/rattata.png" },
    20: { name: "raticate", type: "Normal", image:"images/Normal/raticate.png" },
    21: { name: "spearow", type: "Normal/Flying", image:"images/Normal/spearow.png" },
    22: { name: "fearow", type: "Normal/Flying", image:"images/Normal/fearow.png" },
    23: { name: "ekans", type: "Poison", image:"images/Normal/ekans.png" },
    24: { name: "arbok", type: "Poison", image:"images/Normal/arbok.png" },
    25: { name: "pikachu", type: "Electric", image:"images/Normal/pikachu.png" },
    26: { name: "raichu", type: "Electric", image:"images/Normal/raichu.png" },
    27: { name: "sandshrew", type: "Ground", image:"images/Normal/sandshrew.png" },
    28: { name: "sandslash", type: "Ground", image:"images/Normal/sandslash.png" },
    29: { name: "nidoran-♀", type: "Poison", image:"images/Normal/nidoran-♀.png" },
    30: { name: "nidorina", type: "Poison", image:"images/Normal/nidorina.png" },
    31: { name: "nidoqueen", type: "Poison/Ground", image:"images/Normal/nidoqueen.png" },
    32: { name: "nidoran-♂", type: "Poison", image:"images/Normal/nidoran-♂.png" },
    33: { name: "nidorino", type: "Poison", image:"images/Normal/nidorino.png" },
    34: { name: "nidoking", type: "Poison/Ground", image:"images/Normal/nidoking.png" },
    35: { name: "clefairy", type: "Fairy", image:"images/Normal/clefairy.png" },
    36: { name: "clefable", type: "Fairy", image:"images/Normal/clefable.png" },
    37: { name: "vulpix", type: "Fire", image:"images/Normal/vulpix.png" },
    38: { name: "ninetales", type: "Fire", image:"images/Normal/ninetales.png" },
    39: { name: "jigglypuff", type: "Normal/Fairy", image:"images/Normal/jigglypuff.png" },
    40: { name: "wigglytuff", type: "Normal/Fairy", image:"images/Normal/wigglytuff.png" },
    41: { name: "zubat", type: "Poison/Flying", image:"images/Normal/zubat.png" },
    42: { name: "golbat", type: "Poison/Flying", image:"images/Normal/golbat.png" },
    43: { name: "oddish", type: "Grass/Poison", image:"images/Normal/oddish.png" },
    44: { name: "gloom", type: "Grass/Poison", image:"images/Normal/gloom.png" },
    45: { name: "vileplume", type: "Grass/Poison", image:"images/Normal/vileplume.png" },
    46: { name: "paras", type: "Bug/Grass", image:"images/Normal/paras.png" },
    47: { name: "parasect", type: "Bug/Grass", image:"images/Normal/parasect.png" },
    48: { name: "venonat", type: "Bug/Poison", image:"images/Normal/venonat.png" },
    49: { name: "venomoth", type: "Bug/Poison", image:"images/Normal/venomoth.png" },
    50: { name: "diglett", type: "Ground", image:"images/Normal/diglett.png" },
    51: { name: "dugtrio", type: "Ground", image:"images/Normal/dugtrio.png" },
    52: { name: "meowth", type: "Normal", image:"images/Normal/meowth.png" },
    53: { name: "persian", type: "Normal", image:"images/Normal/persian.png" },
    54: { name: "psyduck", type: "Water", image:"images/Normal/psyduck.png" },
    55: { name: "golduck", type: "Water", image:"images/Normal/golduck.png" },
    56: { name: "mankey", type: "Fighting", image:"images/Normal/mankey.png" },
    57: { name: "primeape", type: "Fighting", image:"images/Normal/primeape.png" },
    58: { name: "growlithe", type: "Fire", image:"images/Normal/growlithe.png" },
    59: { name: "arcanine", type: "Fire", image:"images/Normal/arcanine.png" },
    60: { name: "poliwag", type: "Water", image:"images/Normal/poliwag.png" },
    61: { name: "poliwhirl", type: "Water", image:"images/Normal/poliwhirl.png" },
    62: { name: "poliwrath", type: "Water/Fighting", image:"images/Normal/poliwrath.png" },
    63: { name: "abra", type: "Psychic", image:"images/Normal/abra.png" },
    64: { name: "kadabra", type: "Psychic", image:"images/Normal/kadabra.png" },
    65: { name: "alakazam", type: "Psychic", image:"images/Normal/alakazam.png" },
    66: { name: "machop", type: "Fighting", image:"images/Normal/machop.png" },
    67: { name: "machoke", type: "Fighting", image:"images/Normal/machoke.png" },
    68: { name: "machamp", type: "Fighting", image:"images/Normal/machamp.png" },
    69: { name: "bellsprout", type: "Grass/Poison", image:"images/Normal/bellsprout.png" },
    70: { name: "weepinbell", type: "Grass/Poison", image:"images/Normal/weepinbell.png" },
    71: { name: "victreebel", type: "Grass/Poison", image:"images/Normal/victreebel.png" },
    72: { name: "tentacool", type: "Water/Poison", image:"images/Normal/tentacool.png" },
    73: { name: "tentacruel", type: "Water/Poison", image:"images/Normal/tentacruel.png" },
    74: { name: "geodude", type: "Rock/Ground", image:"images/Normal/geodude.png" },
    75: { name: "graveler", type: "Rock/Ground", image:"images/Normal/graveler.png" },
    76: { name: "golem", type: "Rock/Ground", image:"images/Normal/golem.png" },
    77: { name: "ponyta", type: "Fire", image:"images/Normal/ponyta.png" },
    78: { name: "rapidash", type: "Fire", image:"images/Normal/rapidash.png" },
    79: { name: "slowpoke", type: "Water/Psychic", image:"images/Normal/slowpoke.png" },
    80: { name: "slowbro", type: "Water/Psychic", image:"images/Normal/slowbro.png" },
    81: { name: "magnemite", type: "Electric/Steel", image:"images/Normal/magnemite.png" },
    82: { name: "magneton", type: "Electric/Steel", image:"images/Normal/magneton.png" },
    83: { name: "farfetch'd", type: "Normal/Flying", image:"images/Normal/farfetchd.png" },
    84: { name: "doduo", type: "Normal/Flying", image:"images/Normal/doduo.png" },
    85: { name: "dodrio", type: "Normal/Flying", image:"images/Normal/dodrio.png" },
    86: { name: "seel", type: "Water", image:"images/Normal/seel.png" },
    87: { name: "dewgong", type: "Water/Ice", image:"images/Normal/dewgong.png" },
    88: { name: "grimer", type: "Poison", image:"images/Normal/grimer.png" },
    89: { name: "muk", type: "Poison", image:"images/Normal/muk.png" },
    90: { name: "shellder", type: "Water", image:"images/Normal/shellder.png" },
    91: { name: "cloyster", type: "Water/Ice", image:"images/Normal/cloyster.png" },
    92: { name: "gastly", type: "Ghost/Poison", image:"images/Normal/gastly.png" },
    93: { name: "haunter", type: "Ghost/Poison", image:"images/Normal/haunter.png" },
    94: { name: "gengar", type: "Ghost/Poison", image:"images/Normal/gengar.png" },
    95: { name: "onix", type: "Rock/Ground", image:"images/Normal/onix.png" },
    96: { name: "drowzee", type: "Psychic", image:"images/Normal/drowzee.png" },
    97: { name: "hypno", type: "Psychic", image:"images/Normal/hypno.png" },
    98: { name: "krabby", type: "Water", image:"images/Normal/krabby.png" },
    99: { name: "kingler", type: "Water", image:"images/Normal/kingler.png" },
    100: { name: "voltorb", type: "Electric", image:"images/Normal/voltorb.png" },
    101: { name: "electrode", type: "Electric", image:"images/Normal/electrode.png" },
    102: { name: "exeggcute", type: "Grass/Psychic", image:"images/Normal/exeggcute.png" },
    103: { name: "exeggutor", type: "Grass/Psychic", image:"images/Normal/exeggutor.png" },
    104: { name: "cubone", type: "Ground", image:"images/Normal/cubone.png" },
    105: { name: "marowak", type: "Ground", image:"images/Normal/marowak.png" },
    106: { name: "hitmonlee", type: "Fighting", image:"images/Normal/hitmonlee.png" },
    107: { name: "hitmonchan", type: "Fighting", image:"images/Normal/hitmonchan.png" },
    108: { name: "lickitung", type: "Normal", image:"images/Normal/lickitung.png" },
    109: { name: "koffing", type: "Poison", image:"images/Normal/koffing.png" },
    110: { name: "weezing", type: "Poison", image:"images/Normal/weezing.png" },
    111: { name: "rhyhorn", type: "Ground/Rock", image:"images/Normal/rhyhorn.png" },
    112: { name: "rhydon", type: "Ground/Rock", image:"images/Normal/rhydon.png" },
    113: { name: "chansey", type: "Normal", image:"images/Normal/chansey.png" },
    114: { name: "tangela", type: "Grass", image:"images/Normal/tangela.png" },
    115: { name: "kangaskhan", type: "Normal", image:"images/Normal/kangaskhan.png" },
    116: { name: "horsea", type: "Water", image:"images/Normal/horsea.png" },
    117: { name: "seadra", type: "Water", image:"images/Normal/seadra.png" },
    118: { name: "goldeen", type: "Water", image:"images/Normal/goldeen.png" },
    119: { name: "seaking", type: "Water", image:"images/Normal/seaking.png" },
    120: { name: "staryu", type: "Water", image:"images/Normal/staryu.png" },
    121: { name: "starmie", type: "Water/Psychic", image:"images/Normal/starmie.png" },
    122: { name: "mr-mime", type: "Psychic/Fairy", image:"images/Normal/mr-mime.png" },
    123: { name: "scyther", type: "Bug/Flying", image:"images/Normal/scyther.png" },
    124: { name: "jynx", type: "Ice/Psychic", image:"images/Normal/jynx.png" },
    125: { name: "electabuzz", type: "Electric", image:"images/Normal/electabuzz.png" },
    126: { name: "magmar", type: "Fire", image:"images/Normal/magmar.png" },
    127: { name: "pinsir", type: "Bug", image:"images/Normal/pinsir.png" },
    128: { name: "tauros", type: "Normal", image:"images/Normal/tauros.png" },
    129: { name: "magikarp", type: "Water", image:"images/Normal/magikarp.png" },
    130: { name: "gyarados", type: "Water/Flying", image:"images/Normal/gyarados.png" },
    131: { name: "lapras", type: "Water/Ice", image:"images/Normal/lapras.png" },
    132: { name: "ditto", type: "Normal", image:"images/Normal/ditto.png" },
    133: { name: "eevee", type: "Normal", image:"images/Normal/eevee.png" },
    134: { name: "vaporeon", type: "Water", image:"images/Normal/vaporeon.png" },
    135: { name: "jolteon", type: "Electric", image:"images/Normal/jolteon.png" },
    136: { name: "flareon", type: "Fire", image:"images/Normal/flareon.png" },
    137: { name: "porygon", type: "Normal", image:"images/Normal/porygon.png" },
    138: { name: "omanyte", type: "Rock/Water", image:"images/Normal/omanyte.png" },
    139: { name: "omastar", type: "Rock/Water", image:"images/Normal/omastar.png" },
    140: { name: "kabuto", type: "Rock/Water", image:"images/Normal/kabuto.png" },
    141: { name: "kabutops", type: "Rock/Water", image:"images/Normal/kabutops.png" },
    142: { name: "aerodactyl", type: "Rock/Flying", image:"images/Normal/aerodactyl.png" },
    143: { name: "snorlax", type: "Normal", image:"images/Normal/snorlax.png" },
    144: { name: "articuno", type: "Ice/Flying", image:"images/Normal/articuno.png" },
    145: { name: "zapdos", type: "Electric/Flying", image:"images/Normal/zapdos.png" },
    146: { name: "moltres", type: "Fire/Flying", image:"images/Normal/moltres.png" },
    147: { name: "dratini", type: "Dragon", image:"images/Normal/dratini.png" },
    148: { name: "dragonair", type: "Dragon", image:"images/Normal/dragonair.png" },
    149: { name: "dragonite", type: "Dragon/Flying", image:"images/Normal/dragonite.png" },
    150: { name: "mewtwo", type: "Psychic", image:"images/Normal/mewtwo.png" },
    151: { name: "mew", type: "Psychic", image:"images/Normal/mew.png" },
    152: {name: "Chikorita", type: "Grass", image:"images/Normal/chikorita.png" },
    153: {name: "Bayleef", type: "Grass", image:"images/Normal/bayleef.png" },
    154: {name: "Meganium", type: "Grass", image:"images/Normal/meganium.png" },
    155: {name: "Cyndaquil", type: "Fire", image:"images/Normal/cyndaquil.png" },
    156: {name: "Quilava", type: "Fire", image:"images/Normal/quilava.png" },
    157: {name: "Typhlosion", type: "Fire", image:"images/Normal/typhlosion.png" },
    158: {name: "Totodile", type: "Water", image:"images/Normal/totodile.png" },
    159: {name: "Croconaw", type: "Water", image:"images/Normal/croconaw.png" },
    160: {name: "Feraligatr", type: "Water", image:"images/Normal/feraligatr.png" },
    161: {name: "Sentret", type: "Normal", image:"images/Normal/sentret.png" },
    162: {name: "Furret", type: "Normal", image:"images/Normal/furret.png" },
    163: {name: "Hoothoot", type: "Normal/Flying", image:"images/Normal/hoothoot.png" },
    164: {name: "Noctowl", type: "Normal/Flying", image:"images/Normal/noctowl.png" },
    165: {name: "Ledyba", type: "Bug/Flying", image:"images/Normal/ledyba.png" },
    166: {name: "Ledian", type: "Bug/Flying", image:"images/Normal/ledian.png" },
    167: {name: "Spinarak", type: "Bug/Poison", image:"images/Normal/spinarak.png" },
    168: {name: "Ariados", type: "Bug/Poison", image:"images/Normal/ariados.png" },
    169: {name: "Crobat", type: "Poison/Flying", image:"images/Normal/crobat.png" },
    170: {name: "Chinchou", type: "Water/Electric", image:"images/Normal/chinchou.png" },
    171: {name: "Lanturn", type: "Water/Electric", image:"images/Normal/lanturn.png" },
    172: {name: "Pichu", type: "Electric", image:"images/Normal/pichu.png" },
    173: {name: "Cleffa", type: "Fairy", image:"images/Normal/cleffa.png" },
    174: {name: "Igglybuff", type: "Normal/Fairy", image:"images/Normal/igglybuff.png" },
    175: {name: "Togepi", type: "Fairy", image:"images/Normal/togepi.png" },
    176: {name: "Togetic", type: "Fairy/Flying", image:"images/Normal/togetic.png" },
    177: {name: "Natu", type: "Psychic/Flying", image:"images/Normal/natu.png" },
    178: {name: "Xatu", type: "Psychic/Flying", image:"images/Normal/xatu.png" },
    179: {name: "Mareep", type: "Electric", image:"images/Normal/mareep.png" },
    180: {name: "Flaaffy", type: "Electric", image:"images/Normal/flaaffy.png" },
    181: {name: "Ampharos", type: "Electric", image:"images/Normal/ampharos.png" },
    182: {name: "Bellossom", type: "Grass", image:"images/Normal/bellossom.png" },
    183: {name: "Marill", type: "Water/Fairy", image:"images/Normal/marill.png" },
    184: {name: "Azumarill", type: "Water/Fairy", image:"images/Normal/azumarill.png" },
    185: {name: "Sudowoodo", type: "Rock", image:"images/Normal/sudowoodo.png" },
    186: {name: "Politoed", type: "Water", image:"images/Normal/politoed.png" },
    187: {name: "Hoppip", type: "Grass/Flying", image:"images/Normal/hoppip.png" },
    188: {name: "Skiploom", type: "Grass/Flying", image:"images/Normal/skiploom.png" },
    189: {name: "Jumpluff", type: "Grass/Flying", image:"images/Normal/jumpluff.png" },
    190: {name: "Aipom", type: "Normal", image:"images/Normal/aipom.png" },
    191: {name: "Sunkern", type: "Grass", image:"images/Normal/sunkern.png" },
    192: {name: "Sunflora", type: "Grass", image:"images/Normal/sunflora.png" },
    193: {name: "Yanma", type: "Bug/Flying", image:"images/Normal/yanma.png" },
    194: {name: "Wooper", type: "Water/Ground", image:"images/Normal/wooper.png" },
    195: {name: "Quagsire", type: "Water/Ground", image:"images/Normal/quagsire.png" },
    196: {name: "Espeon", type: "Psychic", image:"images/Normal/espeon.png" },
    197: {name: "Umbreon", type: "Dark", image:"images/Normal/umbreon.png" },
    198: {name: "Murkrow", type: "Dark/Flying", image:"images/Normal/murkrow.png" },
    199: {name: "Slowking", type: "Water/Psychic", image:"images/Normal/slowking.png" },
    200: {name: "Misdreavus", type: "Ghost", image:"images/Normal/misdreavus.png" },
    201: {name: "Unown", type: "Psychic", image:"images/Normal/unown.png" },
    202: {name: "Wobbuffet", type: "Psychic", image:"images/Normal/wobbuffet.png" },
    203: {name: "Girafarig", type: "Normal/Psychic", image:"images/Normal/girafarig.png" },
    204: {name: "Pineco", type: "Bug", image:"images/Normal/pineco.png" },
    205: {name: "Forretress", type: "Bug/Steel", image:"images/Normal/forretress.png" },
    206: {name: "Dunsparce", type: "Normal", image:"images/Normal/dunsparce.png" },
    207: {name: "Gligar", type: "Ground/Flying", image:"images/Normal/gligar.png" },
    208: {name: "Steelix", type: "Steel/Ground", image:"images/Normal/steelix.png" },
    209: {name: "Snubbull", type: "Fairy", image:"images/Normal/snubbull.png" },
    210: {name: "Granbull", type: "Fairy", image:"images/Normal/granbull.png" },
    211: {name: "Qwilfish", type: "Water/Poison", image:"images/Normal/qwilfish.png" },
    212: {name: "Scizor", type: "Bug/Steel", image:"images/Normal/scizor.png" },
    213: {name: "Shuckle", type: "Bug/Rock", image:"images/Normal/shuckle.png" },
    214: {name: "Heracross", type: "Bug/Fighting", image:"images/Normal/heracross.png" },
    215: {name: "Sneasel", type: "Dark/Ice", image:"images/Normal/sneasel.png" },
    216: {name: "Teddiursa", type: "Normal", image:"images/Normal/teddiursa.png" },
    217: {name: "Ursaring", type: "Normal", image:"images/Normal/ursaring.png" },
    218: {name: "Slugma", type: "Fire", image:"images/Normal/slugma.png" },
    219: {name: "Magcargo", type: "Fire/Rock", image:"images/Normal/magcargo.png" },
    220: {name: "Swinub", type: "Ice/Ground", image:"images/Normal/swinub.png" },
    221: {name: "Piloswine", type: "Ice/Ground", image:"images/Normal/piloswine.png" },
    222: {name: "Corsola", type: "Water/Rock", image:"images/Normal/corsola.png" },
    223: {name: "Remoraid", type: "Water", image:"images/Normal/remoraid.png" },
    224: {name: "Octillery", type: "Water", image:"images/Normal/octillery.png" },
    225: {name: "Delibird", type: "Ice/Flying", image:"images/Normal/delibird.png" },
    226: {name: "Mantine", type: "Water/Flying", image:"images/Normal/mantine.png" },
    227: {name: "Skarmory", type: "Steel/Flying", image:"images/Normal/skarmory.png" },
    228: {name: "Houndour", type: "Dark/Fire", image:"images/Normal/houndour.png" },
    229: {name: "Houndoom", type: "Dark/Fire", image:"images/Normal/houndoom.png" },
    230: {name: "Kingdra", type: "Water/Dragon", image:"images/Normal/kingdra.png" },
    231: {name: "Phanpy", type: "Ground", image:"images/Normal/phanpy.png" },
    232: {name: "Donphan", type: "Ground", image:"images/Normal/donphan.png" },
    233: {name: "Porygon2", type: "Normal", image:"images/Normal/porygon2.png" },
    234: {name: "Stantler", type: "Normal", image:"images/Normal/stantler.png" },
    235: {name: "Smeargle", type: "Normal", image:"images/Normal/smeargle.png" },
    236: {name: "Tyrogue", type: "Fighting", image:"images/Normal/tyrogue.png" },
    237: {name: "Hitmontop", type: "Fighting", image:"images/Normal/hitmontop.png" },
    238: {name: "Smoochum", type: "Ice/Psychic", image:"images/Normal/smoochum.png" },
    239: {name: "Elekid", type: "Electric", image:"images/Normal/elekid.png" },
    240: {name: "Magby", type: "Fire", image:"images/Normal/magby.png" },
    241: {name: "Miltank", type: "Normal", image:"images/Normal/miltank.png" },
    242: {name: "Blissey", type: "Normal", image:"images/Normal/blissey.png" },
    243: {name: "Raikou", type: "Electric", image:"images/Normal/raikou.png" },
    244: {name: "Entei", type: "Fire", image:"images/Normal/entei.png" },
    245: {name: "Suicune", type: "Water", image:"images/Normal/suicune.png" },
    246: {name: "Larvitar", type: "Rock/Ground", image:"images/Normal/larvitar.png" },
    247: {name: "Pupitar", type: "Rock/Ground", image:"images/Normal/pupitar.png" },
    248: {name: "Tyranitar", type: "Rock/Dark", image:"images/Normal/tyranitar.png" },
    249: {name: "Lugia", type: "Psychic/Flying", image:"images/Normal/lugia.png" },
    250: {name: "Ho-Oh", type: "Fire/Flying", image:"images/Normal/Ho-Oh.png" },
    251: {name: "Celebi", type: "Psychic/Grass", image:"images/Normal/celebi.png" },
    252: {name: "Treecko", type: "Grass", image:"images/Normal/treecko.png" },
    253: {name: "Grovyle", type: "Grass", image:"images/Normal/grovyle.png" },
    254: {name: "Sceptile",type: "Grass",image:"images/Normal/sceptile.png"},
    255: {name: "Torchic",type: "Fire",image:"images/Normal/torchic.png"},
    256: {name: "Combusken",type: "Fire · Fighting",image:"images/Normal/combusken.png"},
    257: {name: "Blaziken",type: "Fire · Fighting",image:"images/Normal/blaziken.png"},
    258: {name: "Mudkip",type: "Water", image:"images/Normal/mudkip.png"},
    259: {name: "Marshtomp",type: "Water · Ground",image:"images/Normal/marshtomp.png"},
    260: {name: "Swampert",type: "Water · Ground",image:"images/Normal/swampert.png"},
    261: {name: "Poochyena",type: "Dark",image:"images/Normal/poochyena.png"},
    262: {name: "Mightyena",type: "Dark",image:"images/Normal/mightyena.png"},
    263: {name: "Zigzagoon", type: "Normal", image:"images/Normal/zigzagoon.png" },
    264: {name: "Linoone", type: "Normal", image:"images/Normal/linoone.png" },
    265: {name: "Wurmple", type: "Bug", image:"images/Normal/wurmple.png" },
    266: {name: "Silcoon", type: "Bug", image:"images/Normal/silcoon.png" },
    267: {name: "Beautifly", type: "Bug · Flying", image:"images/Normal/beautifly.png" },
    268: {name: "Cascoon", type: "Bug", image:"images/Normal/cascoon.png" },
    269: {name: "Dustox", type: "Bug · Poison", image:"images/Normal/dustox.png" },
    270: {name: "Lotad", type: "Water · Grass", image:"images/Normal/lotad.png" },
    271: {name: "Lombre", type: "Water · Grass", image:"images/Normal/lombre.png" },
    272: {name: "Ludicolo", type: "Water · Grass", image:"images/Normal/ludicolo.png" },
    273: {name: "Seedot", type: "Grass", image:"images/Normal/seedot.png" },
    274: {name: "Nuzleaf", type: "Grass · Dark", image:"images/Normal/nuzleaf.png" },
    275: {name: "Shiftry", type: "Grass · Dark", image:"images/Normal/shiftry.png" },
    276: {name: "Taillow", type: "Normal · Flying", image:"images/Normal/taillow.png" },
    277: {name: "Swellow", type: "Normal · Flying", image:"images/Normal/swellow.png" },
    278: {name: "Wingull", type: "Water · Flying", image:"images/Normal/wingull.png" },
    279: {name: "Pelipper", type: "Water · Flying", image:"images/Normal/pelipper.png" },
    280: {name: "Ralts", type: "Psychic · Fairy", image:"images/Normal/ralts.png" },
    281: {name: "Kirlia", type: "Psychic · Fairy", image:"images/Normal/kirlia.png" },
    282: {name: "Gardevoir", type: "Psychic · Fairy", image:"images/Normal/gardevoir.png" },
    283: {name: "Surskit", type: "Bug · Water", image:"images/Normal/surskit.png" },
    284: {name: "Masquerain", type: "Bug · Flying", image:"images/Normal/masquerain.png" },
    285: {name: "Shroomish", type: "Grass", image:"images/Normal/shroomish.png" },
    286: {name: "Breloom", type: "Grass · Fighting", image:"images/Normal/breloom.png" },
    287: {name: "Slakoth", type: "Normal", image:"images/Normal/slakoth.png" },
    288: {name: "Vigoroth", type: "Normal", image:"images/Normal/vigoroth.png" },
    289: {name: "Slaking", type: "Normal", image:"images/Normal/slaking.png" },
    290: {name: "Nincada", type: "Bug · Ground", image:"images/Normal/nincada.png" },
    291: {name: "Ninjask", type: "Bug · Flying", image:"images/Normal/ninjask.png" },
    292: {name: "Shedinja", type: "Bug · Ghost", image:"images/Normal/shedinja.png" },
    293: {name: "Whismur", type: "Normal", image:"images/Normal/whismur.png" },
    294: {name: "Loudred", type: "Normal", image:"images/Normal/loudred.png" },
    295: {name: "Exploud", type: "Normal", image:"images/Normal/exploud.png" },
    296: {name: "Makuhita", type: "Fighting", image:"images/Normal/makuhita.png" },
    297: {name: "Hariyama", type: "Fighting", image:"images/Normal/hariyama.png" },
    298: {name: "Azurill", type: "Normal · Fairy", image:"images/Normal/azurill.png" },
    299: {name: "Nosepass", type: "Rock", image:"images/Normal/nosepass.png" },
    300: {name: "Skitty", type: "Normal", image:"images/Normal/skitty.png" },
    301: {name: "Delcatty", type: "Normal", image:"images/Normal/delcatty.png" },
    302: {name: "Sableye", type: "Dark · Ghost", image:"images/Normal/sableye.png" },
    303: {name: "Mawile",type: "Steel · Fairy",image:"images/Normal/mawile.png"},
    304: {name: "Aron",type: "Steel · Rock",image:"images/Normal/aron.png"},
    305: {name: "Lairon",type: "Steel · Rock", image:"images/Normal/lairon.png"},
    306: {name: "Aggron",type: "Steel · Rock",image:"images/Normal/aggron.png"},
    307: {name: "Meditite",type: "Fighting · Psychic",image:"images/Normal/meditite.png"},
    308: {name: "Medicham",type: "Fighting · Psychic",image:"images/Normal/medicham.png"},
    309: {name: "Electrike",type: "Electric",image:"images/Normal/electrike.png"},
    310: {name: "Manectric",type: "Electric",image:"images/Normal/manectric.png"},
    311: {name: "Plusle",type: "Electric",image:"images/Normal/plusle.png"},
    312: {name: "Minun",type: "Electric",image:"images/Normal/minun.png"},
    313: {name: "Volbeat",type: "Bug",image:"images/Normal/volbeat.png"},
    314: {name: "Illumise",type: "Bug",image:"images/Normal/illumise.png"},
    315: {name: "Roselia",type: "Grass · Poison",image:"images/Normal/roselia.png"},
    316: {name: "Gulpin",type: "Poison",image:"images/Normal/gulpin.png"},
    317: {name: "Swalot",type: "Poison",image:"images/Normal/swalot.png"},
    318: {name: "Carvanha",type: "Water · Dark",image:"images/Normal/carvanha.png"},
    319: {name: "Sharpedo",type: "Water · Dark",image:"images/Normal/sharpedo.png"},
    320: {name: "Wailmer",type: "Water",image:"images/Normal/wailmer.png"},
    321: {name: "Wailord",type: "Water",image:"images/Normal/wailord.png"},
    322: {name: "Numel",type: "Fire · Ground",image:"images/Normal/numel.png"},
    323: {name: "Camerupt",type: "Fire · Ground",image:"images/Normal/camerupt.png"},
    324: {name: "Torkoal",type: "Fire",image:"images/Normal/torkoal.png"},
    325: {name: "Spoink",type: "Psychic",image:"images/Normal/spoink.png"},
    326: {name: "Grumpig",type: "Psychic",image:"images/Normal/grumpig.png"},
    327: {name: "Spinda",type: "Normal",image:"images/Normal/spinda.png"},
    328: {name: "Trapinch",type: "Ground",image:"images/Normal/trapinch.png"},
    329: {name: "Vibrava",type: "Ground · Dragon",image:"images/Normal/vibrava.png"},
    330: {name: "Flygon",type: "Ground · Dragon",image:"images/Normal/flygon.png"},
    331: {name: "Cacnea",type: "Grass",image:"images/Normal/cacnea.png"},
    332: {name: "Cacturne",type: "Grass · Dark",image:"images/Normal/cacturne.png"},
    333: {name: "Swablu",type: "Normal · Flying",image:"images/Normal/swablu.png"},
    334: {name: "Altaria",type: "Dragon · Flying",image:"images/Normal/altaria.png"},
    335: {name: "Zangoose",type: "Normal",image:"images/Normal/zangoose.png"},
    336: {name: "Seviper",type: "Poison",image:"images/Normal/seviper.png"},
    337: {name: "Lunatone",type: "Rock · Psychic",image:"images/Normal/lunatone.png"},
    338: {name: "Solrock",type: "Rock · Psychic",image:"images/Normal/solrock.png"},
    339: {name: "Barboach",type: "Water · Ground",image:"images/Normal/barboach.png"},
    340: {name: "Whiscash",type: "Water · Ground",image:"images/Normal/whiscash.png"},
    341: {name: "Corphish", type: "Water", image:"images/Normal/corphish.png" },
    342: {name: "Crawdaunt",type: "Water · Dark",image:"images/Normal/crawdaunt.png"},
    343: {name: "Baltoy",type: "Ground · Psychic",image:"images/Normal/baltoy.png"},
    344: {name: "Claydol",type: "Ground · Psychic",image:"images/Normal/claydol.png"},
    345: {name: "Lileep",type: "Rock · Grass",image:"images/Normal/lileep.png"},
    346: {name: "Cradily",type: "Rock · Grass",image:"images/Normal/cradily.png"},
    347: {name: "Anorith",type: "Rock · Bug",image:"images/Normal/anorith.png"},
    348: {name: "Armaldo",type: "Rock · Bug",image:"images/Normal/armaldo.png"},
    349: {name: "Feebas",type: "Water",image:"images/Normal/feebas.png"},
    350: {name: "Milotic",type: "Water",image:"images/Normal/milotic.png"},
    351: {name: "Castform",type: "Normal",image:"images/Normal/castform.png"},
    352: {name: "Kecleon",type: "Normal",image:"images/Normal/kecleon.png"},
    353: {name: "Shuppet",type: "Ghost",image:"images/Normal/shuppet.png"},
    354: {name: "Banette",type: "Ghost",image:"images/Normal/banette.png"},
    355: {name: "Duskull",type: "Ghost",image:"images/Normal/duskull.png"},
    356: {name: "Dusclops",type: "Ghost",image:"images/Normal/dusclops.png"},
    357: {name: "Tropius",type: "Grass · Flying",image:"images/Normal/tropius.png"},
    358: {name: "Chimecho", type: "Psychic", image:"images/Normal/chimecho.png" },
    359: {name: "Absol",type: "Dark",image:"images/Normal/absol.png"},
    360: {name: "Wynaut",type: "Psychic",image:"images/Normal/wynaut.png"},
    361: {name: "Snorunt",type: "Ice",image:"images/Normal/snorunt.png"},
    362: {name: "Glalie",type: "Ice",image:"images/Normal/glalie.png"},
    363: {name: "Spheal",type: "Ice · Water",image:"images/Normal/spheal.png"},
    364: {name: "Sealeo",type: "Ice · Water",image:"images/Normal/sealeo.png"},
    365: {name: "Walrein",type: "Ice · Water",image:"images/Normal/walrein.png"},
    366: {name: "Clamperl",type: "Water",image:"images/Normal/clamperl.png"},
    367: {name: "Huntail",type: "Water",image:"images/Normal/huntail.png"},
    368: {name: "Gorebyss",type: "Water",image:"images/Normal/gorebyss.png"},
    369: {name: "Relicanth",type: "Water · Rock",image:"images/Normal/relicanth.png"},
    370: {name: "Luvdisc",type: "Water",image:"images/Normal/luvdisc.png"},
    371: {name: "Bagon",type: "Dragon",image:"images/Normal/bagon.png"},
    372: {name: "Shelgon",type: "Dragon",image:"images/Normal/shelgon.png"},
    373: {name: "Salamence",type: "Dragon · Flying",image:"images/Normal/salamence.png"},
    374: {name: "Beldum",type: "Steel · Psychic",image:"images/Normal/beldum.png"},
    375: {name: "Metang",type: "Steel · Psychic",image:"images/Normal/metang.png"},
    376: {name: "Metagross",type: "Steel · Psychic",image:"images/Normal/metagross.png"},
    377: {name: "Regirock",type: "Rock",image:"images/Normal/regirock.png"},
    378: {name: "Regice",type: "Ice",image:"images/Normal/regice.png"},
    379: {name: "Registeel",type: "Steel",image:"images/Normal/registeel.png"},
    380: {name: "Latias",type: "Dragon · Psychic",image:"images/Normal/latias.png"},
    381: {name: "Latios",type: "Dragon · Psychic",image:"images/Normal/latios.png"},
    382: {name: "Kyogre",type: "Water",image:"images/Normal/kyogre.png"},
    383: {name: "Groudon",type: "Ground",image:"images/Normal/groudon.png"},
    384: {name: "Rayquaza",type: "Dragon · Flying",image:"images/Normal/rayquaza.png"},
    385: {name: "Jirachi",type: "Steel · Psychic",image:"images/Normal/jirachi.png"},
    386: {name: "Deoxys",type: "Psychic",image:"images/Normal/deoxys.png"},
    387: { name: "Turtwig", type: "Grass", image:"images/Normal/turtwig.png" },
    388: { name: "Grotle", type: "Grass", image:"images/Normal/grotle.png" },
    389: { name: "Torterra", type: "Grass · Ground", image:"images/Normal/torterra.png" },
    390: { name: "Chimchar", type: "Fire", image:"images/Normal/chimchar.png" },
    391: { name: "Monferno", type: "Fire · Fighting", image:"images/Normal/monferno.png" },
    392: { name: "Infernape", type: "Fire · Fighting", image:"images/Normal/infernape.png" },
    393: { name: "Piplup", type: "Water", image:"images/Normal/piplup.png" },
    394: { name: "Prinplup", type: "Water", image:"images/Normal/prinplup.png" },
    395: { name: "Empoleon", type: "Water · Steel", image:"images/Normal/empoleon.png" },
    396: { name: "Starly", type: "Normal · Flying", image:"images/Normal/starly.png" },
    397: { name: "Staravia", type: "Normal · Flying", image:"images/Normal/staravia.png" },
    398: { name: "Staraptor", type: "Normal · Flying", image:"images/Normal/staraptor.png" },
    399: { name: "Bidoof", type: "Normal", image:"images/Normal/bidoof.png" },
    400: { name: "Bibarel", type: "Normal · Water", image:"images/Normal/bibarel.png" },
    401: { name: "Kricketot", type: "Bug", image:"images/Normal/kricketot.png" },
    402: { name: "Kricketune", type: "Bug", image:"images/Normal/kricketune.png" },
    403: { name: "Shinx", type: "Electric", image:"images/Normal/shinx.png" },
    404: { name: "Luxio", type: "Electric", image:"images/Normal/luxio.png" },
    405: { name: "Luxray", type: "Electric", image:"images/Normal/luxray.png" },
    406: { name: "Budew", type: "Grass · Poison", image:"images/Normal/budew.png" },
    407: { name: "Roserade", type: "Grass · Poison", image:"images/Normal/roserade.png" },
    408: { name: "Cranidos", type: "Rock", image:"images/Normal/cranidos.png" },
    409: { name: "Rampardos", type: "Rock", image:"images/Normal/rampardos.png" },
    410: { name: "Shieldon", type: "Rock · Steel", image:"images/Normal/shieldon.png" },
    411: { name: "Bastiodon", type: "Rock · Steel", image:"images/Normal/bastiodon.png" },
    412: { name: "Burmy", type: "Bug", image:"images/Normal/burmy.png" },
    413: { name: "Wormadam", type: "Bug · Grass", image:"images/Normal/wormadam.png" },
    414: { name: "Mothim", type: "Bug · Flying", image:"images/Normal/mothim.png" },
    415: { name: "Combee", type: "Bug · Flying", image:"images/Normal/combee.png" },
    416: { name: "Vespiquen", type: "Bug · Flying", image:"images/Normal/vespiquen.png" },
    417: { name: "Pachirisu", type: "Electric", image:"images/Normal/pachirisu.png" },
    418: { name: "Buizel", type: "Water", image:"images/Normal/buizel.png" },
    419: { name: "Floatzel", type: "Water", image:"images/Normal/floatzel.png" },
    420: { name: "Cherubi", type: "Grass", image:"images/Normal/cherubi.png" },
    421: { name: "Cherrim", type: "Grass", image:"images/Normal/cherrim.png" },
    422: { name: "Shellos", type: "Water", image:"images/Normal/shellos.png" },
    423: { name: "Gastrodon", type: "Water · Ground", image:"images/Normal/gastrodon.png" },
    424: { name: "Ambipom", type: "Normal", image:"images/Normal/ambipom.png" },
    425: { name: "Drifloon", type: "Ghost · Flying", image:"images/Normal/drifloon.png" },
    426: { name: "Drifblim", type: "Ghost · Flying", image:"images/Normal/drifblim.png" },
    427: { name: "Buneary", type: "Normal", image:"images/Normal/buneary.png" },
    428: { name: "Lopunny", type: "Normal", image:"images/Normal/lopunny.png" },
    429: { name: "Mismagius", type: "Ghost", image:"images/Normal/mismagius.png" },
    430: { name: "Honchkrow", type: "Dark · Flying", image:"images/Normal/honchkrow.png" },
    431: { name: "Glameow", type: "Normal", image:"images/Normal/glameow.png" },
    432: { name: "Purugly", type: "Normal", image:"images/Normal/purugly.png" },
    433: { name: "Chingling", type: "Psychic", image:"images/Normal/chingling.png" },
    434: { name: "Stunky", type: "Poison · Dark", image:"images/Normal/stunky.png" },
    435: { name: "Skuntank", type: "Poison · Dark", image:"images/Normal/skuntank.png" },
    436: { name: "Bronzor", type: "Steel · Psychic", image:"images/Normal/bronzor.png" },
    437: { name: "Bronzong", type: "Steel · Psychic", image:"images/Normal/bronzong.png" },
    438: { name: "Bonsly", type: "Rock", image:"images/Normal/bonsly.png" },
    439: { name: "Mime Jr.", type: "Psychic · Fairy", image:"images/Normal/mime jr.png" },
    440: { name: "Happiny", type: "Normal", image:"images/Normal/happiny.png" },
    441: { name: "Chatot", type: "Normal · Flying", image:"images/Normal/chatot.png" },
    442: { name: "Spiritomb", type: "Ghost · Dark", image:"images/Normal/spiritomb.png" },
    443: { name: "Gible", type: "Dragon · Ground", image:"images/Normal/gible.png" },
    444: { name: "Gabite", type: "Dragon · Ground", image:"images/Normal/gabite.png" },
    445: { name: "Garchomp", type: "Dragon · Ground", image:"images/Normal/garchomp.png" },
    446: { name: "Munchlax", type: "Normal", image:"images/Normal/munchlax.png" },
    447: { name: "Riolu", type: "Fighting", image:"images/Normal/riolu.png" },
    448: { name: "Lucario", type: "Fighting · Steel", image:"images/Normal/lucario.png" },
    449: { name: "Hippopotas", type: "Ground", image:"images/Normal/hippopotas.png" },
    450: { name: "Hippowdon", type: "Ground", image:"images/Normal/hippowdon.png" },
    451: { name: "Skorupi", type: "Poison · Bug", image:"images/Normal/skorupi.png" },
    452: { name: "Drapion", type: "Poison · Dark", image:"images/Normal/drapion.png" },
    453: { name: "Croagunk", type: "Poison · Fighting", image:"images/Normal/croagunk.png" },
    454: { name: "Toxicroak", type: "Poison · Fighting", image:"images/Normal/toxicroak.png" },
    455: { name: "Carnivine", type: "Grass", image:"images/Normal/carnivine.png" },
    456: { name: "Finneon", type: "Water", image:"images/Normal/finneon.png" },
    457: { name: "Lumineon", type: "Water", image:"images/Normal/lumineon.png" },
    458: { name: "Mantyke", type: "Water · Flying", image:"images/Normal/mantyke.png" },
    459: { name: "Snover", type: "Grass · Ice", image:"images/Normal/snover.png" },
    460: { name: "Abomasnow", type: "Grass · Ice", image:"images/Normal/abomasnow.png" },
    461: { name: "Weavile", type: "Dark · Ice", image:"images/Normal/weavile.png" },
    462: { name: "Magnezone", type: "Electric · Steel", image:"images/Normal/magnezone.png" },
    463: { name: "Lickilicky", type: "Normal", image:"images/Normal/lickilicky.png" },
    464: { name: "Rhyperior", type: "Ground · Rock", image:"images/Normal/rhyperior.png" },
    465: { name: "Tangrowth", type: "Grass", image:"images/Normal/tangrowth.png" },
    466: { name: "Electivire", type: "Electric", image:"images/Normal/electivire.png" },
    467: { name: "Magmortar", type: "Fire", image:"images/Normal/magmortar.png" },
    468: { name: "Togekiss", type: "Fairy · Flying", image:"images/Normal/togekiss.png" },
    469: { name: "Yanmega", type: "Bug · Flying", image:"images/Normal/yanmega.png" },
    470: { name: "Leafeon", type: "Grass", image:"images/Normal/leafeon.png" },
    471: { name: "Glaceon", type: "Ice", image:"images/Normal/glaceon.png" },
    472: { name: "Gliscor", type: "Ground · Flying", image:"images/Normal/gliscor.png" },
    473: { name: "Mamoswine", type: "Ice · Ground", image:"images/Normal/mamoswine.png" },
    474: { name: "Porygon-Z", type: "Normal", image:"images/Normal/porygon-z.png" },
    475: { name: "Gallade", type: "Psychic · Fighting", image:"images/Normal/gallade.png" },
    476: { name: "Probopass", type: "Rock · Steel", image:"images/Normal/probopass.png" },
    477: { name: "Dusknoir", type: "Ghost", image:"images/Normal/dusknoir.png" },
    478: { name: "Froslass", type: "Ice · Ghost", image:"images/Normal/froslass.png" },
    479: { name: "Rotom", type: "Electric · Ghost", image:"images/Normal/rotom.png" },
    480: { name: "Uxie", type: "Psychic", image:"images/Normal/uxie.png" },
    481: { name: "Mesprit", type: "Psychic", image:"images/Normal/mesprit.png" },
    482: { name: "Azelf", type: "Psychic", image:"images/Normal/azelf.png" },
    483: { name: "Dialga", type: "Steel · Dragon", image:"images/Normal/dialga.png" },
    484: { name: "Palkia", type: "Water · Dragon", image:"images/Normal/palkia.png" },
    485: { name: "Heatran", type: "Fire · Steel", image:"images/Normal/heatran.png" },
    486: { name: "Regigigas", type: "Normal", image:"images/Normal/regigigas.png" },
    487: { name: "Giratina", type: "Ghost · Dragon", image:"images/Normal/giratina.png" },
    488: { name: "Cresselia", type: "Psychic", image:"images/Normal/cresselia.png" },
    489: { name: "Phione", type: "Water", image:"images/Normal/phione.png" },
    490: { name: "Manaphy", type: "Water", image:"images/Normal/manaphy.png" },
    491: { name: "Darkrai", type: "Dark", image:"images/Normal/darkrai.png" },
    492: { name: "Shaymin", type: "Grass", image:"images/Normal/shaymin.png" },
    493: { name: "Arceus", type: "Normal", image:"images/Normal/arceus.png" },
    494: { name: "Victini", type: "Psychic/Fire", image:"images/Normal/victini.png" },
    495: { name: "Snivy", type: "Grass", image:"images/Normal/sniv.png" },
    496: { name: "Servine", type: "Grass", image:"images/Normal/servine.png" },
    497: { name: "Serperior", type: "Grass", image:"images/Normal/serperior.png" },
    498: { name: "Tepig", type: "Fire", image:"images/Normal/tepig.png" },
    499: { name: "Pignite", type: "Fire/Fighting", image:"images/Normal/pignite.png" },
    500: { name: "Emboar", type: "Fire/Fighting", image:"images/Normal/emboar.png" },
    501: { name: "Oshawott", type: "Water", image:"images/Normal/oshawott.png" },
    502: { name: "Dewott", type: "Water", image:"images/Normal/dewott.png" },
    503: { name: "Samurott", type: "Water", image:"images/Normal/samurott.png" },
    504: { name: "Patrat", type: "Normal", image:"images/Normal/patrat.png" },
    505: { name: "Watchog", type: "Normal", image:"images/Normal/watchog.png" },
    506: { name: "Lillipup", type: "Normal", image:"images/Normal/lillipup.png" },
    507: { name: "Herdier", type: "Normal", image:"images/Normal/herdier.png" },
    508: { name: "Stoutland", type: "Normal", image:"images/Normal/stoutland.png" },
    509: { name: "Purrloin", type: "Dark", image:"images/Normal/purrloin.png" },
    510: { name: "Liepard", type: "Dark", image:"images/Normal/liepard.png" },
    511: { name: "Pansage", type: "Grass", image:"images/Normal/pansage.png" },
    512: { name: "Simisage", type: "Grass", image:"images/Normal/simisage.png" },
    513: { name: "Pansear", type: "Fire", image:"images/Normal/pansear.png" },
    514: { name: "Simisear", type: "Fire", image:"images/Normal/simisear.png" },
    515: { name: "Panpour", type: "Water", image:"images/Normal/panpour.png" },
    516: { name: "Simipour", type: "Water", image:"images/Normal/simipour.png" },
    517: { name: "Munna", type: "Psychic", image:"images/Normal/munna.png" },
    518: { name: "Musharna", type: "Psychic", image:"images/Normal/musharna.png" },
    519: { name: "Pidove", type: "Normal/Flying", image:"images/Normal/pidove.png" },
    520: { name: "Tranquill", type: "Normal/Flying", image:"images/Normal/tranquill.png" },
    521: { name: "Unfezant", type: "Normal/Flying", image:"images/Normal/unfezant.png" },
    522: { name: "Blitzle", type: "Electric", image:"images/Normal/blitzle.png" },
    523: { name: "Zebstrika", type: "Electric", image:"images/Normal/zebstrika.png" },
    524: { name: "Roggenrola", type: "Rock", image:"images/Normal/roggenrola.png" },
    525: { name: "Boldore", type: "Rock", image:"images/Normal/boldore.png" },
    526: { name: "Gigalith", type: "Rock", image:"images/Normal/gigalith.png" },
    527: { name: "Woobat", type: "Psychic/Flying", image:"images/Normal/woobat.png" },
    528: { name: "Swoobat", type: "Psychic/Flying", image:"images/Normal/swoobat.png" },
    529: { name: "Drilbur", type: "Ground", image:"images/Normal/drilbur.png" },
    530: { name: "Excadrill", type: "Ground/Steel", image:"images/Normal/excadrill.png" },
    531: { name: "Audino", type: "Normal", image:"images/Normal/audino.png" },
    532: { name: "Timburr", type: "Fighting", image:"images/Normal/timburr.png" },
    533: { name: "Gurdurr", type: "Fighting", image:"images/Normal/gurdurr.png" },
    534: { name: "Conkeldurr", type: "Fighting", image:"images/Normal/conkeldurr.png" },
    535: { name: "Tympole", type: "Water", image:"images/Normal/tympole.png" },
    536: { name: "Palpitoad", type: "Water · Ground", image:"images/Normal/palpitoad.png" },
    537: { name: "Seismitoad", type: "Water · Ground", image:"images/Normal/seismitoad.png" },
    538: { name: "Throh", type: "Fighting", image:"images/Normal/throh.png" },
    539: { name: "Sawk", type: "Fighting", image:"images/Normal/sawk.png" },
    540: { name: "Sewaddle", type: "Bug · Grass", image:"images/Normal/sewaddle.png" },
    541: { name: "Swadloon", type: "Bug · Grass", image:"images/Normal/swadloon.png" },
    542: { name: "Leavanny", type: "Bug · Grass", image:"images/Normal/leavanny.png" },
    543: { name: "Venipede", type: "Bug · Poison", image:"images/Normal/venipede.png" },
    544: { name: "Whirlipede", type: "Bug · Poison", image:"images/Normal/whirlipede.png" },
    545: { name: "Scolipede", type: "Bug · Poison", image:"images/Normal/scolipede.png" },
    546: { name: "Cottonee", type: "Grass · Fairy", image:"images/Normal/cottonee.png" },
    547: { name: "Whimsicott", type: "Grass · Fairy", image:"images/Normal/whimsicott.png" },
    548: { name: "Petilil", type: "Grass", image:"images/Normal/petilil.png" },
    549: { name: "Lilligant", type: "Grass", image:"images/Normal/lilligant.png" },
    550: { name: "Basculin", type: "Water", image:"images/Normal/basculin.png" },
    551: { name: "Sandile", type: "Ground · Dark", image:"images/Normal/sandile.png" },
    552: { name: "Krokorok", type: "Ground · Dark", image:"images/Normal/krokorok.png" },
    553: { name: "Krookodile", type: "Ground · Dark", image:"images/Normal/krookodile.png" },
    554: { name: "Darumaka", type: "Fire", image:"images/Normal/darumaka.png" },
    555: { name: "Darmanitan", type: "Fire", image:"images/Normal/darmanitan.png" },
    556: { name: "Maractus", type: "Grass", image:"images/Normal/maractus.png" },
    557: { name: "Dwebble", type: "Bug · Rock", image:"images/Normal/dwebble.png" },
    558: { name: "Crustle", type: "Bug · Rock", image:"images/Normal/crustle.png" },
    559: { name: "Scraggy", type: "Dark · Fighting", image:"images/Normal/scraggy.png" },
    560: { name: "Scrafty", type: "Dark · Fighting", image:"images/Normal/scrafty.png" },
    561: { name: "Sigilyph", type: "Psychic · Flying", image:"images/Normal/sigilyph.png" },
    562: { name: "Yamask", type: "Ghost", image:"images/Normal/yamask.png" },
    563: { name: "Cofagrigus", type: "Ghost", image:"images/Normal/cofagrigus.png" },
    564: { name: "Tirtouga", type: "Water · Rock", image:"images/Normal/tirtouga.png" },
    565: { name: "Carracosta", type: "Water · Rock", image:"images/Normal/carracosta.png" },
    566: { name: "Archen", type: "Rock · Flying", image:"images/Normal/archen.png" },
    567: { name: "Archeops", type: "Rock · Flying", image:"images/Normal/archeops.png" },
    568: { name: "Trubbish", type: "Poison", image:"images/Normal/trubbish.png" },
    569: { name: "Garbodor", type: "Poison", image:"images/Normal/garbodor.png" },
    570: { name: "Zorua", type: "Dark", image:"images/Normal/zorua.png" },
    571: { name: "Zoroark", type: "Dark", image:"images/Normal/zoroark.png" },
    572: { name: "Minccino", type: "Normal", image:"images/Normal/minccino.png" },
    573: { name: "Cinccino", type: "Normal", image:"images/Normal/cinccino.png" },
    574: { name: "Gothita", type: "Psychic", image:"images/Normal/gothita.png" },
    575: { name: "Gothorita", type: "Psychic", image:"images/Normal/gothorita.png" },
    576: { name: "Gothitelle", type: "Psychic", image:"images/Normal/gothitelle.png" },
    577: { name: "Solosis", type: "Psychic", image:"images/Normal/solosis.png" },
    578: { name: "Duosion", type: "Psychic", image:"images/Normal/duosion.png" },
    579: { name: "Reuniclus", type: "Psychic", image:"images/Normal/reuniclus.png" },
    580: { name: "Ducklett", type: "Water · Flying", image:"images/Normal/ducklett.png" },
    581: { name: "Swanna", type: "Water · Flying", image:"images/Normal/swanna.png" },
    582: { name: "Vanillite", type: "Ice", image:"images/Normal/vanillite.png" },
    583: { name: "Vanillish", type: "Ice", image:"images/Normal/vanillish.png" },
    584: { name: "Vanilluxe", type: "Ice", image:"images/Normal/vanilluxe.png" },
    585: { name: "Deerling", type: "Normal · Grass", image:"images/Normal/deerling.png" },
    586: { name: "Sawsbuck", type: "Normal · Grass", image:"images/Normal/sawsbuck.png" },
    587: { name: "Emolga", type: "Electric · Flying", image:"images/Normal/emolga.png" },
    588: { name: "Karrablast", type: "Bug", image:"images/Normal/karrablast.png" },
    589: { name: "Escavalier", type: "Bug · Steel", image:"images/Normal/escavalier.png" },
    590: { name: "Foongus", type: "Grass · Poison", image:"images/Normal/foongus.png" },
    591: { name: "Amoonguss", type: "Grass · Poison", image:"images/Normal/amoonguss.png" },
    592: { name: "Frillish", type: "Water · Ghost", image:"images/Normal/frillish.png" },
    593: { name: "Jellicent", type: "Water · Ghost", image:"images/Normal/jellicent.png" },
    594: { name: "Alomomola", type: "Water", image:"images/Normal/alomomola.png" },
    595: { name: "Joltik", type: "Bug · Electric", image:"images/Normal/joltik.png" },
    596: { name: "Galvantula", type: "Bug · Electric", image:"images/Normal/galvantula.png" },
    597: { name: "Ferroseed", type: "Grass · Steel", image:"images/Normal/ferroseed.png" },
    598: { name: "Ferrothorn", type: "Grass · Steel", image:"images/Normal/ferrothorn.png" },
    599: { name: "Klink", type: "Steel", image:"images/Normal/klink.png" },
    600: { name: "Klang", type: "Steel", image:"images/Normal/klang.png" },
    601: { name: "Klinklang", type: "Steel", image:"images/Normal/klinklang.png" },
    602: { name: "Tynamo", type: "Electric", image:"images/Normal/tynamo.png" },
    603: { name: "Eelektrik", type: "Electric", image:"images/Normal/eelektrik.png" },
    604: { name: "Eelektross", type: "Electric", image:"images/Normal/eelektross.png" },
    605: { name: "Elgyem", type: "Psychic", image:"images/Normal/elgyem.png" },
    606: { name: "Beheeyem", type: "Psychic", image:"images/Normal/beheeyem.png" },
    607: { name: "Litwick", type: "Ghost · Fire", image:"images/Normal/litwick.png" },
    608: { name: "Lampent", type: "Ghost · Fire", image:"images/Normal/lampent.png" },
    609: { name: "Chandelure", type: "Ghost · Fire", image:"images/Normal/chandelure.png" },
    610: { name: "Axew", type: "Dragon", image:"images/Normal/axew.png" },
    611: { name: "Fraxure", type: "Dragon", image:"images/Normal/fraxure.png" },
    612: { name: "Haxorus", type: "Dragon", image:"images/Normal/haxorus.png" },
    613: { name: "Cubchoo", type: "Ice", image:"images/Normal/cubchoo.png" },
    614: { name: "Beartic", type: "Ice", image:"images/Normal/beartic.png" },
    615: { name: "Cryogonal", type: "Ice", image:"images/Normal/cryogonal.png" },
    616: { name: "Shelmet", type: "Bug", image:"images/Normal/shelmet.png" },
    617: { name: "Accelgor", type: "Bug", image:"images/Normal/accelgor.png" },
    618: { name: "Stunfisk", type: "Ground · Electric", image:"images/Normal/stunfisk.png" },
    619: { name: "Mienfoo", type: "Fighting", image:"images/Normal/mienfoo.png" },
    620: { name: "Mienshao", type: "Fighting", image:"images/Normal/mienshao.png" },
    621: { name: "Druddigon", type: "Dragon", image:"images/Normal/druddigon.png" },
    622: { name: "Golett", type: "Ground · Ghost", image:"images/Normal/golett.png" },
    623: { name: "Golurk", type: "Ground · Ghost", image:"images/Normal/golurk.png" },
    624: { name: "Pawniard", type: "Dark · Steel", image:"images/Normal/pawniard.png" },
    625: { name: "Bisharp", type: "Dark · Steel", image:"images/Normal/bisharp.png" },
    626: { name: "Bouffalant", type: "Normal", image:"images/Normal/bouffalant.png" },
    627: { name: "Rufflet", type: "Normal · Flying", image:"images/Normal/rufflet.png" },
    628: { name: "Braviary", type: "Normal · Flying", image:"images/Normal/braviary.png" },
    629: { name: "Vullaby", type: "Dark · Flying", image:"images/Normal/vullaby.png" },
    630: { name: "Mandibuzz", type: "Dark · Flying", image:"images/Normal/mandibuzz.png" },
    631: { name: "Heatmor", type: "Fire", image:"images/Normal/heatmor.png" },
    632: { name: "Durant", type: "Bug · Steel", image:"images/Normal/durant.png" },
    633: { name: "Deino", type: "Dark · Dragon", image:"images/Normal/deino.png" },
    634: { name: "Zweilous", type: "Dark · Dragon", image:"images/Normal/zweilous.png" },
    635: { name: "Hydreigon", type: "Dark · Dragon", image:"images/Normal/hydreigon.png" },
    636: { name: "Larvesta", type: "Bug · Fire", image:"images/Normal/larvesta.png" },
    637: { name: "Volcarona", type: "Bug · Fire", image:"images/Normal/volcarona.png" },
    638: { name: "Cobalion", type: "Steel · Fighting", image:"images/Normal/cobalion.png" },
    639: { name: "Terrakion", type: "Rock · Fighting", image:"images/Normal/terrakion.png" },
    640: { name: "Virizion", type: "Grass · Fighting", image:"images/Normal/virizion.png" },
    641: { name: "Tornadus", type: "Flying", image:"images/Normal/tornadus.png" },
    642: { name: "Thundurus", type: "Electric · Flying", image:"images/Normal/thundurus.png" },
    643: { name: "Reshiram", type: "Dragon · Fire", image:"images/Normal/reshiram.png" },
    644: { name: "Zekrom", type: "Dragon · Electric", image:"images/Normal/zekrom.png" },
    645: { name: "Landorus", type: "Ground · Flying", image:"images/Normal/landorus.png" },
    646: { name: "Kyurem", type: "Dragon · Ice", image:"images/Normal/kyurem.png" },
    647: { name: "Keldeo", type: "Water · Fighting", image:"images/Normal/keldeo.png" },
    648: { name: "Meloetta", type: "Normal · Psychic", image:"images/Normal/meloetta.png" },
    649: { name: "Genesect", type: "Bug · Steel", image:"images/Normal/genesect.png" },
    650: { name: "Chespin", type: "Grass", image:"images/Normal/chespin.png" },
    651: { name: "Quilladin", type: "Grass", image:"images/Normal/quilladin.png" },
    652: { name: "Chesnaught", type: "Grass · Fighting", image:"images/Normal/chesnaught.png" },
    653: { name: "Fennekin", type: "Fire", image:"images/Normal/fennekin.png" },
    654: { name: "Braixen", type: "Fire", image:"images/Normal/braixen.png" },
    655: { name: "Delphox", type: "Fire · Psychic", image:"images/Normal/delphox.png" },
    656: { name: "Froakie", type: "Water", image:"images/Normal/froakie.png" },
    657: { name: "Frogadier", type: "Water", image:"images/Normal/frogadier.png" },
    658: { name: "Greninja", type: "Water · Dark", image:"images/Normal/greninja.png" },
    659: { name: "Bunnelby", type: "Normal", image:"images/Normal/bunnelby.png" },
    660: { name: "Diggersby", type: "Normal · Ground", image:"images/Normal/diggersby.png" },
    661: { name: "Fletchling", type: "Normal · Flying", image:"images/Normal/fletchling.png" },
    662: { name: "Fletchinder", type: "Fire · Flying", image:"images/Normal/fletchinder.png" },
    663: { name: "Talonflame", type: "Fire · Flying", image:"images/Normal/talonflame.png" },
    664: { name: "Scatterbug", type: "Bug", image:"images/Normal/scatterbug.png" },
    665: { name: "Spewpa", type: "Bug", image:"images/Normal/spewpa.png" },
    666: { name: "Vivillon", type: "Bug · Flying", image:"images/Normal/vivillon.png" },
    667: { name: "Litleo", type: "Fire · Normal", image:"images/Normal/litleo.png" },
    668: { name: "Pyroar", type: "Fire · Normal", image:"images/Normal/pyroar.png" },
    669: { name: "Flabébé", type: "Fairy", image:"images/Normal/Flabébé.png" },
    670: { name: "Floette", type: "Fairy", image:"images/Normal/floette.png" },
    671: { name: "Florges", type: "Fairy", image:"images/Normal/florges.png" },
    672: { name: "Skiddo", type: "Grass", image:"images/Normal/skiddo.png" },
    673: { name: "Gogoat", type: "Grass", image:"images/Normal/gogoat.png" },
    674: { name: "Pancham", type: "Fighting", image:"images/Normal/pancham.png" },
    675: { name: "Pangoro", type: "Fighting · Dark", image:"images/Normal/pangoro.png" },
    676: { name: "Furfrou", type: "Normal", image:"images/Normal/furfrou.png" },
    677: { name: "Espurr", type: "Psychic", image:"images/Normal/espurr.png" },
    678: { name: "Meowstic", type: "Psychic", image:"images/Normal/meowstic.png" },
    679: { name: "Honedge", type: "Steel · Ghost", image:"images/Normal/honedge.png" },
    680: { name: "Doublade", type: "Steel · Ghost", image:"images/Normal/doublade.png" },
    681: { name: "Aegislash", type: "Steel · Ghost", image:"images/Normal/aegislash.png" },
    682: { name: "Spritzee", type: "Fairy", image:"images/Normal/spritzee.png" },
    683: { name: "Aromatisse", type: "Fairy", image:"images/Normal/aromatisse.png" },
    684: { name: "Swirlix", type: "Fairy", image:"images/Normal/swirlix.png" },
    685: { name: "Slurpuff", type: "Fairy", image:"images/Normal/slurpuff.png" },
    686: { name: "Inkay", type: "Dark · Psychic", image:"images/Normal/inkay.png" },
    687: { name: "Malamar", type: "Dark · Psychic", image:"images/Normal/malamar.png" },
    688: { name: "Binacle", type: "Rock · Water", image:"images/Normal/binacle.png" },
    689: { name: "Barbaracle", type: "Rock · Water", image:"images/Normal/barbaracle.png" },
    690: { name: "Skrelp", type: "Poison · Water", image:"images/Normal/skrelp.png" },
    691: { name: "Dragalge", type: "Poison · Dragon", image:"images/Normal/dragalge.png" },
    692: { name: "Clauncher", type: "Water", image:"images/Normal/clauncher.png" },
    693: { name: "Clawitzer", type: "Water", image:"images/Normal/clawitzer.png" },
    694: { name: "Helioptile", type: "Electric · Normal", image:"images/Normal/helioptile.png" },
    695: { name: "Heliolisk", type: "Electric · Normal", image:"images/Normal/heliolisk.png" },
    696: { name: "Tyrunt", type: "Rock · Dragon", image:"images/Normal/tyrunt.png" },
    697: { name: "Tyrantrum", type: "Rock · Dragon", image:"images/Normal/tyrantrum.png" },
    698: { name: "Amaura", type: "Rock · Ice", image:"images/Normal/amaura.png" },
    699: { name: "Aurorus", type: "Rock · Ice", image:"images/Normal/aurorus.png" },
    700: { name: "Sylveon", type: "Fairy", image:"images/Normal/sylveon.png" },
    701: { name: "Hawlucha", type: "Fighting · Flying", image:"images/Normal/hawlucha.png" },
    702: { name: "Dedenne", type: "Electric · Fairy", image:"images/Normal/dedenne.png" },
    703: { name: "Carbink", type: "Rock · Fairy", image:"images/Normal/carbink.png" },
    704: { name: "Goomy", type: "Dragon", image:"images/Normal/goomy.png" },
    705: { name: "Sliggoo", type: "Dragon", image:"images/Normal/sliggoo.png" },
    706: { name: "Goodra", type: "Dragon", image:"images/Normal/goodra.png" },
    707: { name: "Klefki", type: "Steel · Fairy", image:"images/Normal/klefki.png" },
    708: { name: "Phantump", type: "Ghost · Grass", image:"images/Normal/phantump.png" },
    709: { name: "Trevenant", type: "Ghost · Grass", image:"images/Normal/trevenant.png" },
    710: { name: "Pumpkaboo", type: "Ghost · Grass", image:"images/Normal/pumpkaboo.png" },
    711: { name: "Gourgeist", type: "Ghost · Grass", image:"images/Normal/gourgeist.png" },
    712: { name: "Bergmite", type: "Ice", image:"images/Normal/bergmite.png" },
    713: { name: "Avalugg", type: "Ice", image:"images/Normal/avalugg.png" },
    714: { name: "Noibat", type: "Flying · Dragon", image:"images/Normal/noibat.png" },
    715: { name: "Noivern", type: "Flying · Dragon", image:"images/Normal/noivern.png" },
    716: { name: "Xerneas", type: "Fairy", image:"images/Normal/xerneas.png" },
    717: { name: "Yveltal", type: "Dark · Flying", image:"images/Normal/yveltal.png" },
    718: { name: "Zygarde", type: "Dragon · Ground", image:"images/Normal/zygarde.png" },
    719: { name: "Diancie", type: "Rock · Fairy", image:"images/Normal/diancie.png" },
    720: { name: "Hoopa", type: "Psychic · Ghost", image:"images/Normal/hoopa.png" },
    721: { name: "Volcanion", type: "Fire · Water", image:"images/Normal/volcanion.png" },
    722: { name: "Rowlet", type: "Grass · Flying", image:"images/Normal/rowlet.png" },
    723: { name: "Dartrix", type: "Grass · Flying", image:"images/Normal/dartrix.png" },
    724: { name: "Decidueye", type: "Grass · Ghost", image:"images/Normal/decidueye.png" },
    725: { name: "Litten", type: "Fire", image:"images/Normal/litten.png" },
    726: { name: "Torracat", type: "Fire", image:"images/Normal/torracat.png" },
    727: { name: "Incineroar", type: "Fire · Dark", image:"images/Normal/incineroar.png" },
    728: { name: "Popplio", type: "Water", image:"images/Normal/popplio.png" },
    729: { name: "Brionne", type: "Water", image:"images/Normal/brionne.png" },
    730: { name: "Primarina", type: "Water · Fairy", image:"images/Normal/primarina.png" },
    731: { name: "Pikipek", type: "Normal · Flying", image:"images/Normal/pikipek.png" },
    732: { name: "Trumbeak", type: "Normal · Flying", image:"images/Normal/trumbeak.png" },
    733: { name: "Toucannon", type: "Normal · Flying", image:"images/Normal/toucannon.png" },
    734: { name: "Yungoos", type: "Normal", image:"images/Normal/yungoos.png" },
    735: { name: "Gumshoos", type: "Normal", image:"images/Normal/gumshoos.png" },
    736: { name: "Grubbin", type: "Bug", image:"images/Normal/grubbin.png" },
    737: { name: "Charjabug", type: "Bug · Electric", image:"images/Normal/charjabug.png" },
    738: { name: "Vikavolt", type: "Bug · Electric", image:"images/Normal/vikavolt.png" },
    739: { name: "Crabrawler", type: "Fighting", image:"images/Normal/crabrawler.png" },
    740: { name: "Crabominable", type: "Fighting · Ice", image:"images/Normal/crabominable.png" },
    741: { name: "Oricorio", type: "Fire · Flying", image:"images/Normal/oricorio.png" },
    742: { name: "Cutiefly", type: "Bug · Fairy", image:"images/Normal/cutiefly.png" },
    743: { name: "Ribombee", type: "Bug · Fairy", image:"images/Normal/ribombee.png" },
    744: { name: "Rockruff", type: "Rock", image:"images/Normal/rockruff.png" },
    745: { name: "Lycanroc", type: "Rock", image:"images/Normal/lycanroc.png" },
    746: { name: "Wishiwashi", type: "Water", image:"images/Normal/wishiwashi.png" },
    747: { name: "Mareanie", type: "Poison · Water", image:"images/Normal/mareanie.png" },
    748: { name: "Toxapex", type: "Poison · Water", image:"images/Normal/toxapex.png" },
    749: { name: "Mudbray", type: "Ground", image:"images/Normal/mudbray.png" },
    750: { name: "Mudsdale", type: "Ground", image:"images/Normal/mudsdale.png" },
    751: { name: "Dewpider", type: "Water · Bug", image:"images/Normal/dewpider.png" },
    752: { name: "Araquanid", type: "Water · Bug", image:"images/Normal/araquanid.png" },
    753: { name: "Fomantis", type: "Grass", image:"images/Normal/fomantis.png" },
    754: { name: "Lurantis", type: "Grass", image:"images/Normal/lurantis.png" },
    755: { name: "Morelull", type: "Grass · Fairy", image:"images/Normal/morelull.png" },
    756: { name: "Shiinotic", type: "Grass · Fairy", image:"images/Normal/shiinotic.png" },
    757: { name: "Salandit", type: "Poison · Fire", image:"images/Normal/salandit.png" },
    758: { name: "Salazzle", type: "Poison · Fire", image:"images/Normal/salazzle.png" },
    759: { name: "Stufful", type: "Normal · Fighting", image:"images/Normal/stufful.png" },
    760: { name: "Bewear", type: "Normal · Fighting", image:"images/Normal/bewear.png" },
    761: { name: "Bounsweet", type: "Grass", image:"images/Normal/bounsweet.png" },
    762: { name: "Steenee", type: "Grass", image:"images/Normal/steenee.png" },
    763: { name: "Tsareena", type: "Grass", image:"images/Normal/tsareena.png" },
    764: { name: "Comfey", type: "Fairy", image:"images/Normal/comfey.png" },
    765: { name: "Oranguru", type: "Normal · Psychic", image:"images/Normal/oranguru.png" },
    766: { name: "Passimian", type: "Fighting", image:"images/Normal/passimian.png" },
    767: { name: "Wimpod", type: "Bug · Water", image:"images/Normal/wimpod.png" },
    768: { name: "Golisopod", type: "Bug · Water", image:"images/Normal/golisopod.png" },
    769: { name: "Sandygast", type: "Ghost · Ground", image:"images/Normal/sandygast.png" },
    770: { name: "Palossand", type: "Ghost · Ground", image:"images/Normal/palossand.png" },
    771: { name: "Pyukumuku", type: "Water", image:"images/Normal/pyukumuku.png" },
    772: { name: "Type: Null", type: "Normal", image:"images/Normal/typenull.png" },
    773: { name: "Silvally", type: "Normal", image:"images/Normal/silvally.png" },
    774: { name: "Minior", type: "Rock · Flying", image:"images/Normal/minior.png" },
    775: { name: "Komala", type: "Normal", image:"images/Normal/komala.png" },
    776: { name: "Turtonator", type: "Fire · Dragon", image:"images/Normal/turtonator.png" },
    777: { name: "Togedemaru", type: "Electric · Steel", image:"images/Normal/togedemaru.png" },
    778: { name: "Mimikyu", type: "Ghost · Fairy", image:"images/Normal/mimikyu.png" },
    779: { name: "Bruxish", type: "Water · Psychic", image:"images/Normal/bruxish.png" },
    780: { name: "Drampa", type: "Normal · Dragon", image:"images/Normal/drampa.png" },
    781: { name: "Dhelmise", type: "Ghost · Grass", image:"images/Normal/dhelmise.png" },
    782: { name: "Jangmo-o", type: "Dragon", image:"images/Normal/jangmoo.png" },
    783: { name: "Hakamo-o", type: "Dragon · Fighting", image:"images/Normal/hakamo-o.png" },
    784: { name: "Kommo-o", type: "Dragon · Fighting", image:"images/Normal/kommo-o.png" },
    785: { name: "Tapu Koko", type: "Electric · Fairy", image:"images/Normal/tapukoko.png" },
    786: { name: "Tapu Lele", type: "Psychic · Fairy", image:"images/Normal/tapulele.png" },
    787: { name: "Tapu Bulu", type: "Grass · Fairy", image:"images/Normal/tapubulu.png" },
    788: { name: "Tapu Fini", type: "Water · Fairy", image:"images/Normal/tapufini.png" },
    789: { name: "Cosmog", type: "Psychic", image:"images/Normal/cosmog.png" },
    790: { name: "Cosmoem", type: "Psychic", image:"images/Normal/cosmoem.png" },
    791: { name: "Solgaleo", type: "Psychic · Steel", image:"images/Normal/solgaleo.png" },
    792: { name: "Lunala", type: "Psychic · Ghost", image:"images/Normal/lunala.png" },
    793: { name: "Nihilego", type: "Rock · Poison", image:"images/Normal/nihilego.png" },
    794: { name: "Buzzwole", type: "Bug · Fighting", image:"images/Normal/buzzwole.png" },
    795: { name: "Pheromosa", type: "Bug · Fighting", image:"images/Normal/pheromosa.png" },
    796: { name: "Xurkitree", type: "Electric", image:"images/Normal/xurkitree.png" },
    797: { name: "Celesteela", type: "Steel · Flying", image:"images/Normal/celesteela.png" },
    798: { name: "Kartana", type: "Grass · Steel", image:"images/Normal/kartana.png" },
    799: { name: "Guzzlord", type: "Dark · Dragon", image:"images/Normal/guzzlord.png" },
    800: { name: "Necrozma", type: "Psychic", image:"images/Normal/necrozma.png" },
    801: { name: "Magearna", type: "Steel · Fairy", image:"images/Normal/magearna.png" },
    802: { name: "Marshadow", type: "Fighting · Ghost", image:"images/Normal/marshadow.png" },
    803: { name: "Poipole", type: "Poison", image:"images/Normal/poipole.png" },
    804: { name: "Naganadel", type: "Poison · Dragon", image:"images/Normal/naganadel.png" },
    805: { name: "Stakataka", type: "Rock · Steel", image:"images/Normal/stakataka.png" },
    806: { name: "Blacephalon", type: "Fire · Ghost", image:"images/Normal/blacephalon.png" },
    807: { name: "Zeraora", type: "Electric", image:"images/Normal/zeraora.png" },
    808: { name: "Meltan", type: "Steel", image:"images/Normal/meltan.png" },
    809: { name: "Melmetal", type: "Steel", image:"images/Normal/melmetal.png" },
    810: { name: "Grookey", type: "Grass", image:"images/Normal/grookey.png" },
    811: { name: "Thwackey", type: "Grass", image:"images/Normal/thwackey.png" },
    812: { name: "Rillaboom", type: "Grass", image:"images/Normal/rillaboom.png" },
    813: { name: "Scorbunny", type: "Fire", image:"images/Normal/scorbunny.png" },
    814: { name: "Raboot", type: "Fire", image:"images/Normal/raboot.png" },
    815: { name: "Cinderace", type: "Fire", image:"images/Normal/cinderace.png" },
    816: { name: "Sobble", type: "Water", image:"images/Normal/sobble.png" },
    817: { name: "Drizzile", type: "Water", image:"images/Normal/drizzile.png" },
    818: { name: "Inteleon", type: "Water", image:"images/Normal/inteleon.png" },
    819: { name: "Skwovet", type: "Normal", image:"images/Normal/skwovet.png" },
    820: { name: "Greedent", type: "Normal", image:"images/Normal/greedent.png" },
    821: { name: "Rookidee", type: "Flying", image:"images/Normal/rookidee.png" },
    822: { name: "Corvisquire", type: "Flying", image:"images/Normal/corvisquire.png" },
    823: { name: "Corviknight", type: "Flying · Steel", image:"images/Normal/corviknight.png" },
    824: { name: "Blipbug", type: "Bug", image:"images/Normal/blipbug.png" },
    825: { name: "Dottler", type: "Bug · Psychic", image:"images/Normal/dottler.png" },
    826: { name: "Orbeetle", type: "Bug · Psychic", image:"images/Normal/orbeetle.png" },
    827: { name: "Nickit", type: "Dark", image:"images/Normal/nickit.png" },
    828: { name: "Thievul", type: "Dark", image:"images/Normal/thievul.png" },
    829: { name: "Gossifleur", type: "Grass", image:"images/Normal/gossifleur.png" },
    830: { name: "Eldegoss", type: "Grass", image:"images/Normal/eldegoss.png" },
    831: { name: "Wooloo", type: "Normal", image:"images/Normal/wooloo.png" },
    832: { name: "Dubwool", type: "Normal", image:"images/Normal/dubwool.png" },
    833: { name: "Chewtle", type: "Water", image:"images/Normal/chewtle.png" },
    834: { name: "Drednaw", type: "Water · Rock", image:"images/Normal/drednaw.png" },
    835: { name: "Yamper", type: "Electric", image:"images/Normal/yamper.png" },
    836: { name: "Boltund", type: "Electric", image:"images/Normal/boltund.png" },
    837: { name: "Rolycoly", type: "Rock", image:"images/Normal/rolycoly.png" },
    838: { name: "Carkol", type: "Rock · Fire", image:"images/Normal/carkol.png" },
    839: { name: "Coalossal", type: "Rock · Fire", image:"images/Normal/coalossal.png" },
    840: { name: "Applin", type: "Grass · Dragon", image:"images/Normal/applin.png" },
    841: { name: "Flapple", type: "Grass · Dragon", image:"images/Normal/flapple.png" },
    842: { name: "Appletun", type: "Grass · Dragon", image:"images/Normal/appletun.png" },
    843: { name: "Silicobra", type: "Ground", image:"images/Normal/silicobra.png" },
    844: { name: "Sandaconda", type: "Ground", image:"images/Normal/sandaconda.png" },
    845: { name: "Cramorant", type: "Flying · Water", image:"images/Normal/cramorant.png" },
    846: { name: "Arrokuda", type: "Water", image:"images/Normal/arrokuda.png" },
    847: { name: "Barraskewda", type: "Water", image:"images/Normal/barraskewda.png" },
    848: { name: "Toxel", type: "Electric · Poison", image:"images/Normal/toxel.png" },
    849: { name: "Toxtricity", type: "Electric · Poison", image:"images/Normal/toxtricity.png" },
    850: { name: "Sizzlipede", type: "Fire · Bug", image:"images/Normal/sizzlipede.png" },
    851: { name: "Centiskorch", type: "Fire · Bug", image:"images/Normal/centiskorch.png" },
    852: { name: "Clobbopus", type: "Fighting", image:"images/Normal/clobbopus.png" },
    853: { name: "Grapploct", type: "Fighting", image:"images/Normal/grapploct.png" },
    854: { name: "Sinistea", type: "Ghost", image:"images/Normal/sinistea.png" },
    855: { name: "Polteageist", type: "Ghost", image:"images/Normal/polteageist.png" },
    856: { name: "Hatenna", type: "Psychic", image:"images/Normal/hatenna.png" },
    857: { name: "Hattrem", type: "Psychic", image:"images/Normal/hattrem.png" },
    858: { name: "Hatterene", type: "Psychic · Fairy", image:"images/Normal/hatterene.png" },
    859: { name: "Impidimp", type: "Dark · Fairy", image:"images/Normal/impidimp.png" },
    860: { name: "Morgrem", type: "Dark · Fairy", image:"images/Normal/morgrem.png" },
    861: { name: "Grimmsnarl", type: "Dark · Fairy", image:"images/Normal/grimmsnarl.png" },
    862: { name: "Obstagoon", type: "Dark · Normal", image:"images/Normal/obstagoon.png" },
    863: { name: "Perrserker", type: "Steel", image:"images/Normal/perrserker.png" },
    864: { name: "Cursola", type: "Ghost", image:"images/Normal/cursola.png" },
    865: { name: "Sirfetch'd", type: "Fighting", image:"images/Normal/sirfetch'd.png" },
    866: { name: "Mr. Rime", type: "Ice · Psychic", image:"images/Normal/mr. rime.png" },
    867: { name: "Runerigus", type: "Ground · Ghost", image:"images/Normal/runerigus.png" },
    868: { name: "Milcery", type: "Fairy", image:"images/Normal/milcery.png" },
    869: { name: "Alcremie", type: "Fairy", image:"images/Normal/alcremie.png" },
    870: { name: "Falinks", type: "Fighting", image:"images/Normal/falinks.png" },
    871: { name: "Pincurchin", type: "Electric", image:"images/Normal/pincurchin.png" },
    872: { name: "Snom", type: "Ice · Bug", image:"images/Normal/snom.png" },
    873: { name: "Frosmoth", type: "Ice · Bug", image:"images/Normal/frosmoth.png" },
    874: { name: "Stonjourner", type: "Rock", image:"images/Normal/stonjourner.png" },
    875: { name: "Eiscue", type: "Ice", image:"images/Normal/eiscue.png" },
    876: { name: "Indeedee", type: "Psychic · Normal", image:"images/Normal/indeedee.png" },
    877: { name: "Morpeko", type: "Electric · Dark", image:"images/Normal/morpeko.png" },
    878: { name: "Cufant", type: "Steel", image:"images/Normal/cufant.png" },
    879: { name: "Copperajah", type: "Steel", image:"images/Normal/copperajah.png" },
    880: { name: "Dracozolt", type: "Electric · Dragon", image:"images/Normal/dracozolt.png" },
    881: { name: "Arctozolt", type: "Electric · Ice", image:"images/Normal/arctozolt.png" },
    882: { name: "Dracovish", type: "Water · Dragon", image:"images/Normal/dracovish.png" },
    883: { name: "Arctovish", type: "Water · Ice", image:"images/Normal/arctovish.png" },
    884: { name: "Duraludon", type: "Steel · Dragon", image:"images/Normal/duraludon.png" },
    885: { name: "Dreepy", type: "Dragon · Ghost", image:"images/Normal/dreepy.png" },
    886: { name: "Drakloak", type: "Dragon · Ghost", image:"images/Normal/drakloak.png" },
    887: { name: "Dragapult", type: "Dragon · Ghost", image:"images/Normal/dragapult.png" },
    888: { name: "Zacian", type: "Fairy", image:"images/Normal/zacian.png" },
    889: { name: "Zamazenta", type: "Fighting", image:"images/Normal/zamazenta.png" },
    890: { name: "Eternatus", type: "Poison · Dragon", image:"images/Normal/eternatus.png" },
    891: { name: "Kubfu", type: "Fighting", image:"images/Normal/kubfu.png" },
    892: { name: "Urshifu", type: "Fighting · Dark", image:"images/Normal/urshifu.png" },
    893: { name: "Zarude", type: "Dark · Grass", image:"images/Normal/zarude.png" },
    894: { name: "Regieleki", type: "Electric", image:"images/Normal/regieleki.png" },
    895: { name: "Regidrago", type: "Dragon", image:"images/Normal/regidrago.png" },
    896: { name: "Glastrier", type: "Ice", image:"images/Normal/glastrier.png" },
    897: { name: "Spectrier", type: "Ghost", image:"images/Normal/spectrier.png" },
    898: { name: "Calyrex", type: "Psychic · Grass", image:"images/Normal/calyrex.png" },
    899: { name: "Wyrdeer", type: "Normal · Psychic", image:"images/Normal/wyrdeer.png" },
    900: { name: "Kleavor", type: "Bug · Rock", image:"images/Normal/kleavor.png" },
    901: { name: "Ursaluna", type: "Ground · Normal", image:"images/Normal/ursaluna.png" },
    902: { name: "Basculegion", type: "Water · Ghost", image:"images/Normal/basculegion.png" },
    903: { name: "Sneasler", type: "Fighting · Poison", image:"images/Normal/sneasler.png" },
    904: { name: "Overqwil", type: "Dark · Poison", image:"images/Normal/overqwil.png" },
    905: { name: "Enamorus", type: "Fairy · Flying", image:"images/Normal/enamorus.png" },
    906: { name: "Sprigatito", type: "Grass", image:"images/Normal/sprigatito.png" },
    907: { name: "Floragato", type: "Grass", image:"images/Normal/floragato.png" },
    908: { name: "Meowscarada", type: "Grass · Dark", image:"images/Normal/meowscarada.png" },
    909: { name: "Fuecoco", type: "Fire", image:"images/Normal/fuecoco.png" },
    910: { name: "Crocalor", type: "Fire", image:"images/Normal/crocalor.png" },
    911: { name: "Skeledirge", type: "Fire · Ghost", image:"images/Normal/skeledirge.png" },
    912: { name: "Quaxly", type: "Water", image:"images/Normal/quaxly.png" },
    913: { name: "Quaxwell", type: "Water", image:"images/Normal/quaxwell.png" },
    914: { name: "Quaquaval", type: "Water · Fighting", image:"images/Normal/quaquaval.png" },
    915: { name: "Lechonk", type: "Normal", image:"images/Normal/lechonk.png" },
    916: { name: "Oinkologne", type: "Normal", image:"images/Normal/oinkologne.png" },
    917: { name: "Tarountula", type: "Bug", image:"images/Normal/tarountula.png" },
    918: { name: "Spidops", type: "Bug", image:"images/Normal/spidops.png" },
    919: { name: "Nymble", type: "Bug", image:"images/Normal/nymble.png" },
    920: { name: "Lokix", type: "Bug · Dark", image:"images/Normal/lokix.png" },
    921: { name: "Pawmi", type: "Electric", image:"images/Normal/pawmi.png" },
    922: { name: "Pawmo", type: "Electric · Fighting", image:"images/Normal/pawmo.png" },
    923: { name: "Pawmot", type: "Electric · Fighting", image:"images/Normal/pawmot.png" },
    924: { name: "Tandemaus", type: "Normal", image:"images/Normal/tandemaus.png" },
    925: { name: "Maushold", type: "Normal", image:"images/Normal/maushold.png" },
    926: { name: "Fidough", type: "Fairy", image:"images/Normal/fidough.png" },
    927: { name: "Dachsbun", type: "Fairy", image:"images/Normal/dachsbun.png" },
    928: { name: "Smoliv", type: "Grass · Normal", image:"images/Normal/smoliv.png" },
    929: { name: "Dolliv", type: "Grass · Normal", image:"images/Normal/dolliv.png" },
    930: { name: "Arboliva", type: "Grass · Normal", image:"images/Normal/arboliva.png" },
    931: { name: "Squawkabilly", type: "Normal · Flying", image:"images/Normal/squawkabilly.png" },
    932: { name: "Nacli", type: "Rock", image:"images/Normal/nacli.png" },
    933: { name: "Naclstack", type: "Rock", image:"images/Normal/naclstack.png" },
    934: { name: "Garganacl", type: "Rock", image:"images/Normal/garganacl.png" },
    935: { name: "Charcadet", type: "Fire", image:"images/Normal/charcadet.png" },
    936: { name: "Armarouge", type: "Fire · Psychic", image:"images/Normal/armarouge.png" },
    937: { name: "Ceruledge", type: "Fire · Ghost", image:"images/Normal/ceruledge.png" },
    938: { name: "Tadbulb", type: "Electric", image:"images/Normal/tadbulb.png" },
    939: { name: "Bellibolt", type: "Electric", image:"images/Normal/bellibolt.png" },
    940: { name: "Wattrel", type: "Electric · Flying", image:"images/Normal/wattrel.png" },
    941: { name: "Kilowattrel", type: "Electric · Flying", image:"images/Normal/kilowattrel.png" },
    942: { name: "Maschiff", type: "Dark", image:"images/Normal/maschiff.png" },
    943: { name: "Mabosstiff", type: "Dark", image:"images/Normal/mabosstiff.png" },
    944: { name: "Shroodle", type: "Poison · Normal", image:"images/Normal/shroodle.png" },
    945: { name: "Grafaiai", type: "Poison · Normal", image:"images/Normal/grafaiai.png" },
    946: { name: "Bramblin", type: "Grass · Ghost", image:"images/Normal/bramblin.png" },
    947: { name: "Brambleghast", type: "Grass · Ghost", image:"images/Normal/brambleghast.png" },
    948: { name: "Toedscool", type: "Ground · Grass", image:"images/Normal/toedscool.png" },
    949: { name: "Toedscruel", type: "Ground · Grass", image:"images/Normal/toedscruel.png" },
    950: { name: "Klawf", type: "Rock", image:"images/Normal/klawf.png" },
    951: { name: "Capsakid", type: "Grass", image:"images/Normal/capsakid.png" },
    952: { name: "Scovillain", type: "Grass · Fire", image:"images/Normal/scovillain.png" },
    953: { name: "Rellor", type: "Bug", image:"images/Normal/rellor.png" },
    954: { name: "Rabsca", type: "Bug · Psychic", image:"images/Normal/rabsca.png" },
    955: { name: "Flittle", type: "Psychic", image:"images/Normal/flittle.png" },
    956: { name: "Espathra", type: "Psychic", image:"images/Normal/espathra.png" },
    957: { name: "Tinkatink", type: "Fairy · Steel", image:"images/Normal/tinkatink.png" },
    958: { name: "Tinkatuff", type: "Fairy · Steel", image:"images/Normal/tinkatuff.png" },
    959: { name: "Tinkaton", type: "Fairy · Steel", image:"images/Normal/tinkaton.png" },
    960: { name: "Wiglett", type: "Water", image:"images/Normal/wiglett.png" },
    961: { name: "Wugtrio", type: "Water", image:"images/Normal/wugtrio.png" },
    962: { name: "Bombirdier", type: "Flying · Dark", image:"images/Normal/bombirdier.png" },
    963: { name: "Finizen", type: "Water", image:"images/Normal/finizen.png" },
    964: { name: "Palafin", type: "Water", image:"images/Normal/palafin.png" },
    965: { name: "Varoom", type: "Steel · Poison", image:"images/Normal/varoom.png" },
    966: { name: "Revavroom", type: "Steel · Poison", image:"images/Normal/revavroom.png" },
    967: { name: "Cyclizar", type: "Dragon · Normal", image:"images/Normal/cyclizar.png" },
    968: { name: "Orthworm", type: "Steel", image:"images/Normal/orthworm.png" },
    969: { name: "Glimmet", type: "Rock · Poison", image:"images/Normal/glimmet.png" },
    970: { name: "Glimmora", type: "Rock · Poison", image:"images/Normal/glimmora.png" },
    971: { name: "Greavard", type: "Ghost", image:"images/Normal/greavard.png" },
    972: { name: "Houndstone", type: "Ghost", image:"images/Normal/houndstone.png" },
    973: { name: "Flamigo", type: "Flying · Fighting", image:"images/Normal/flamigo.png" },
    974: { name: "Cetoddle", type: "Ice", image:"images/Normal/cetoddle.png" },
    975: { name: "Cetitan", type: "Ice", image:"images/Normal/cetitan.png" },
    976: { name: "Veluza", type: "Water · Psychic", image:"images/Normal/veluza.png" },
    977: { name: "Dondozo", type: "Water", image:"images/Normal/dondozo.png" },
    978: { name: "Tatsugiri", type: "Dragon · Water", image:"images/Normal/tatsugiri.png" },
    979: { name: "Annihilape", type: "Fighting · Ghost", image:"images/Normal/annihilape.png" },
    980: { name: "Clodsire", type: "Poison · Ground", image:"images/Normal/clodsire.png" },
    981: { name: "Farigiraf", type: "Normal · Psychic", image:"images/Normal/farigiraf.png" },
    982: { name: "Dudunsparce", type: "Normal", image:"images/Normal/dudunsparce.png" },
    983: { name: "Kingambit", type: "Dark · Steel", image:"images/Normal/kingambit.png" },
    984: { name: "Great Tusk", type: "Ground · Fighting", image:"images/Normal/great tusk.png" },
    985: { name: "Scream Tail", type: "Fairy · Psychic", image:"images/Normal/scream tail.png" },
    986: { name: "Brute Bonnet", type: "Grass · Dark", image:"images/Normal/brute bonnet.png" },
    987: { name: "Flutter Mane", type: "Ghost · Fairy", image:"images/Normal/flutter mane.png" },
    988: { name: "Slither Wing", type: "Bug · Fighting", image:"images/Normal/slither wing.png" },
    989: { name: "Sandy Shocks", type: "Electric · Ground", image:"images/Normal/sandy shocks.png" },
    990: { name: "Iron Treads", type: "Ground · Steel", image:"images/Normal/iron treads.png" },
    991: { name: "Iron Bundle", type: "Ice · Water", image:"images/Normal/iron bundle.png" },
    992: { name: "Iron Hands", type: "Fighting · Electric", image:"images/Normal/iron hands.png" },
    993: { name: "Iron Jugulis", type: "Dark · Flying", image:"images/Normal/iron jugulis.png" },
    994: { name: "Iron Moth", type: "Fire · Poison", image:"images/Normal/iron moth.png" },
    995: { name: "Iron Thorns", type: "Rock · Electric", image:"images/Normal/iron thorns.png" },
    996: { name: "Frigibax", type: "Dragon · Ice", image:"images/Normal/frigibax.png" },
    997: { name: "Arctibax", type: "Dragon · Ice", image:"images/Normal/arctibax.png" },
    998: { name: "Baxcalibur", type: "Dragon · Ice", image:"images/Normal/baxcalibur.png" },
    999: { name: "Gimmighoul", type: "Ghost", image:"images/Normal/gimmighoul.png" },
    1000: { name: "Gholdengo", type: "Steel · Ghost", image:"images/Normal/gholdengo.png" },
    1001: { name: "Wo-Chien", type: "Dark · Grass", image:"images/Normal/wo-chien.png" },
    1002: { name: "Chien-Pao", type: "Dark · Ice", image:"images/Normal/chien-pao.png" },
    1003: { name: "Ting-Lu", type: "Dark · Ground", image:"images/Normal/ting-lu.png" },
    1004: { name: "Chi-Yu", type: "Dark · Fire", image:"images/Normal/chi-yu.png" },
    1005: { name: "Roaring Moon", type: "Dragon · Dark", image:"images/Normal/roaring moon.png" },
    1006: { name: "Iron Valiant", type: "Fairy · Fighting", image:"images/Normal/iron valiant.png" },
    1007: { name: "Koraidon", type: "Dragon · Fighting", image:"images/Normal/koraidon.png" },
    1008: { name: "Miraidon", type: "Dragon · Electric", image:"images/Normal/miraidon.png" },
    1009: { name: "Walking Wake", type: "Dragon · Water", image:"images/Normal/walking_wake.png" },
    1010: { name: "Iron Leaves", type: "Grass · Psychic", image:"images/Normal/iron leaves.png" },
    1011: { name: "Dipplin", type: "Grass · Dragon", image:"images/Normal/dipplin.png" },
    1012: { name: "Poltchageist", type: "Grass · Ghost", image:"images/Normal/poltchageist.png" },
    1013: { name: "Sinistcha", type: "Grass · Ghost", image:"images/Normal/sinistcha.png" },
    1014: { name: "Okidogi", type: "Poison · Fighting", image:"images/Normal/okidogi.png" },
    1015: { name: "Munkidori", type: "Poison · Psychic", image:"images/Normal/munkidori.png" },
    1016: { name: "Fezandipiti", type: "Poison · Fairy", image:"images/Normal/fezandipiti.png" },
    1017: { name: "Ogerpon", type: "Grass", image:"images/Normal/ogerpon.png" },
    1018: { name: "Archaludon", type: "Steel · Dragon", image:"images/Normal/archalundon.png" },
    1019: { name: "Hydrapple", type: "Grass · Dragon", image:"images/Normal/hydrapple.png" },
    1020: { name: "Gouging Fire", type: "Fire · Dragon", image:"images/Normal/gouging fire.png" },
    1021: { name: "Raging Bolt", type: "Electric · Dragon", image:"images/Normal/raging bolt.png" },
    1022: { name: "Iron Boulder", type: "Rock · Psychic", image:"images/Normal/iron boulder.png" },
    1023: { name: "Iron Crown", type: "Steel · Psychic", image:"images/Normal/iron crown.png" },
    1024: { name: "Terapagos", type: "Normal", image:"images/Normal/terapagos.png" },
    1025: { name: "Pecharunt", type: "Poison · Ghost", image:"images/Normal/pecharunt.png" }
    },

};
function loadNationalDex() {
    const pokemonGrid = document.getElementById("pokedex");
    const pokedex = pokedexData.national;

    pokemonGrid.innerHTML = '';

    for (const number in pokedex) {
        const pokemon = pokedex[number];

        const pokemonBox = document.createElement("div");
        pokemonBox.className = "pokemon-box";
        pokemonBox.innerHTML = `
            <div class="pokemon-number">#${number}</div>
            <div class="pokemon-name">${capitalize(pokemon.name)}</div>
            <div class="pokemon-type">${pokemon.type}</div>
            <img src="${pokemon.image}" alt="${pokemon.name}" class="pokemon-image">
        `;

        pokemonGrid.appendChild(pokemonBox);
    }
}

function capitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
}

// Optional: "Back" button
function goBack() {
    document.getElementById('pokedex-section').classList.add('hidden');
    document.getElementById('game-selection').classList.remove('hidden');
}

document.addEventListener("DOMContentLoaded", () => {
    loadNationalDex();
});
